import { STUDIO_VRM_EXPORT_REQUIRED_BONES } from "./studio-vrm-export-vrm-extension";
import { inspectVrmGlbBytes, validateVrmGlbBytes } from "./vrm-library";

export type StudioVrmGenerateHumanoidInspection = {
  readonly vrmVersion: 0 | 1;
  readonly humanoidBoneNames: readonly string[];
  readonly isCompleteHumanoid: boolean;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Reads the shipped VRM/GLB inspector and reports whether the 15 required humanoid bones exist. */
export function inspectGeneratedVrmHumanoid(
  bytes: ArrayBuffer | Uint8Array,
): StudioVrmGenerateHumanoidInspection {
  const inspected = inspectVrmGlbBytes(bytes);
  validateVrmGlbBytes(bytes);
  const extensions = isRecord(inspected.json.extensions) ? inspected.json.extensions : {};
  const vrmc = isRecord(extensions.VRMC_vrm) ? extensions.VRMC_vrm : {};
  const humanoid = isRecord(vrmc.humanoid) ? vrmc.humanoid : {};
  const humanBones = isRecord(humanoid.humanBones) ? humanoid.humanBones : {};
  const humanoidBoneNames = Object.keys(humanBones).sort();
  return {
    vrmVersion: inspected.vrmVersion,
    humanoidBoneNames,
    isCompleteHumanoid: STUDIO_VRM_EXPORT_REQUIRED_BONES.every((bone) =>
      Object.prototype.hasOwnProperty.call(humanBones, bone),
    ),
  };
}

/**
 * Reloads generated bytes with the same GLTFLoader + VRMLoaderPlugin pair the Studio viewport uses.
 */
export async function reloadGeneratedVrmAsHumanoid(
  bytes: ArrayBuffer | Uint8Array,
): Promise<{
  readonly name: string | null;
  readonly presentBones: readonly string[];
  readonly missingBones: readonly string[];
}> {
  const { GLTFLoader } = await import("three/examples/jsm/loaders/GLTFLoader.js");
  const { VRMLoaderPlugin } = await import("@pixiv/three-vrm");
  const source = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  const buffer = new ArrayBuffer(source.byteLength);
  new Uint8Array(buffer).set(source);
  const loader = new GLTFLoader();
  loader.register((parser) => new VRMLoaderPlugin(parser));
  const gltf = await loader.parseAsync(buffer, "");
  const vrm = (gltf.userData as {
    vrm?: {
      meta?: { name?: string };
      humanoid?: { getNormalizedBoneNode(name: string): unknown };
    };
  }).vrm;
  if (!vrm?.humanoid) {
    throw new TypeError("생성된 VRM을 휴머노이드로 다시 불러오지 못했습니다.");
  }
  const presentBones = STUDIO_VRM_EXPORT_REQUIRED_BONES.filter(
    (bone) => vrm.humanoid?.getNormalizedBoneNode(bone) != null,
  );
  return {
    name: vrm.meta?.name ?? null,
    presentBones,
    missingBones: STUDIO_VRM_EXPORT_REQUIRED_BONES.filter((bone) => !presentBones.includes(bone)),
  };
}
