import type { StrokeStyle } from "../brush/studio-stroke-shapes";
import type { BubbleVariant } from "../studio-assets";

export interface BubbleStylePreset {
  id: string;
  label: string;
  description: string;
  fill: string;
  textFill: string;
  stroke?: string;
  strokeWidth?: number;
  strokeStyle?: StrokeStyle; // 점선 등(studio-stroke-shapes) — 지정하면 프리셋 적용 시 함께 바뀐다.
  variant?: BubbleVariant; // 지정하면 프리셋 적용 시 말풍선 모양(variant)도 함께 바뀐다. 미지정이면 현재 모양 유지.
  starAmplitude?: number; // shout/angry 등 Star 기반 variant의 안쪽 반경 비율(0..1) 오버라이드.
  shadowColor?: string;
  shadowBlur?: number;
  shadowOffsetX?: number;
  shadowOffsetY?: number;
  shadowOpacity?: number;
  font?: string;
}

export const BUBBLE_STYLE_PRESETS: BubbleStylePreset[] = [
  {
    id: "classic_white",
    label: "기본 흰색",
    description: "보편적인 웹툰 말풍선",
    variant: "speech",
    fill: "#fffdfa",
    textFill: "#211d19",
    stroke: "#211d19",
    strokeWidth: 2,
    shadowColor: "#000000",
    shadowBlur: 4,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    shadowOpacity: 0.12,
  },
  {
    id: "classic_black",
    label: "속마음/독백",
    description: "어두운 분위기 또는 독백",
    variant: "thought",
    fill: "#1b1a20",
    textFill: "#efece4",
    stroke: "#4c4b56",
    strokeWidth: 1.75,
    shadowColor: "#000000",
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 3,
    shadowOpacity: 0.28,
  },
  {
    id: "warm_cream",
    label: "따뜻한 크림",
    description: "아늑한 일상과 잔잔한 대화",
    variant: "speech",
    fill: "#f7efdd",
    textFill: "#3a2f24",
    stroke: "#8a7358",
    strokeWidth: 2,
    shadowColor: "#5c4a34",
    shadowBlur: 3,
    shadowOffsetX: 0,
    shadowOffsetY: 1,
    shadowOpacity: 0.1,
    font: "Gaegu",
  },
  {
    id: "pastel_pink",
    label: "설렘 핑크",
    description: "두근거리는 로맨스, 플러팅 씬",
    variant: "heart",
    fill: "#fbeef1",
    textFill: "#9a3b57",
    stroke: "#d9a3b2",
    strokeWidth: 2,
    shadowColor: "#e3aebb",
    shadowBlur: 6,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    shadowOpacity: 0.18,
    font: "Gamja Flower",
  },
  {
    id: "action_red",
    label: "격앙 레드",
    description: "분노, 격돌, 외침 씬",
    variant: "angry",
    starAmplitude: 0.45,
    fill: "#7e2420",
    textFill: "#fbf2ea",
    stroke: "#2a0e0d",
    strokeWidth: 4,
    shadowColor: "#000000",
    shadowBlur: 3,
    shadowOffsetX: 1,
    shadowOffsetY: 1,
    shadowOpacity: 0.3,
    font: "Black Han Sans",
  },
  {
    id: "horror_purple",
    label: "공포 퍼플",
    description: "기괴하고 오싹한 공포/미스터리 씬",
    variant: "scared",
    fill: "#1c1622",
    textFill: "#d7d2db",
    stroke: "#5a3f6b",
    strokeWidth: 2.25,
    shadowColor: "#000000",
    shadowBlur: 10,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    shadowOpacity: 0.4,
    font: "'East Sea Dokdo', cursive",
  },
  {
    id: "cyber_cyan",
    label: "네온 사이언",
    description: "SF, 기계음, 상태창 메시지",
    variant: "system",
    fill: "#0b0f1a",
    textFill: "#b8f2f5",
    stroke: "#2e9aa3",
    strokeWidth: 2,
    shadowColor: "#2ed3e0",
    shadowBlur: 6,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowOpacity: 0.35,
    font: "Jua",
  },
  {
    id: "phone_green",
    label: "모바일 메신저",
    description: "채팅 앱 UI 스타일 말풍선",
    variant: "phone",
    fill: "#eef1f4",
    textFill: "#23272f",
    stroke: "#d3d8de",
    strokeWidth: 1.25,
    shadowColor: "#000000",
    shadowBlur: 4,
    shadowOffsetX: 0,
    shadowOffsetY: 1,
    shadowOpacity: 0.08,
  },
  {
    id: "narration_box",
    label: "내레이션 박스",
    description: "장면 설명, 시간/장소 자막",
    variant: "box",
    fill: "#211f24",
    textFill: "#e9e5dd",
    stroke: "#3c3a42",
    strokeWidth: 1,
    shadowColor: "#000000",
    shadowBlur: 4,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    shadowOpacity: 0.2,
  },
  {
    id: "deadpan_sarcasm",
    label: "무표정 개그",
    description: "비꼼, 정색, 드라이한 리액션",
    variant: "box",
    fill: "#e9e6e1",
    textFill: "#57534b",
    stroke: "#b3ada2",
    strokeWidth: 1.5,
  },
  {
    id: "flashback_memory",
    label: "회상/기억",
    description: "아련하고 흐릿한 과거 회상 씬",
    variant: "thought",
    fill: "#e6e0e9",
    textFill: "#5d5468",
    stroke: "#b6abc4",
    strokeWidth: 1.75,
    shadowColor: "#8b7fa3",
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 2,
    shadowOpacity: 0.15,
    font: "Nanum Pen Script",
  },
  {
    id: "hushed_whisper",
    label: "속삭임",
    description: "조용히 소곤대는 귓속말, ASMR 대사",
    variant: "whisper",
    fill: "#fbfbfe",
    textFill: "#5b5f6b",
    stroke: "#b9bdc7",
    strokeWidth: 1.25,
    strokeStyle: { dash: "dot", lineCap: "round", arrowStart: "none", arrowEnd: "none" },
  },
  {
    id: "mecha_transmission",
    label: "전화/기계음",
    description: "무전기·전화·안내음성 등 딱딱한 기계 대사",
    variant: "box",
    fill: "#202832",
    textFill: "#d7dde3",
    stroke: "#5b6472",
    strokeWidth: 2.5,
    strokeStyle: { dash: "solid", lineCap: "square", arrowStart: "none", arrowEnd: "none" },
    shadowColor: "#5b6472",
    shadowBlur: 4,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowOpacity: 0.3,
  },
  {
    id: "trembling_fear",
    label: "다급함/공포",
    description: "겁에 질려 떨리는 다급한 대사",
    variant: "scared",
    fill: "#eef0f5",
    textFill: "#2a2f3a",
    stroke: "#4b4f5c",
    strokeWidth: 2,
    strokeStyle: { dash: "dash", lineCap: "round", arrowStart: "none", arrowEnd: "none" },
  },
];
