const KO = {
  common: {
    all: "전체",
    cancel: "취소",
    close: "닫기",
    confirm: "확인",
    delete: "삭제",
    edit: "수정",
    exportCsv: "CSV 내보내기",
    next: "다음",
    previous: "이전",
    refresh: "새로고침",
    save: "저장",
    saving: "저장 중…",
  },
  console: {
    navLabel: "관리 영역",
    tabPanelLabel: "관리자 콘솔 작업 영역",
  },
  dashboard: {
    actionCenterTitle: "운영 액션 센터",
    actionCenterDesc: "즉시 확인하거나 처리해야 할 항목을 우선순위별로 모았습니다.",
    periodLabel: "집계 기간",
    refreshing: "갱신 중…",
    partialWarning: "일부 운영 데이터가 지연되어 마지막 정상 값 또는 0으로 표시됩니다.",
    pendingReports: "미처리 신고",
    pendingReportsDesc: "콘텐츠 신고 큐를 검토하고 조치합니다.",
    pendingSettlements: "대기 정산",
    pendingSettlementsDesc: "승인 또는 반려가 필요한 정산 이벤트입니다.",
    criticalAnnouncements: "활성 긴급 공지",
    criticalAnnouncementsDesc: "현재 사용자에게 노출 중인 긴급 공지입니다.",
    systemStatus: "시스템 상태",
    maintenance: "점검 모드가 활성화되어 있습니다.",
    degraded: "시스템 상태가 저하되었습니다.",
    healthy: "정상 운영 중입니다.",
    open: "바로가기",
    allClear: "현재 즉시 대응이 필요한 운영 항목이 없습니다.",
    lastUpdated: "마지막 갱신",
  },
  members: {
    filtersTitle: "회원 필터",
    roleAll: "모든 역할",
    statusAll: "모든 상태",
    sortNewest: "최근 가입순",
    sortOldest: "오래된 가입순",
    sortNameAsc: "이름 오름차순",
    sortNameDesc: "이름 내림차순",
    pageSize: "페이지당",
    resetFilters: "필터 초기화",
    exportFiltered: "현재 조건 CSV",
    selectPage: "현재 페이지 전체 선택",
    selectedCount: "{count}명 선택",
    totalCount: "총 {count}명",
    pageOf: "{page} / {pages} 페이지",
    details: "상세",
    detailsTitle: "회원 상세",
    bulkSuspend: "선택 정지",
    bulkRestore: "선택 복구",
    noSelection: "먼저 회원을 선택해 주세요.",
    actionReason: "사유",
    actionReasonOptional: "운영 이력에 남길 사유를 입력하세요.",
    roleChangeTitle: "회원 역할 변경",
    suspendTitle: "회원 계정 정지",
    restoreTitle: "회원 계정 복구",
    deleteTitle: "회원 탈퇴 처리",
    bulkSuspendTitle: "선택 회원 일괄 정지",
    bulkRestoreTitle: "선택 회원 일괄 복구",
    destructiveWarning: "이 작업은 즉시 적용되며 감사 로그에 남습니다.",
    updateSuccess: "회원 정보가 업데이트되었습니다.",
    bulkSuccess: "{count}명의 상태를 변경했습니다.",
    exportSuccess: "회원 CSV를 내려받았습니다.",
    exportError: "회원 CSV를 내려받지 못했습니다.",
    accountSection: "계정",
    activitySection: "활동",
    paymentSection: "결제",
    posts: "게시글",
    reviews: "리뷰",
    ratings: "평점",
    paid: "누적 결제",
    emptyDetail: "상세 정보를 불러오지 못했습니다.",
  },
  announcements: {
    create: "새 공지 만들기",
    edit: "공지 수정",
    preview: "실시간 미리보기",
    filters: "노출 상태",
    statusAll: "전체",
    statusActive: "노출 중",
    statusScheduled: "예약",
    statusExpired: "종료",
    statusInactive: "비활성",
    schedule: "노출 일정",
    startsAt: "시작 일시",
    endsAt: "종료 일시",
    activeToggle: "활성화",
    activeDesc: "활성화되어 있어도 예약 시작 전이거나 종료 후에는 노출되지 않습니다.",
    noStart: "즉시 시작",
    noEnd: "종료 없음",
    editAction: "수정",
    duplicateAction: "복제",
    scheduleError: "종료 일시는 시작 일시보다 뒤여야 합니다.",
    saveSuccess: "공지사항을 저장했습니다.",
    deleteSuccess: "공지사항을 삭제했습니다.",
    toggleSuccess: "공지 노출 상태를 변경했습니다.",
    deleteConfirmTitle: "공지사항 삭제",
    deleteConfirmDesc: "삭제한 공지는 복구할 수 없습니다.",
    emptyFiltered: "조건에 맞는 공지사항이 없습니다.",
    targetPrefix: "대상",
    createdPrefix: "생성",
  },
  reports: {
    searchPlaceholder: "신고 사유·신고자·대상 ID 검색",
    targetAll: "모든 대상",
    selectedCount: "{count}건 선택",
    selectPage: "현재 목록 전체 선택",
    bulkResolve: "선택 해결",
    bulkDismiss: "선택 기각",
    note: "처리 메모",
    notePlaceholder: "판단 근거와 후속 조치를 기록하세요.",
    bulkTitle: "신고 일괄 처리",
    resolveTitle: "신고 해결 처리",
    dismissTitle: "신고 기각 처리",
    processSuccess: "{count}건의 신고를 처리했습니다.",
    partialFailure: "{failed}건은 처리하지 못했습니다.",
    viewTarget: "대상 열기",
    refresh: "신고 새로고침",
  },
} as const;

const EN = {
  common: {
    all: "All",
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    exportCsv: "Export CSV",
    next: "Next",
    previous: "Previous",
    refresh: "Refresh",
    save: "Save",
    saving: "Saving…",
  },
  console: {
    navLabel: "Administration areas",
    tabPanelLabel: "Admin console workspace",
  },
  dashboard: {
    actionCenterTitle: "Operations action center",
    actionCenterDesc: "Prioritized items that need review or action.",
    periodLabel: "Reporting period",
    refreshing: "Refreshing…",
    partialWarning: "Some operational data is delayed; the last healthy value or zero is shown.",
    pendingReports: "Pending reports",
    pendingReportsDesc: "Review and resolve the content report queue.",
    pendingSettlements: "Pending settlements",
    pendingSettlementsDesc: "Revenue events awaiting approval or rejection.",
    criticalAnnouncements: "Active critical notices",
    criticalAnnouncementsDesc: "Critical notices currently visible to users.",
    systemStatus: "System status",
    maintenance: "Maintenance mode is enabled.",
    degraded: "System health is degraded.",
    healthy: "All monitored systems are healthy.",
    open: "Open",
    allClear: "There are no urgent operational items right now.",
    lastUpdated: "Last updated",
  },
  members: {
    filtersTitle: "Member filters",
    roleAll: "All roles",
    statusAll: "All statuses",
    sortNewest: "Newest first",
    sortOldest: "Oldest first",
    sortNameAsc: "Name A–Z",
    sortNameDesc: "Name Z–A",
    pageSize: "Per page",
    resetFilters: "Reset filters",
    exportFiltered: "Export current filters",
    selectPage: "Select current page",
    selectedCount: "{count} selected",
    totalCount: "{count} total",
    pageOf: "Page {page} of {pages}",
    details: "Details",
    detailsTitle: "Member details",
    bulkSuspend: "Suspend selected",
    bulkRestore: "Restore selected",
    noSelection: "Select at least one member first.",
    actionReason: "Reason",
    actionReasonOptional: "Add a reason for the operational record.",
    roleChangeTitle: "Change member role",
    suspendTitle: "Suspend member account",
    restoreTitle: "Restore member account",
    deleteTitle: "Delete member account",
    bulkSuspendTitle: "Suspend selected members",
    bulkRestoreTitle: "Restore selected members",
    destructiveWarning: "This takes effect immediately and is recorded in the audit log.",
    updateSuccess: "Member information was updated.",
    bulkSuccess: "Updated {count} members.",
    exportSuccess: "Member CSV downloaded.",
    exportError: "Member CSV download failed.",
    accountSection: "Account",
    activitySection: "Activity",
    paymentSection: "Payments",
    posts: "Posts",
    reviews: "Reviews",
    ratings: "Ratings",
    paid: "Lifetime paid",
    emptyDetail: "Member details could not be loaded.",
  },
  announcements: {
    create: "Create notice",
    edit: "Edit notice",
    preview: "Live preview",
    filters: "Visibility status",
    statusAll: "All",
    statusActive: "Live",
    statusScheduled: "Scheduled",
    statusExpired: "Ended",
    statusInactive: "Inactive",
    schedule: "Visibility schedule",
    startsAt: "Starts",
    endsAt: "Ends",
    activeToggle: "Enabled",
    activeDesc: "An enabled notice is still hidden before its start time and after its end time.",
    noStart: "Start immediately",
    noEnd: "No end date",
    editAction: "Edit",
    duplicateAction: "Duplicate",
    scheduleError: "The end time must be later than the start time.",
    saveSuccess: "Announcement saved.",
    deleteSuccess: "Announcement deleted.",
    toggleSuccess: "Announcement visibility updated.",
    deleteConfirmTitle: "Delete announcement",
    deleteConfirmDesc: "Deleted announcements cannot be recovered.",
    emptyFiltered: "No announcements match the selected status.",
    targetPrefix: "Target",
    createdPrefix: "Created",
  },
  reports: {
    searchPlaceholder: "Search reason, reporter, or target ID",
    targetAll: "All targets",
    selectedCount: "{count} selected",
    selectPage: "Select all visible",
    bulkResolve: "Resolve selected",
    bulkDismiss: "Dismiss selected",
    note: "Resolution note",
    notePlaceholder: "Record the rationale and any follow-up action.",
    bulkTitle: "Process selected reports",
    resolveTitle: "Resolve report",
    dismissTitle: "Dismiss report",
    processSuccess: "Processed {count} reports.",
    partialFailure: "{failed} reports failed.",
    viewTarget: "Open target",
    refresh: "Refresh reports",
  },
} as const;

export type AdminAdvancedCopy = typeof KO;

export function getAdminAdvancedCopy(locale: string): AdminAdvancedCopy {
  return locale.toLowerCase().startsWith("ko") ? KO : (EN as unknown as AdminAdvancedCopy);
}
