import { STUDIO_AUTHORED_SCENE_TEMPLATES } from "./catalog/studio-authored-scene-templates";

/**
 * Studio Scene Templates — 원클릭 "장면 템플릿" 라이브러리.
 *
 * 기존 startFromExample 은 샘플 프레임 + 말풍선 한 개짜리 단일 예시뿐이었다. 이 모듈은
 * 코미포·툰스푼의 "캐릭터·말풍선·효과를 한 번에" 발상을 따라, 자주 쓰는 연출(고백·액션·
 * 회상·긴장 클로즈업…)을 프레임+말풍선+효과선+효과음 여러 요소로 미리 조합해 한 번에
 * 캔버스에 깔아준다. 장르 카탈로그 20종: 학원·로맨스·액션·판타지·일상·연출.
 *
 * 각 템플릿의 build(originX, originY)는 id 없는 SceneSeed 배열을 돌려준다 — 메인 루프가
 * crypto.randomUUID()로 id를 채워 El 로 만든다. SceneSeed 필드명은 El 유니온과 1:1로
 * 맞춰야 한다(여기가 통합 계약). 전부 순수·결정적. 사용자 노출 문자열은 한글.
 *
 * 좌표 규약: build(0,0) 기준 모든 x가 [0, 720](CANVAS_W) 안에 들어오게 배치한다.
 */

const CANVAS_W = 720;

type BubbleVariant =
  | "speech"
  | "double"
  | "thought"
  | "shout"
  | "box"
  | "whisper"
  | "scared"
  | "system"
  | "heart"
  | "phone"
  | "angry";
type Align = "left" | "center" | "right";
type FontStyle = "normal" | "bold" | "italic" | "bold italic";

export type SceneSeedFrame = {
  type: "frame";
  x: number;
  y: number;
  width: number;
  height: number;
  stroke?: string;
  strokeWidth?: number;
  bgColor?: string;
  dashStyle?: "solid" | "dashed";
};
export type SceneSeedBubble = {
  type: "bubble";
  variant: BubbleVariant;
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fill: string;
  textFill: string;
  rotation: number;
  tail?: "left" | "right" | "none";
  tailDirection?: "bottom" | "top" | "left" | "right";
  font?: string;
  fontSize?: number;
  align?: Align;
  fontStyle?: FontStyle;
};
export type SceneSeedText = {
  type: "text";
  text: string;
  x: number;
  y: number;
  width: number;
  fontSize: number;
  fill: string;
  rotation: number;
  font?: string;
  stroke?: string;
  strokeWidth?: number;
  align?: Align;
  fontStyle?: FontStyle;
};
export type SceneSeedFocusLines = {
  type: "focusLines";
  x: number;
  y: number;
  width: number;
  height: number;
  lineCount: number;
  innerRadius: number;
  outerRadius: number;
  stroke: string;
  strokeWidth: number;
  noise: number;
  rotation: number;
};
export type SceneSeedSpeedLines = {
  type: "speedLines";
  x: number;
  y: number;
  width: number;
  height: number;
  lineCount: number;
  direction: "horizontal" | "vertical";
  stroke: string;
  strokeWidth: number;
  rotation: number;
};
export type SceneSeed =
  | SceneSeedFrame
  | SceneSeedBubble
  | SceneSeedText
  | SceneSeedFocusLines
  | SceneSeedSpeedLines;

export interface SceneTemplate {
  id: string;
  label: string;
  category: string;
  description: string;
  build: (originX: number, originY: number) => SceneSeed[];
}

export const SCENE_TEMPLATE_CATEGORIES: { id: string; label: string }[] = [
  { id: "school", label: "학원" },
  { id: "romance", label: "로맨스" },
  { id: "action", label: "액션·긴장" },
  { id: "fantasy", label: "판타지" },
  { id: "daily", label: "일상·대화" },
  { id: "narrative", label: "연출·타이틀" },
];

// 좌측 안쪽 여백 — build(0,0) 시 x 시작점. 660폭 프레임이 720 안에 들어오게 30.
const PAD = 30;
const INNER_W = CANVAS_W - PAD * 2; // 660

export const SCENE_TEMPLATES: SceneTemplate[] = [
  {
    id: "confession",
    label: "고백 장면",
    category: "romance",
    description: "포근한 프레임 + 대사 두 개 + 두근 효과음",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 460,
        bgColor: "#fff1f4",
        stroke: "#f4b8c6",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "speech",
        text: "저… 사실 너한테 할 말이 있어.",
        x: ox + PAD + 28,
        y: oy + 36,
        width: 300,
        height: 110,
        fill: "#ffffff",
        textFill: "#3a2a30",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "heart",
        text: "응? 무슨 말인데…",
        x: ox + PAD + 320,
        y: oy + 250,
        width: 260,
        height: 110,
        fill: "#ffe3ea",
        textFill: "#a23a55",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "두근",
        x: ox + PAD + 250,
        y: oy + 170,
        width: 160,
        fontSize: 64,
        fill: "#ff5a7a",
        rotation: -8,
        font: "Black Han Sans",
        stroke: "#ffffff",
        strokeWidth: 5,
        align: "center",
      },
    ],
  },
  {
    id: "action-impact",
    label: "액션 컷",
    category: "action",
    description: "집중선 + 외침 말풍선 + 쾅! 효과음",
    build: (ox, oy) => [
      {
        type: "focusLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        lineCount: 60,
        innerRadius: 120,
        outerRadius: 460,
        stroke: "#15100c",
        strokeWidth: 5,
        noise: 0.4,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "shout",
        text: "이게 끝이 아니야!",
        x: ox + PAD + 150,
        y: oy + 60,
        width: 340,
        height: 150,
        fill: "#f7f3ec",
        textFill: "#1c1712",
        rotation: -4,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "text",
        text: "쾅!",
        x: ox + PAD + 200,
        y: oy + 300,
        width: 260,
        fontSize: 120,
        fill: "#ffffff",
        rotation: -10,
        font: "Black Han Sans",
        stroke: "#161616",
        strokeWidth: 9,
        align: "center",
      },
    ],
  },
  {
    id: "daily-talk",
    label: "일상 대화 2컷",
    category: "daily",
    description: "위아래 두 컷 + 주고받는 대사",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 300,
        bgColor: "#ffffff",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "frame",
        x: ox + PAD,
        y: oy + 324,
        width: INNER_W,
        height: 300,
        bgColor: "#ffffff",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "speech",
        text: "오늘 점심 뭐 먹을까?",
        x: ox + PAD + 30,
        y: oy + 36,
        width: 280,
        height: 100,
        fill: "#ffffff",
        textFill: "#2a2620",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "speech",
        text: "음… 떡볶이 어때?",
        x: ox + PAD + 320,
        y: oy + 392,
        width: 280,
        height: 100,
        fill: "#fdf3e7",
        textFill: "#5c4a2e",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
    ],
  },
  {
    id: "flashback",
    label: "회상 장면",
    category: "narrative",
    description: "나레이션 박스 + 흐릿한 점선 프레임",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 440,
        bgColor: "#f3efe7",
        stroke: "#b9ad97",
        strokeWidth: 2,
        dashStyle: "dashed",
      },
      {
        type: "bubble",
        variant: "box",
        text: "그날의 기억은 아직도 선명했다.",
        x: ox + PAD + 40,
        y: oy + 32,
        width: 360,
        height: 96,
        fill: "#fffdf6",
        textFill: "#5a4f3a",
        rotation: 0,
        font: "Nanum Pen Script",
        align: "left",
      },
      {
        type: "text",
        text: "…그때 우리는 어렸다",
        x: ox + PAD + 60,
        y: oy + 320,
        width: 420,
        fontSize: 40,
        fill: "#8a7c60",
        rotation: -3,
        font: "Nanum Pen Script",
        align: "left",
      },
    ],
  },
  {
    id: "tense-closeup",
    label: "긴장 클로즈업",
    category: "action",
    description: "속도선 + 불안 말풍선 + 두근 효과음",
    build: (ox, oy) => [
      {
        type: "speedLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 460,
        lineCount: 48,
        direction: "vertical",
        stroke: "#1a1a22",
        strokeWidth: 4,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "scared",
        text: "설마… 들킨 건가?",
        x: ox + PAD + 130,
        y: oy + 80,
        width: 320,
        height: 130,
        fill: "#e6e9f4",
        textFill: "#242a3d",
        rotation: 0,
        align: "center",
      },
      {
        type: "text",
        text: "철렁…",
        x: ox + PAD + 220,
        y: oy + 300,
        width: 220,
        fontSize: 56,
        fill: "#5a6072",
        rotation: 6,
        font: "Gaegu",
        stroke: "#ffffff",
        strokeWidth: 4,
        align: "center",
      },
    ],
  },
  {
    id: "title-cut",
    label: "타이틀 컷",
    category: "narrative",
    description: "큰 제목 + 부제 박스",
    build: (ox, oy) => [
      {
        type: "text",
        text: "프롤로그",
        x: ox + PAD,
        y: oy + 80,
        width: INNER_W,
        fontSize: 96,
        fill: "#161616",
        rotation: 0,
        font: "Black Han Sans",
        align: "center",
      },
      {
        type: "bubble",
        variant: "box",
        text: "— 모든 것은 그 비 오는 밤부터 시작되었다 —",
        x: ox + PAD + 60,
        y: oy + 240,
        width: INNER_W - 120,
        height: 90,
        fill: "#161616",
        textFill: "#f4f4f4",
        rotation: 0,
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 학원 ─────────────────────────────
  {
    id: "school-classroom",
    label: "교실 수업",
    category: "school",
    description: "교실 컷 + 선생님 대사 + 딴생각 말풍선",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 460,
        bgColor: "#fdf8ec",
        stroke: "#d9c9a6",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "speech",
        text: "자, 오늘은 47페이지부터 볼게요.",
        x: ox + PAD + 24,
        y: oy + 32,
        width: 320,
        height: 104,
        fill: "#ffffff",
        textFill: "#33301f",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "thought",
        text: "…오늘 급식 뭐 나오더라.",
        x: ox + PAD + 340,
        y: oy + 300,
        width: 260,
        height: 104,
        fill: "#f4f6ff",
        textFill: "#4a5064",
        rotation: 0,
        tail: "none",
      },
      {
        type: "text",
        text: "사각사각",
        x: ox + PAD + 60,
        y: oy + 330,
        width: 200,
        fontSize: 40,
        fill: "#b9a97e",
        rotation: -6,
        font: "Gaegu",
        align: "center",
      },
    ],
  },
  {
    id: "school-hallway",
    label: "복도 대치",
    category: "school",
    description: "복도 컷 + 속도선 + 시비 거는 대사",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 440,
        bgColor: "#eef1f5",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "speedLines",
        x: ox + PAD,
        y: oy + 150,
        width: INNER_W,
        height: 140,
        lineCount: 36,
        direction: "horizontal",
        stroke: "#3a4050",
        strokeWidth: 3,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "angry",
        text: "야. 너 어제 뭐라고 했냐?",
        x: ox + PAD + 20,
        y: oy + 24,
        width: 300,
        height: 110,
        fill: "#ffe9e3",
        textFill: "#7a1f1f",
        rotation: -2,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "scared",
        text: "…나한테 하는 말이야?",
        x: ox + PAD + 340,
        y: oy + 300,
        width: 280,
        height: 110,
        fill: "#eef2f7",
        textFill: "#2e3547",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "저벅…",
        x: ox + PAD + 70,
        y: oy + 330,
        width: 180,
        fontSize: 44,
        fill: "#5a6072",
        rotation: 4,
        font: "Gaegu",
        stroke: "#ffffff",
        strokeWidth: 3,
        align: "center",
      },
    ],
  },
  {
    id: "school-rooftop",
    label: "옥상 고백",
    category: "school",
    description: "하늘색 옥상 컷 + 외침 고백 + 바람 효과음",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        bgColor: "#e9f4fd",
        stroke: "#a9cde8",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "방과 후, 아무도 없는 옥상.",
        x: ox + PAD + 24,
        y: oy + 24,
        width: 300,
        height: 84,
        fill: "#ffffff",
        textFill: "#3a5570",
        rotation: 0,
        align: "left",
      },
      {
        type: "bubble",
        variant: "shout",
        text: "1학년 때부터 쭉 좋아했어!",
        x: ox + PAD + 120,
        y: oy + 150,
        width: 380,
        height: 150,
        fill: "#f4fbff",
        textFill: "#1c2b38",
        rotation: -3,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "bubble",
        variant: "heart",
        text: "어…?!",
        x: ox + PAD + 430,
        y: oy + 350,
        width: 180,
        height: 96,
        fill: "#ffe9dc",
        textFill: "#a8503a",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "휘이잉",
        x: ox + PAD + 40,
        y: oy + 380,
        width: 220,
        fontSize: 44,
        fill: "#7ba7c9",
        rotation: -8,
        font: "Gaegu",
        stroke: "#ffffff",
        strokeWidth: 4,
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 로맨스 ─────────────────────────────
  {
    id: "romance-cafe",
    label: "카페 데이트",
    category: "romance",
    description: "따뜻한 카페 컷 + 주고받는 대사 + 하트 말풍선",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 460,
        bgColor: "#fbf3e7",
        stroke: "#dcc39f",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "주말 오후, 골목 안 작은 카페.",
        x: ox + PAD + 24,
        y: oy + 22,
        width: 330,
        height: 80,
        fill: "#fffdf6",
        textFill: "#6a5638",
        rotation: 0,
        font: "Nanum Pen Script",
        align: "left",
      },
      {
        type: "bubble",
        variant: "speech",
        text: "여기 치즈케이크가 그렇게 맛있대.",
        x: ox + PAD + 30,
        y: oy + 130,
        width: 300,
        height: 110,
        fill: "#ffffff",
        textFill: "#3a2f24",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "heart",
        text: "너랑 같이 오니까 더 맛있네.",
        x: ox + PAD + 330,
        y: oy + 300,
        width: 290,
        height: 110,
        fill: "#f7dfe3",
        textFill: "#8a3f52",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "달그락",
        x: ox + PAD + 80,
        y: oy + 330,
        width: 180,
        fontSize: 36,
        fill: "#c0a67e",
        rotation: 6,
        font: "Gaegu",
        align: "center",
      },
    ],
  },
  {
    id: "romance-rain",
    label: "빗속 재회",
    category: "romance",
    description: "세로 빗줄기 + 나레이션 + 조용한 한마디",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        bgColor: "#e4e9f2",
        stroke: "#8fa3c2",
        strokeWidth: 3,
      },
      {
        type: "speedLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        lineCount: 56,
        direction: "vertical",
        stroke: "#8fa3c2",
        strokeWidth: 2,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "box",
        text: "그 사람을 다시 만난 건, 3년 만이었다.",
        x: ox + PAD + 30,
        y: oy + 28,
        width: 400,
        height: 88,
        fill: "#f4f7fd",
        textFill: "#3d4a63",
        rotation: 0,
        align: "left",
      },
      {
        type: "bubble",
        variant: "speech",
        text: "…우산, 같이 쓸래?",
        x: ox + PAD + 300,
        y: oy + 330,
        width: 300,
        height: 110,
        fill: "#ffffff",
        textFill: "#2c3242",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "쏴아아…",
        x: ox + PAD + 50,
        y: oy + 380,
        width: 220,
        fontSize: 48,
        fill: "#6d84ab",
        rotation: 0,
        font: "Gaegu",
        stroke: "#ffffff",
        strokeWidth: 3,
        align: "center",
      },
    ],
  },
  {
    id: "romance-fireworks",
    label: "불꽃놀이",
    category: "romance",
    description: "밤하늘 컷 + 불꽃 집중선 + 설레는 고백",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 520,
        bgColor: "#1d2240",
        stroke: "#3c4676",
        strokeWidth: 3,
      },
      {
        type: "focusLines",
        x: ox + PAD + 300,
        y: oy + 30,
        width: 330,
        height: 260,
        lineCount: 36,
        innerRadius: 30,
        outerRadius: 160,
        stroke: "#ffd76a",
        strokeWidth: 3,
        noise: 0.5,
        rotation: 0,
      },
      {
        type: "text",
        text: "펑—!",
        x: ox + PAD + 340,
        y: oy + 100,
        width: 240,
        fontSize: 72,
        fill: "#ffd76a",
        rotation: -8,
        font: "Black Han Sans",
        stroke: "#1d2240",
        strokeWidth: 6,
        align: "center",
      },
      {
        type: "bubble",
        variant: "heart",
        text: "예쁘다… 불꽃 말고, 너.",
        x: ox + PAD + 40,
        y: oy + 340,
        width: 320,
        height: 120,
        fill: "#2c3358",
        textFill: "#ffd9e4",
        rotation: 0,
        tail: "left",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "와아아…",
        x: ox + PAD + 420,
        y: oy + 430,
        width: 200,
        fontSize: 34,
        fill: "#8d96c4",
        rotation: 0,
        font: "Gaegu",
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 액션 ─────────────────────────────
  {
    id: "action-chase",
    label: "추격전",
    category: "action",
    description: "가로 속도선 + 쫓고 쫓기는 대사 + 질주 효과음",
    build: (ox, oy) => [
      {
        type: "speedLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 440,
        lineCount: 52,
        direction: "horizontal",
        stroke: "#15100c",
        strokeWidth: 5,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "shout",
        text: "거기 서! 도망칠 셈이냐!",
        x: ox + PAD + 20,
        y: oy + 40,
        width: 320,
        height: 130,
        fill: "#eef2f6",
        textFill: "#161b22",
        rotation: -5,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "bubble",
        variant: "scared",
        text: "잡히면 끝장이야…!",
        x: ox + PAD + 350,
        y: oy + 230,
        width: 280,
        height: 120,
        fill: "#e7ebf2",
        textFill: "#20242e",
        rotation: 3,
        align: "center",
      },
      {
        type: "text",
        text: "타다다닷",
        x: ox + PAD + 120,
        y: oy + 330,
        width: 320,
        fontSize: 80,
        fill: "#ffffff",
        rotation: -8,
        font: "Black Han Sans",
        stroke: "#161616",
        strokeWidth: 8,
        align: "center",
      },
    ],
  },
  {
    id: "action-standoff",
    label: "대치 클라이맥스",
    category: "action",
    description: "흑백 세로 2분할 + 낮은 목소리 대치",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: 320,
        height: 400,
        bgColor: "#ffffff",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "frame",
        x: ox + PAD + 340,
        y: oy,
        width: 320,
        height: 400,
        bgColor: "#161616",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "whisper",
        text: "…여기서 끝내자.",
        x: ox + PAD + 30,
        y: oy + 40,
        width: 260,
        height: 100,
        fill: "#f4f4f4",
        textFill: "#2a2a2a",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "angry",
        text: "바라던 바다.",
        x: ox + PAD + 370,
        y: oy + 260,
        width: 260,
        height: 100,
        fill: "#2a2a2a",
        textFill: "#ff6a5a",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "고오오오…",
        x: ox + PAD + 170,
        y: oy + 430,
        width: 320,
        fontSize: 52,
        fill: "#161616",
        rotation: 0,
        font: "Black Han Sans",
        stroke: "#ffffff",
        strokeWidth: 4,
        align: "center",
      },
    ],
  },
  {
    id: "action-awakening",
    label: "패배 후 각성",
    category: "action",
    description: "어두운 컷 + 집중선 + 다시 일어서는 외침",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 540,
        bgColor: "#14121c",
        stroke: "#2e2a40",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "무릎이 꺾였다. 하지만 —",
        x: ox + PAD + 26,
        y: oy + 26,
        width: 340,
        height: 84,
        fill: "#0e0c14",
        textFill: "#b9b3d9",
        rotation: 0,
        align: "left",
      },
      {
        type: "focusLines",
        x: ox + PAD + 60,
        y: oy + 120,
        width: 540,
        height: 360,
        lineCount: 64,
        innerRadius: 90,
        outerRadius: 300,
        stroke: "#4a3f73",
        strokeWidth: 4,
        noise: 0.3,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "shout",
        text: "아직… 끝나지 않았어!!",
        x: ox + PAD + 150,
        y: oy + 200,
        width: 360,
        height: 150,
        fill: "#f5f1ff",
        textFill: "#1c1330",
        rotation: -3,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "text",
        text: "번쩍",
        x: ox + PAD + 220,
        y: oy + 420,
        width: 220,
        fontSize: 76,
        fill: "#ffd76a",
        rotation: -6,
        font: "Black Han Sans",
        stroke: "#14121c",
        strokeWidth: 7,
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 판타지 ─────────────────────────────
  {
    id: "fantasy-throne",
    label: "왕좌 알현",
    category: "fantasy",
    description: "장엄한 알현실 컷 + 왕의 하문 + 긴장한 독백",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 520,
        bgColor: "#231a35",
        stroke: "#4a3a68",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "왕국의 심장 — 대알현실.",
        x: ox + PAD + 24,
        y: oy + 24,
        width: 320,
        height: 80,
        fill: "#f3ead2",
        textFill: "#4a3a22",
        rotation: 0,
        align: "left",
      },
      {
        type: "bubble",
        variant: "speech",
        text: "그대가… 예언에 나온 아이인가.",
        x: ox + PAD + 160,
        y: oy + 150,
        width: 360,
        height: 130,
        fill: "#f7f1e1",
        textFill: "#3a2f1c",
        rotation: 0,
        tail: "none",
        align: "center",
      },
      {
        type: "bubble",
        variant: "whisper",
        text: "(마른침이 넘어갔다.)",
        x: ox + PAD + 50,
        y: oy + 350,
        width: 280,
        height: 96,
        fill: "#2c2344",
        textFill: "#b9aede",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "text",
        text: "두웅…",
        x: ox + PAD + 420,
        y: oy + 400,
        width: 200,
        fontSize: 48,
        fill: "#c9a856",
        rotation: 0,
        font: "Black Han Sans",
        stroke: "#231a35",
        strokeWidth: 5,
        align: "center",
      },
    ],
  },
  {
    id: "fantasy-summon",
    label: "마법진 소환",
    category: "fantasy",
    description: "보라 집중선 마법진 + 상태창 + 소환 외침",
    build: (ox, oy) => [
      {
        type: "focusLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        lineCount: 72,
        innerRadius: 100,
        outerRadius: 330,
        stroke: "#5b2fb0",
        strokeWidth: 4,
        noise: 0.2,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "system",
        text: "[ 소환 마법진 전개 — 동기화 87% ]",
        x: ox + PAD + 140,
        y: oy + 30,
        width: 380,
        height: 92,
        fill: "#101322",
        textFill: "#7de3ff",
        rotation: 0,
        align: "center",
      },
      {
        type: "bubble",
        variant: "shout",
        text: "나와라, 계약의 짐승이여!",
        x: ox + PAD + 150,
        y: oy + 170,
        width: 360,
        height: 140,
        fill: "#ffffff",
        textFill: "#2a1650",
        rotation: -2,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "text",
        text: "우우웅—",
        x: ox + PAD + 180,
        y: oy + 360,
        width: 300,
        fontSize: 64,
        fill: "#8a5cf5",
        rotation: 0,
        font: "Black Han Sans",
        stroke: "#ffffff",
        strokeWidth: 5,
        align: "center",
      },
    ],
  },
  {
    id: "fantasy-dungeon",
    label: "던전 입구",
    category: "fantasy",
    description: "어둑한 던전 컷 + 정보 상태창 + 파티 대사",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 500,
        bgColor: "#151a15",
        stroke: "#33402e",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "system",
        text: "[ B급 던전 · 침묵의 아가리 — 권장 인원 4 ]",
        x: ox + PAD + 30,
        y: oy + 26,
        width: 480,
        height: 90,
        fill: "#0c1410",
        textFill: "#8fe08a",
        rotation: 0,
        align: "left",
      },
      {
        type: "bubble",
        variant: "scared",
        text: "…진짜 들어가야 해?",
        x: ox + PAD + 40,
        y: oy + 170,
        width: 280,
        height: 110,
        fill: "#e6efe4",
        textFill: "#2a352b",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "bubble",
        variant: "speech",
        text: "겁먹었냐? 내가 앞장선다.",
        x: ox + PAD + 330,
        y: oy + 320,
        width: 300,
        height: 110,
        fill: "#ffffff",
        textFill: "#22301f",
        rotation: 0,
        tail: "right",
        tailDirection: "top",
      },
      {
        type: "text",
        text: "스으으…",
        x: ox + PAD + 80,
        y: oy + 380,
        width: 200,
        fontSize: 42,
        fill: "#7fb8ad",
        rotation: -4,
        font: "Gaegu",
        stroke: "#151a15",
        strokeWidth: 3,
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 일상 ─────────────────────────────
  {
    id: "daily-morning-rush",
    label: "아침 등교",
    category: "daily",
    description: "시계 나레이션 + 지각 외침 + 질주 속도선",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 440,
        bgColor: "#fdfbf4",
        stroke: "#1c1c1c",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "AM 8:47",
        x: ox + PAD + 22,
        y: oy + 22,
        width: 150,
        height: 64,
        fill: "#161616",
        textFill: "#f4f4f4",
        rotation: 0,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "speedLines",
        x: ox + PAD + 60,
        y: oy + 220,
        width: 540,
        height: 160,
        lineCount: 30,
        direction: "horizontal",
        stroke: "#b9b3a4",
        strokeWidth: 3,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "shout",
        text: "지각이다 지각—!!",
        x: ox + PAD + 200,
        y: oy + 80,
        width: 320,
        height: 130,
        fill: "#fff8ec",
        textFill: "#3a2410",
        rotation: -4,
        fontStyle: "bold",
        align: "center",
      },
      {
        type: "text",
        text: "헐레벌떡",
        x: ox + PAD + 120,
        y: oy + 330,
        width: 260,
        fontSize: 52,
        fill: "#d97a2b",
        rotation: 6,
        font: "Gaegu",
        stroke: "#ffffff",
        strokeWidth: 4,
        align: "center",
      },
    ],
  },
  {
    id: "daily-overtime",
    label: "야근 사무실",
    category: "daily",
    description: "밤 사무실 컷 + 메신저 말풍선 + 속마음",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 460,
        bgColor: "#20242f",
        stroke: "#3a4152",
        strokeWidth: 3,
      },
      {
        type: "bubble",
        variant: "box",
        text: "PM 11:20 — 아직 사무실.",
        x: ox + PAD + 24,
        y: oy + 24,
        width: 300,
        height: 76,
        fill: "#161a24",
        textFill: "#9aa5bd",
        rotation: 0,
        align: "left",
      },
      {
        type: "bubble",
        variant: "phone",
        text: "부장: 이거 내일까지 되지? ^^",
        x: ox + PAD + 330,
        y: oy + 130,
        width: 300,
        height: 110,
        fill: "#0e1118",
        textFill: "#cfe0ff",
        rotation: 0,
        tail: "none",
        align: "left",
      },
      {
        type: "bubble",
        variant: "thought",
        text: "……집에 가고 싶다.",
        x: ox + PAD + 50,
        y: oy + 300,
        width: 300,
        height: 110,
        fill: "#2a3040",
        textFill: "#c3cade",
        rotation: 0,
        tail: "none",
      },
      {
        type: "text",
        text: "타닥타닥",
        x: ox + PAD + 400,
        y: oy + 370,
        width: 220,
        fontSize: 38,
        fill: "#7d879e",
        rotation: 0,
        font: "Gaegu",
        align: "center",
      },
    ],
  },
  // ───────────────────────────── 연출 ─────────────────────────────
  {
    id: "narrative-cliffhanger",
    label: "클리프행어 엔딩",
    category: "narrative",
    description: "어두운 프레임 + 불안한 속삭임 + 다음화 예고 배너",
    build: (ox, oy) => [
      {
        type: "frame",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 480,
        bgColor: "#100e16",
        stroke: "#2b2740",
        strokeWidth: 3,
      },
      {
        type: "focusLines",
        x: ox + PAD,
        y: oy,
        width: INNER_W,
        height: 480,
        lineCount: 24,
        innerRadius: 200,
        outerRadius: 460,
        stroke: "#221e38",
        strokeWidth: 2,
        noise: 0.6,
        rotation: 0,
      },
      {
        type: "bubble",
        variant: "whisper",
        text: "…설마, 이게 끝이 아니라고?",
        x: ox + PAD + 30,
        y: oy + 40,
        width: 340,
        height: 110,
        fill: "#1c1830",
        textFill: "#c9c2e6",
        rotation: 0,
        tail: "left",
        tailDirection: "bottom",
      },
      {
        type: "text",
        text: "삐걱…",
        x: ox + PAD + 420,
        y: oy + 200,
        width: 180,
        fontSize: 40,
        fill: "#4a4468",
        rotation: -4,
        font: "Gaegu",
        align: "center",
      },
      {
        type: "bubble",
        variant: "box",
        text: "다음 화에 계속…",
        x: ox + PAD + 370,
        y: oy + 380,
        width: 260,
        height: 70,
        fill: "#2a2440",
        textFill: "#e8c76a",
        rotation: 0,
        align: "right",
      },
    ],
  },
  ...STUDIO_AUTHORED_SCENE_TEMPLATES,
];

/** 카테고리로 템플릿 거르기(미지정이면 전체). */
export function listSceneTemplates(category?: string): SceneTemplate[] {
  if (!category) return SCENE_TEMPLATES;
  return SCENE_TEMPLATES.filter((t) => t.category === category);
}
