/**
 * CC0 Krita RGBA_brushes tip import v1 — real impasto/grain tip alpha maps.
 *
 * Upstream: `RGBA_brushes.bundle` by Ramon Miranda (2020-12), shipped with Krita. Provenance
 * chain: the bundle's meta.xml declares license "Same as default brushes in Krita" and the Krita 4
 * default resources bundle (`Krita_4_Default_Resources.bundle`) meta.xml declares license="CC-0",
 * so these tip images are CC0 by reference. We archive both meta.xml statements here verbatim.
 *
 * Reduction formula (documented honesty — these are ALPHA REDUCTIONS of RGBA tips, not the full
 * RGBA/lightness impasto payloads):
 * - RGBA sources (`Craig_02.png`, `Mountain_Brush_01.png`): coverage = alpha01 × luma01
 *   (Rec. 709 luma). RGB carries bristle-height detail in the RGBA brush model; multiplying it
 *   into coverage keeps the groove texture in a single channel.
 * - Grayscale source (`DA_Triangle grain.png`, white background): coverage = 1 − luma01.
 * - Non-square sources are centre-padded to square (aspect preserved), box-downsampled to 64×64
 *   (the in-document custom tip cap, studio-brush-tip-stamp), then max-normalized to the 0..255
 *   byte range.
 *
 * The payloads are plain `StudioBrushTipSettings`-shaped custom alpha maps, so the dynamic-dabs
 * tip pipeline (`buildStudioBrushTipAlphaMap` / `planStudioBrushTipStamp`) consumes them without
 * any new code path. Static data only — determinism is trivial.
 */

import { STUDIO_BRUSH_CUSTOM_TIP_ALPHA_MAP_MAX_SIZE } from "./brush/studio-brush-tip-stamp";

import type { StudioBrushTipSettings } from "./brush/studio-brush-tip-stamp";

export const STUDIO_CC0_KRITA_RGBA_TIP_IMPORT_VERSION_V1 = 1 as const;

export const STUDIO_CC0_KRITA_RGBA_TIP_PROVENANCE = Object.freeze({
  bundle: "RGBA_brushes.bundle (Krita resource bundle)",
  author: "Ramon Miranda",
  bundleLicenseStatement:
    "meta.xml meta:meta-userdefined license = \"Same as default brushes in Krita\" (2020-12-15)",
  kritaDefaultLicenseStatement:
    "Krita_4_Default_Resources.bundle meta.xml meta:meta-userdefined license = \"CC-0\"",
  license: "CC0-1.0 (by reference through the Krita 4 default resources bundle)",
} as const);

/** All embedded tips are 64×64 — exactly the in-document custom alpha-map boundary. */
export const STUDIO_CC0_KRITA_RGBA_TIP_ALPHA_MAP_SIZE = 64;

export interface StudioCc0KritaRgbaTipImport {
  readonly tipId: string;
  readonly nameKo: string;
  /** Exact file inside RGBA_brushes.bundle (`brushes/` directory). */
  readonly upstreamFile: string;
  /** Documented single-channel reduction applied to the upstream image. */
  readonly reduction: "alpha-times-luma" | "inverted-luma";
  /** Base64 of 64×64 alpha bytes (standard alphabet, padded) — tip pipeline contract. */
  readonly alphaMapBase64: string;
  readonly alphaMapSize: number;
}

function tip(
  tipId: string,
  nameKo: string,
  upstreamFile: string,
  reduction: StudioCc0KritaRgbaTipImport["reduction"],
  alphaMapBase64: string,
): StudioCc0KritaRgbaTipImport {
  return Object.freeze({
    tipId,
    nameKo,
    upstreamFile,
    reduction,
    alphaMapBase64,
    alphaMapSize: STUDIO_CC0_KRITA_RGBA_TIP_ALPHA_MAP_SIZE,
  });
}

// 64×64 alpha bytes, standard base64. Generated once from the upstream PNGs with the
// documented reduction; regenerating with the same inputs reproduces these bytes exactly.
const CRAIG_IMPASTO_ALPHA_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB" +
  "BAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAARQaCwAAAAAAAAAAAAYcFAQAAAAAAAYoPGpXDwAAAAEB" +
  "AAAAAAAAAAACAQAAAAAAAAAAAAE1ZiwCAQwVGgUABkhgaEMDAAAAAAAAByJIWXiAEQAAAAZwhm6UoWcGAAQjIicXBwIBAAAT" +
  "QUUNAQAAAAAAAAAToqF0MUA7cVw9IEq6ya9lBAwQIj0bFVHIp9/Gkk0FAAQ6x5qajLlkKicjSHVkJC4lGAUGPm58SBwCAAAA" +
  "AAAAN87Crqe0knt4o6+NxvLrn15JYYG+k6OyxtDh3cGZSyZ8bdSev3uPjYCVfb/RxXdcSjwjFEyUoWo5HBEDAAAAACCdkHeo" +
  "1NWwrcOsPrrr3LJMfZerkn2AtN7j8e3b2cvN1a/AlbiTpMvIwrvX4reqg4pOMhUviZ+ZcUxwQAYAAAAhrFxVesC2mqq3iVW6" +
  "5cWympRKjJ5YlKej1NbizN3s2bLNh8C5k8758tK8xcCiqKyIeUg3Q4qjjXllXHofAAABQLtnZGFnhYuXoodIi8zDprDBd4+F" +
  "l8ijsrKtsKe/1s3BkJjgpqPk+f+/j4iNaJyelKpzZEZjlZV1cVRpHgAABnXBl2xdSVpVkqmkf4jHyoKml6dvRrehvs+kl6uh" +
  "kYyMhmXOjq+Xv+jVhFVOW2yda6y4f3lrT2GMlJ56OAcAAByvwLKNb0xNUI6llEdPhrBJdYm/iD1VSniCR4exqKaNgmqNcZmQ" +
  "eX6LfXFfPFOiu4NcZYGQaDlWg4KhkT8DAAAnrMTCrHBaYV2gsYc9UUuUQGyVt8FlQSpWpGepnKCkjXJ/mrGUi3luZGdqY1Vh" +
  "yNTFYl1wdGlBOXWWp5dRBAADKIrAwr6toJeSqqSkLB1FhUB2d6GrY0UkS5dAVmlehI2AZoKvm3J2alxXVFhWYrS20I1sgJRn" +
  "T4Snp6ScJAEACDmpfb/Gx7GSb3KMkEEiU4k9c3CTakhLLVuXMTIlN4iBl7GWhIKAdl1UWl5hUWNvq52MaXKUeER7nKd/VggA" +
  "ABJNo4CTnMW+oF0tb3M8TYZvToxlVT8pRV5TiEMzEE+DZa/Q1LuIhYtqXl5iVk5hXWxiXXBkaZBML3OBUg8AAAAmQ3xPcVeK" +
  "kpRyN1xrOElvX2KdmmhPM1NNNLM+Ph1BeXu54sG0n4VygHdvZmFdVkdebmlselleTSorIiQgBQAAKCyGMHxSiY6QZ0lPblVz" +
  "Z19zmZZxXS5MOyuTIzIfYnJ8c6eWm4VsbIp6Z2BKQkRKQGBza2ptVUNKKR8nHAwBAAk4hz1hU4aNgk5KP5PEwItjTVhqXGY3" +
  "YTQubD4cIz5pYDg4VUFvXk87TWBYSC8pLkJVYWxjTmNVZTEnNB4SBAADM2BmS2CAjVNEMFmx0bd+iTA2RlNgPVQuKU9BIzIV" +
  "TU8pOUhQVl5rZGN1VjgmNU1OYWpfQTprRmw+MCkeFhAAAQ1BhkNsYm1CNEVifpGLVYk/JykyPSdgKDlZOCNqKB9LLTtOXVRP" +
  "aFF1f2NIJC5QYFxkQSw6XGBbTjgsHSEAAAAAMY9Wa2djcEM+Q2FpUTOSLyskOFg7aCk3ZzQubF0kJjQdTGBZQFxde3+FTSNN" +
  "U2BOeTw0OUxRUksoJSkTAAAAAQ10akxbcmlrSklWJzUtdRkwIz9TMk00QGAkMlt8LkMZSEBeTl84aGNhdntcjWF/Z2k/K2Y6" +
  "JVB+TkY0AgAAAAAtZntXY3hdZ2VKYCEeck0SMSdEVTxQPUJlLkFQiyVYMiQ+MyhDZG1bRniGMyoYXn1WLRwrPkd3Y0dvNQAA" +
  "AAAAEUGJVUZPSF5JT4BAGlsiLTwzP0NYamNbc2xdTFQ/XW1VPjkVFVw0Myxghz0GKU1fLRoYEyczLSEbFQUAAAAAAAUjllRE" +
  "OENNUldyPCMqR15FS1lobXl3cXZpaUsrU5KYbT87QSE4PTMeSHZLEy5DZ081LCYXEgwIDAIAAAAAAAAAHpxNPS89R15gZ053" +
  "X1ReZ153d3x+hnd7bXl4MaSMf3NNX1tOQ0kzIDRUOw0oWXVoPDkuEgQBAAAAAAAAAAAAABJdUk84P05naW9ucWtLRmJocXyJ" +
  "iI6efnpmqSaIgMu2c21pdWxkjnhVVWYGETBXbEM3LgcAAAAAAAAAAAAAAAABfkVPS0xXbJlyWlpeUk9oYGxqc3FzbH15WktD" +
  "Xq/txHtmYW5yeWFHaWbJFgUgSUlDNSEBAAAAAAAAAAAAAAAAABdfe5N6mVmGSTdDZm5eUipfZWJnXlhjZUtaYXKYy8htUGh1" +
  "dWcTBQwWQh0sUFZZOQ8GAAAAAAAAAAAAAAAAAAAAGHxfEgMHBwcII0dWTTkSRHNucmZZWTgzY2NaZYZuZmBudXVdGAYIDg4V" +
  "Jj1iMBIAAAAAAAAAAAAAAAAAAAAAAAAdAgAAAAAAABdFSUM6FiN1c2VBHBcEBxw7PUZbV0NZa29oRyQEAgUHDBESJggAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiKytBLh0UVG1kJAEAAAATK01IV1RaUGFlTCUVAgAAAAECAQEAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAADTY2RksuBxdQIAYAAAALN19eSlldRDU9PzggCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAJDSxQNAMBCwQAAAAACjJmY1tqVjYZNTAvDgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAZMDcLAAAAAAAAAAYhR0E6Yj4yGiIXDAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBYuBAAA" +
  "AAAAAAAABQwJDDYvIBwFAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAA" +
  "AAMXKhgPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQ4JAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

const TRIANGLE_GRAIN_ALPHA_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCQgAAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCUcobCASBQYFAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAADkJZa7eHOBYbIREWCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAB9SaJnP2I5tq3ZmOBwSDgMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAQ1X5nGxffa1NbZwGxMQl4uDwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACO3Xo3O76" +
  "8+vI+N6Ylq24fVJHDAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxyy9P8/f35+sSaxMDG" +
  "96rQmjMTAQAMBAQAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZNHm9PrY6u/l5OH83srj5LFZHAwS" +
  "S15PHwQACw4AAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVGx3+jl1erk6/Wcw7zz4dbkfilNMLSTeGYuETUi" +
  "JBAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbquz02e3j7/n+7efS9MjZ1NaJra/WrbOXiWWGanglAQQGAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABG6Pw6Onl1P//+efl3NKt8+bCTWqV5+6+1ubVV8i/TxUYKhYFAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAFFir0L3j4cf7///NzPe93urfV8Lp0LPNiuf5/Z6w0YRwSk1AKwUKAgAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAQVZzNrG7NCu4fn6/fn736+xwrXRzO7a1bvCnsy1xueLTVuTyJgxIhwBAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AhEUcsvn6u/1sq/s+v/87sbfzvu4jLze7/bi+7WCXsf5alSLweu3P0c5OicRBQAAAAAAAAAAAAAAAAAAAAAAAA8nKWyh9e/3" +
  "7NfS3//9+u/458nu46W06N280vvk1OrH7cSNZmTJv3Cge41FIhQDAAAAAAAAAAAAAAAAAAAAAAAJK0lxx+j8/P/948j7//3i" +
  "+dDC+/W1vPDhre3Y4tjp1ufUkpamu8VphbmUZVUoKR8JAAAAAAAAAAAAAAAAAAAAAAx6neTi+P78/b3i//z77+Hv9/TyrtTw" +
  "0dL79um1huy6WX+uhzA+XITYnHJdZZd3QR0OBgAAAAAAAAAAAAAAAApGrcrb5vPp3v/79vr+9+Lm4f788efY1tXT/f7Z3GTX" +
  "iLq2tblYNbpTk3BZj7aqurKMW0ciBgAAAAAAAAAAAAARcdjk8/P10cre1/L07Pfu6vX48tLH0q3m7fTu9/HtzoySeYhQeVvG" +
  "PKWYcq65r8jRyZWGaDUNAAAAAAAAAAAAHnbb1vDl3eHJxNTx++XF0Jy437iodMff8u3v0+fj7+d7e2Jic4iQRo7ZY5DAt7Lb" +
  "wtTj1alLRAIAAAAAAAAAACSN08Xo5c23nPrVwsjBga/YxsDD17f7+f/96vm/eeTdmyago2Nz0aXS5eq2o5fU4MTm9vK7hGEc" +
  "AwAAAAAAAAAqhsjF2urCqJz58KmBkXu6zqu/3+Wf//n5/fP9tZbGZ1Nd4nqkjLjM18rZyOXo8+z42fL1x72kfVEHAAAAAAAA" +
  "E2OmttvuwL+r7LDNfpx/yr6BsPLm//718fL59PH0x19PTcDH47Snuo6MprzfzcCw6+/w9czNsGCUPxwBAAAAAAQ7o6LSr5Kl" +
  "rpm/0NmUn+O4YKnmzubP77/j7uDr/P6xOVvhwtG9s9LWy9bkZsr2w9HewfC5y9TErndQHQUAAAAAKbWx1c2keMTOuazJr8i+" +
  "55u2ueSrhufm69Dj8Pf9nYt8n1Gh0eX3+uK2nDFv2+Ty3tH6z9nOp5TeqkwRAAAAAjvB0sWetayzqpC4vOnj2ufIvVDc393f" +
  "3Nj8+9a3qujy1d+Xj6Lsu9/AhrA5hcr68sTt68Kx3did4O2dLxYCAAUnhs7Ox8KqlrKF2rfp09zh2LRTm/fk7dHc5d7UkY3Y" +
  "9u/TzMjL0NHs5LaWpq7J9Pv06vft5/DX8vLlzLZ/GQEEJnS3y8qvrNu4mr2Uvdu/4b7PaIKs2vzaxLzKiqeC1e7WtdbD7tHv" +
  "+73Aytbc8+T+/Ov15+3n4vjs8tfhtUYAABqRyODS4t/m4/HUjtzk4urasXzE+//8+Pvp6Nrru6G7qbuvk9vW09Ottcb26uXV" +
  "3N7E2vD/9dLb9vjWz4k/CAAejrjk7Pfz9dO7tLjRvMvP25ju/fv++NP78+DJ6IamvtnlisPCx8zrxarG9eTg58bI7fXj6crj" +
  "5+vz7N9qDAsADXjA4eT2+vXn3Yvl7rKs4/n66/XVz+Xi/77SaePG2ezTwMzd5uzT88y+rr+z4fbj9Pb48tGr6eLz7djJZTAF" +
  "AA5uv7nJ++j129mN4fXo6uzz9OjAldqkkcrJ583j9+LUybip59zO2sq/zMHa2Mzd7t375fPapfH4+uuxnDEuAgAORIO7zvLY" +
  "39Tj0+Pq7+3r9fz58KbogXWo4aTw6/f4srTSj+njzNOFqKv26fDMztnx/vr45sns7/Pcomw3DgAAAy1q2PnJt6rI1eDk7/n0" +
  "+u33zNvd6byM37/Tx7b3/N/kvqzHy9DTn7iK2s7h0NST2vfy/frv6vLat5NbGwAAAAAajcrtmqmY1u7o4sfy+/Xbwq678/z3" +
  "v/Tx+OrW5ubw1LGmm9LmirjCtN+6yu7Sp+D08vbz89vfw5RLJgEAAAAADFnH5tvAhMG69NmR7fz6663Bz/b98Ovr7P7q287H" +
  "9OfQwJmdrrie1OX6zNjv/Nz12dDr6eTPm6BqJgcAAAAAABYmyef28bPEyve84vvO+t+N2vn4+vX2/c3t5NnM2/X1tMinpLDk" +
  "4+fm7fLp9vjo9enozZx7c0UsKAMAAAAAAAAVN7HY/Pvt9cnR3Nf00L2s2+/6/v7r+PmpyPvSu9Hb6OLW393R7vP29e/t1Oz7" +
  "+vbs2oxIIRwOAwIAAAAAAAAAE06kv+n/6ce45uDo8ZmWzNHz28328u/wxcfdu6i/wfHz69/b2Orw8vHt5uP32uTgv514JwEA" +
  "AAAAAAAAAAAAAAFDudH2/ujQ5ff99Pflws7S7N7y3+f95fHuydKdzNjb1tvi3/X1+e/u49nv5sHIqmhAGQAAAAAAAAAAAAAA" +
  "AAABPsvV7ef2+/z7//rpzKCi1PP7++DO5LLp3MLYyNXU2uHS3u3y5/jy7Oro5tC2pHQzCwAAAAAAAAAAAAAAAAAABlPd9PDk" +
  "3fD30+7jyrL26fT3+vny28rCs6PE1NjX2/X59vPz8eb69/DevKB6ZDUJAQAAAAAAAAAAAAAAAAAAAAtd6fL2/fH2+eTk9uX0" +
  "6trs/Pz49dPG4cLE4NPv2Mjb8fTy3tzj09/jyXNBMxYBAAAAAAAAAAAAAAAAAAAAAAAZgNz0/vj8+vLZ4ebp8OfZ2+v++v3m" +
  "zdLL2eTn+NKuwdrEsoJwlKCylFUkEQwBAAAAAAAAAAAAAAAAAAAAAAAAHZHc6/vw7ff16eTb4+7s2tHH9fv69tfP2MfU5+bD" +
  "nJaLbEQqJ1FWbT4nCwAAAAAAAAAAAAAAAAAAAAAAAAAAABKe09vi4un29/nx59Te6eHlwuP1+ffw6tzAnJZiHxk8JgoAARsk" +
  "JBsSCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAanMGn0Onq9fj68ezq6fDn4NnW9fbw6uPMpmpGEQAAAwYAAAAKIhYCAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAHYS6vuHh7vjy8u/i5uHVvZKfysjRzLKtgE1VIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAABltx9jf5u30597i0LyMk4BHZZp4d21RcVlPNwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAARWK/K0cLT27musY6FVTk2ID5+VzsjIDYbHwoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByqOnqiQ" +
  "amNQU1JaWisVDgYVPTgOBAAGAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAURa4uMcUgbDAYKGgwD" +
  "AQEAAQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBRcmOCoDAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEgoBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";

const MOUNTAIN_ROCK_ALPHA_BASE64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIFAsAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJNmBwfnZjWEspCQEAAAAAAAACDj5phaG0xdDBdRgAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAIRYas1t7LxcbHyMnP0b+ploeMmZ+pusvZ0dHX3OXu8//2jxgAAAAAAAAAAAAAAAAAAAAAAAACDhkn" +
  "MUdYcYijxN7SysnIx8jKysvLzM7NysrMzs/OztDT1tbW19jb3t/j7e7qbwgAAAAAAAAAAAAAAAAAAAAzsMTd6+nl4NXOysnJ" +
  "ysrKyMnJy8vMzc3Oz83P0NHU2d3e3t7e3t7d29vY2dze4fvQTwMAAAAAAAAAAAAAAAAHh5OTlaG1u7y6w8LBv8bLy83My8fH" +
  "yMrLzM7S1NPT09jZ2djY2Nja3N3f3Njb3N7d3+24RQQAAAAAAAAAAAAAPpCVk5Wdo6musby9vb3Ayc3NzMvLy8vLzM7Oz8/O" +
  "0NHR09PS09PS1Nbd4uLh4eLj49/d4Oe4TQMAAAAAAAAAAFeEkpmamqClp666vb29v8jNy8rLzMvMy8vMzM7Ozs/Q0dHS0tHU" +
  "2N3d2tfRz83S3eHf3N3g6PKkGAAAAAAAAAOEmbmzraqZkpKXrbSztLbDycfJysrLzMrLy8vNzczNzszNxcjPz8bBwcHEyNHa" +
  "39/f3t3d3d3f5slTAgAAAAAAdWGmu7y9v7y0qK6wqKmpqrC3u8DAwcDAwL/Av8LBwcO+ubO1tLK8xcvQ2N3f3drW2Nrd3uDh" +
  "4+Pi5YUCAAAAADpQla2/vsC/xczO0c/Fw8LBxcjIx8bHxsnO0NHS1NPTzsrLz9PW293d3NvX1dfc3t/h4+Pj4uDbzr+oGgAA" +
  "AAAjV7Oiw8jMzc7R0dTW19PR0dLR0NDR09PS1NXV1tnb3dzc3t7d3dzZ2dbV1dPc39rT2+Lc19bOwquFWhkAAAAAL0+2x8XB" +
  "xMvQ09TW19nY1dHR0NHS0tPS1NbX2dre39/e3tza2dnZ2NbT0dDR08zCxs7JxcXFroxrWkkkAAAAADRDecLHw8PGyMvP1tnZ" +
  "2tvZ1dXW1tbW1dXX3d/f39/f39/g4ODf39zc29nZ1tLR09bNxL+riHBmXVNJLwAAAAAxPmGVrbO7vL7BxMzOs9ba29rW19fX" +
  "2Nrb3N3e3d3d3N7f39/e3+Df3t7d2NrZ29K+t6B6bGpnYlxVTj4IAAAALTtckI+gu7u9u7u9wIuu2drb2tjX2dvb29zc29vd" +
  "3t7d3drV3Nvc3dzb2NHR0cCoknlqaWloZV9bU0w9FwAAACI5SISPj5mtt7m6urSgf8PRy8fFw8HDvMjT1NLQzsrCvbeZsr6+" +
  "vr66uLi5sJV7bWxoaGloZ2ZhWFJKOiUCAAAWOjpLaXmLkJCRi3FYUEZwfoiMiYeGf3t8gYCDiJScnJZ7f4V8enZ0dXNxb25q" +
  "aWZoaWlpaWdmY1lPQi4RAAAACDg6OzdEWn2OhVI7OSgwRk9SUlFUVFNTUlJSUlJbZGdnampqaWtjWVBbZmVkYltZWVlfYmBh" +
  "X1xQPCEJAAAAAAAaPj07LjJIWzc4OTozKzE4PT89Ozs/PzxAQUNDQU5WWFpdWlhRRUE1PlJRUVA8NTMyOU9PT05MNQkAAAAA" +
  "AAAAAA4wPDgtLTMxOTk6OjIzODg4OTg4OTo5OTo7Pjo6OUJPUFFJPDk4ODhKTExMOyYmJiZHSUpFGgEAAAAAAAAAAAAAASM0" +
  "LSstMzg4Ojs5NDY2NjY2NjY2Njc4ODg4Njc2Pk1MRDg4ODg3OkdMS0YnJiYlQEo8DAAAAAAAAAAAAAAAAAACKDArLzQ5ODg4" +
  "ODg4NjY2NjY2NjY2NjY3NzY3NzY8S0c3Nzc4OTY8S0tJMSUkJDM0BAAAAAAAAAAAAAAAAAAAAAwxMC82ODg3Nzc3ODg2NjY2" +
  "NTY2NjY2NjY2NTY2NTtGNjY2Nzo2NUZMSz0kIyQfBQAAAAAAAAAAAAAAAAAAAAAAKDMzNzg3Njc1Nzg4ODY1NjU2NjY2NTY2" +
  "NjY2NjU2PzQ3Nzc6ODI+SUlHJiEfBQAAAAAAAAAAAAAAAAAAAAAAABc0PkJJPjc2ODg3Nzg2Nzc3NTY2NjU2NjY2NjY1NkY5" +
  "Nzc3OTsyOEhISC8dCAAAAAAAAAAAAAAAAAAAAAAAAAAGMEVRTEpJPzg4ODg4NjU5RkRCPTo3NjY2NjY2NTc6Pzc4ODg8ODdI" +
  "SEg6DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUzUVBMS0xHPzo4ODg1QEZFR0ZIRDc2NjY4ODg4ODs8ODk5Ozs6SEc/HgAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAABlJUkxLTk5OS0dEQkY6IxMNDxYaIi02Nzg4ODg4QTw6Ozo8KBYHAQAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAC0dST05NTEtKSTgWAQAAAAAAAAAABxUmNjo6OTlFKhgJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAART1BJRUhGNREAAAAAAAAAAAAAAAAAAAIOEw8KAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBQ" +
  "TkQrDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKiMHAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";


export const STUDIO_CC0_KRITA_RGBA_TIP_IMPORTS: readonly StudioCc0KritaRgbaTipImport[] =
  Object.freeze([
    tip(
      "craig-impasto",
      "Krita CC0 · 크레이그 임파스토 팁",
      "brushes/Craig_02.png",
      "alpha-times-luma",
      CRAIG_IMPASTO_ALPHA_BASE64,
    ),
    tip(
      "triangle-grain",
      "Krita CC0 · 삼각 그레인 팁",
      "brushes/DA_Triangle grain.png",
      "inverted-luma",
      TRIANGLE_GRAIN_ALPHA_BASE64,
    ),
    tip(
      "mountain-rock",
      "Krita CC0 · 마운틴 록 팁",
      "brushes/Mountain_Brush_01.png",
      "alpha-times-luma",
      MOUNTAIN_ROCK_ALPHA_BASE64,
    ),
  ]);

const TIP_BY_ID: ReadonlyMap<string, StudioCc0KritaRgbaTipImport> = new Map(
  STUDIO_CC0_KRITA_RGBA_TIP_IMPORTS.map((entry) => [entry.tipId, entry]),
);

export function listStudioCc0KritaRgbaTipImports(): readonly StudioCc0KritaRgbaTipImport[] {
  return STUDIO_CC0_KRITA_RGBA_TIP_IMPORTS;
}

export function resolveStudioCc0KritaRgbaTipImport(
  tipId: string | null | undefined,
): StudioCc0KritaRgbaTipImport | null {
  if (!tipId) return null;
  return TIP_BY_ID.get(tipId) ?? null;
}

/**
 * Ready-to-consume settings for the PNG-alpha tip pipeline. Shape "hard" only names the
 * procedural fallback slot — the custom alpha map overrides it whenever the payload validates,
 * and softness 0 keeps the imported texture unfiltered.
 */
export function resolveStudioCc0KritaRgbaTipSettings(
  tipId: string | null | undefined,
): StudioBrushTipSettings | null {
  const entry = resolveStudioCc0KritaRgbaTipImport(tipId);
  if (!entry) return null;
  if (entry.alphaMapSize > STUDIO_BRUSH_CUSTOM_TIP_ALPHA_MAP_MAX_SIZE) return null;
  return Object.freeze({
    shape: "hard",
    softness: 0,
    alphaMapBase64: entry.alphaMapBase64,
    alphaMapSize: entry.alphaMapSize,
  });
}
