/**
 * Local-document production insights for a single Studio episode.
 *
 * The module intentionally accepts a small structural projection instead of StudioPage state.
 * It never reads private audience analytics, network state, or remote telemetry. Callers decide
 * which document fields map to dialogue, narration, assets, review state, and known issues.
 */

export const STUDIO_PRODUCTION_INSIGHTS_LIMITS = {
  maxPages: 1_000,
  maxFrames: 20_000,
  maxTextSegments: 50_000,
  maxTextCodeUnitsPerSegment: 10_000,
  maxTextCodeUnitsTotal: 1_000_000,
  maxAssets: 50_000,
  maxIssues: 10_000,
  maxNumericMetricInput: 1_000_000_000,
} as const;

export const STUDIO_READING_TIME_MODEL = {
  visibleCharactersPerMinute: 300,
  secondsPerFrame: 2,
  formula:
    "ceil((visibleCharacterCount / 300) * 60 + frameCount * 2)",
} as const;

export type StudioProductionReviewStatus =
  | "draft"
  | "needs-review"
  | "changes-requested"
  | "approved";

export type StudioProductionIssueSeverity = "error" | "warning" | "info";

export interface StudioProductionTextValue {
  text?: string | null;
}

export type StudioProductionTextSource = string | StudioProductionTextValue;

export type StudioProductionTextCollection =
  | StudioProductionTextSource
  | readonly StudioProductionTextSource[]
  | null;

export interface StudioProductionAssetInput {
  /** Strictly `true` means the supplied asset entry was generated by AI. */
  aiGenerated?: boolean;
  /** Strictly `true` means the supplied asset entry was edited by AI. */
  aiEdited?: boolean;
}

export interface StudioProductionFrameInput {
  dialogue?: StudioProductionTextCollection;
  narration?: StudioProductionTextCollection;
  /** Each supplied entry is counted once. Do not repeat page-level entries here. */
  assets?: readonly StudioProductionAssetInput[];
}

export interface StudioProductionReviewInput {
  status?: StudioProductionReviewStatus | null;
  locked?: boolean;
}

export interface StudioProductionPageInput {
  frames?: readonly StudioProductionFrameInput[];
  /** Page-level or unframed speech text not already represented by a frame. */
  dialogue?: StudioProductionTextCollection;
  /** Page-level or unframed narration text not already represented by a frame. */
  narration?: StudioProductionTextCollection;
  /** Assets not already represented by one of this page's frames. */
  assets?: readonly StudioProductionAssetInput[];
  review?: StudioProductionReviewInput | null;
}

export interface StudioProductionIssueInput {
  severity?: StudioProductionIssueSeverity | null;
  /** Resolved issues remain in totals but are excluded from actionable counts. */
  resolved?: boolean;
  /** Explicit `false` suppresses an unresolved issue from actionable counts. */
  actionable?: boolean;
}

export interface StudioProductionInsightsInput {
  pages?: readonly StudioProductionPageInput[];
  issues?: readonly StudioProductionIssueInput[];
}

export interface StudioProductionTextMetrics {
  textCount: number;
  /** NFKC-normalized, non-whitespace Unicode code points. */
  characterCount: number;
}

export interface StudioReadingTimeEstimate {
  estimatedSeconds: number;
  /** Positive estimates are rounded up for a compact UI label. */
  roundedUpMinutes: number;
  visibleCharactersPerMinute: number;
  secondsPerFrame: number;
  formula: typeof STUDIO_READING_TIME_MODEL.formula;
}

export interface StudioProductionIssueSeveritySummary {
  totalCount: number;
  actionableCount: number;
  resolvedCount: number;
  suppressedCount: number;
}

export type StudioProductionLimitedArea =
  | "pages"
  | "frames"
  | "text"
  | "assets"
  | "issues";

export interface StudioProductionInsights {
  /** A machine-readable reminder that these metrics use only the supplied document projection. */
  basis: "local-document-structure";
  pages: {
    totalCount: number;
    withFramesCount: number;
    emptyCount: number;
  };
  frames: {
    totalCount: number;
    averagePerPage: number;
  };
  text: {
    dialogue: StudioProductionTextMetrics;
    narration: StudioProductionTextMetrics;
    total: StudioProductionTextMetrics;
  };
  readingTime: StudioReadingTimeEstimate;
  review: {
    statusCounts: Record<StudioProductionReviewStatus | "untracked", number>;
    lockedPageCount: number;
    approvedAndLockedPageCount: number;
    approvedUnlockedPageCount: number;
    coverage: {
      trackedPercent: number;
      lockedPercent: number;
      approvedPercent: number;
      changesRequestedPercent: number;
    };
  };
  assets: {
    totalCount: number;
    aiGeneratedCount: number;
    aiEditedCount: number;
    aiGeneratedAndEditedCount: number;
    aiAffectedCount: number;
    aiAffectedPercent: number;
  };
  issues: {
    totalCount: number;
    actionableCount: number;
    blockingCount: number;
    resolvedCount: number;
    suppressedCount: number;
    unclassifiedCount: number;
    bySeverity: Record<StudioProductionIssueSeverity, StudioProductionIssueSeveritySummary>;
  };
  normalization: {
    malformedEntryCount: number;
    limitsApplied: boolean;
    limitedAreas: readonly StudioProductionLimitedArea[];
  };
}

type MutableTextMetrics = {
  textCount: number;
  characterCount: number;
};

type ProcessingState = {
  malformedEntryCount: number;
  limitedAreas: Set<StudioProductionLimitedArea>;
  remainingFrames: number;
  remainingTextSegments: number;
  remainingTextCodeUnits: number;
  remainingAssets: number;
};

const REVIEW_STATUSES = new Set<StudioProductionReviewStatus>([
  "draft",
  "needs-review",
  "changes-requested",
  "approved",
]);

const ISSUE_SEVERITIES = new Set<StudioProductionIssueSeverity>([
  "error",
  "warning",
  "info",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeMetricInput(value: unknown): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) return 0;
  return Math.min(
    Math.floor(value),
    STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxNumericMetricInput
  );
}

function percentage(part: number, whole: number): number {
  if (whole <= 0) return 0;
  return Math.round((part / whole) * 1_000) / 10;
}

function average(part: number, whole: number): number {
  if (whole <= 0) return 0;
  return Math.round((part / whole) * 100) / 100;
}

function replaceUnsafeControlCharacters(value: string): string {
  let result = "";
  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0;
    const isUnsafeControl =
      (codePoint >= 0 && codePoint <= 8) ||
      codePoint === 11 ||
      codePoint === 12 ||
      (codePoint >= 14 && codePoint <= 31) ||
      codePoint === 127;
    result += isUnsafeControl ? " " : character;
  }
  return result;
}

/**
 * Deterministic editorial estimate, not an observed reader-engagement metric.
 *
 * Formula: `ceil((visible characters / 300) * 60 + frames * 2)` seconds. Inputs are
 * finite, non-negative integers after normalization and are capped by the public limit above.
 */
export function estimateStudioReadingTime(
  frameCount: unknown,
  visibleCharacterCount: unknown
): StudioReadingTimeEstimate {
  const frames = normalizeMetricInput(frameCount);
  const characters = normalizeMetricInput(visibleCharacterCount);
  const estimatedSeconds = Math.ceil(
    (characters / STUDIO_READING_TIME_MODEL.visibleCharactersPerMinute) * 60 +
      frames * STUDIO_READING_TIME_MODEL.secondsPerFrame
  );

  return {
    estimatedSeconds,
    roundedUpMinutes: estimatedSeconds === 0 ? 0 : Math.ceil(estimatedSeconds / 60),
    ...STUDIO_READING_TIME_MODEL,
  };
}

function markMalformed(state: ProcessingState): void {
  state.malformedEntryCount += 1;
}

function normalizeTextSource(value: unknown, state: ProcessingState): string | null {
  let raw: string | null = null;
  if (typeof value === "string") raw = value;
  else if (isRecord(value) && (typeof value.text === "string" || value.text === null)) {
    raw = value.text;
  } else if (value !== null && value !== undefined) {
    markMalformed(state);
  }

  if (raw === null) return null;
  if (state.remainingTextCodeUnits <= 0) {
    state.limitedAreas.add("text");
    return null;
  }

  const allowedCodeUnits = Math.min(
    raw.length,
    STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxTextCodeUnitsPerSegment,
    state.remainingTextCodeUnits
  );
  if (allowedCodeUnits < raw.length) state.limitedAreas.add("text");
  state.remainingTextCodeUnits -= allowedCodeUnits;

  return replaceUnsafeControlCharacters(raw.slice(0, allowedCodeUnits).normalize("NFKC"))
    .trim()
    .replace(/\s+/g, " ");
}

function countVisibleCodePoints(value: string): number {
  let count = 0;
  for (const character of value) {
    if (!/\s/u.test(character)) count += 1;
  }
  return count;
}

function addTextCollection(
  value: unknown,
  target: MutableTextMetrics,
  state: ProcessingState
): void {
  if (value === null || value === undefined) return;
  const entries = Array.isArray(value) ? value : [value];
  const processCount = Math.min(entries.length, state.remainingTextSegments);
  if (processCount < entries.length) state.limitedAreas.add("text");
  state.remainingTextSegments -= processCount;

  for (let index = 0; index < processCount; index += 1) {
    const normalized = normalizeTextSource(entries[index], state);
    if (!normalized) continue;
    target.textCount += 1;
    target.characterCount += countVisibleCodePoints(normalized);
  }
}

function addAssets(value: unknown, insights: StudioProductionInsights, state: ProcessingState): void {
  if (value === null || value === undefined) return;
  if (!Array.isArray(value)) {
    markMalformed(state);
    return;
  }

  const processCount = Math.min(value.length, state.remainingAssets);
  if (processCount < value.length) state.limitedAreas.add("assets");
  state.remainingAssets -= processCount;

  for (let index = 0; index < processCount; index += 1) {
    const asset = value[index];
    if (!isRecord(asset)) {
      markMalformed(state);
      continue;
    }
    const generated = asset.aiGenerated === true;
    const edited = asset.aiEdited === true;
    insights.assets.totalCount += 1;
    if (generated) insights.assets.aiGeneratedCount += 1;
    if (edited) insights.assets.aiEditedCount += 1;
    if (generated && edited) insights.assets.aiGeneratedAndEditedCount += 1;
    if (generated || edited) insights.assets.aiAffectedCount += 1;
  }
}

function addReview(
  value: unknown,
  insights: StudioProductionInsights,
  state: ProcessingState
): void {
  if (!isRecord(value)) {
    insights.review.statusCounts.untracked += 1;
    if (value !== null && value !== undefined) markMalformed(state);
    return;
  }

  const status = REVIEW_STATUSES.has(value.status as StudioProductionReviewStatus)
    ? (value.status as StudioProductionReviewStatus)
    : null;
  if (status) insights.review.statusCounts[status] += 1;
  else insights.review.statusCounts.untracked += 1;

  const locked = value.locked === true;
  if (locked) insights.review.lockedPageCount += 1;
  if (status === "approved" && locked) insights.review.approvedAndLockedPageCount += 1;
  if (status === "approved" && !locked) insights.review.approvedUnlockedPageCount += 1;
}

function addFrame(
  value: unknown,
  insights: StudioProductionInsights,
  state: ProcessingState
): boolean {
  if (!isRecord(value)) {
    markMalformed(state);
    return false;
  }

  insights.frames.totalCount += 1;
  addTextCollection(value.dialogue, insights.text.dialogue, state);
  addTextCollection(value.narration, insights.text.narration, state);
  addAssets(value.assets, insights, state);
  return true;
}

function addFrames(value: unknown, insights: StudioProductionInsights, state: ProcessingState): number {
  if (value === null || value === undefined) return 0;
  if (!Array.isArray(value)) {
    markMalformed(state);
    return 0;
  }

  const processCount = Math.min(value.length, state.remainingFrames);
  if (processCount < value.length) state.limitedAreas.add("frames");
  state.remainingFrames -= processCount;
  let validFrameCount = 0;
  for (let index = 0; index < processCount; index += 1) {
    if (addFrame(value[index], insights, state)) validFrameCount += 1;
  }
  return validFrameCount;
}

function addPage(value: unknown, insights: StudioProductionInsights, state: ProcessingState): void {
  if (!isRecord(value)) {
    markMalformed(state);
    return;
  }

  insights.pages.totalCount += 1;
  addReview(value.review, insights, state);
  addTextCollection(value.dialogue, insights.text.dialogue, state);
  addTextCollection(value.narration, insights.text.narration, state);
  addAssets(value.assets, insights, state);
  const frameCount = addFrames(value.frames, insights, state);
  if (frameCount > 0) insights.pages.withFramesCount += 1;
  else insights.pages.emptyCount += 1;
}

function addPages(value: unknown, insights: StudioProductionInsights, state: ProcessingState): void {
  if (value === null || value === undefined) return;
  if (!Array.isArray(value)) {
    markMalformed(state);
    return;
  }

  const processCount = Math.min(
    value.length,
    STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxPages
  );
  if (processCount < value.length) state.limitedAreas.add("pages");
  for (let index = 0; index < processCount; index += 1) {
    addPage(value[index], insights, state);
  }
}

function addIssues(value: unknown, insights: StudioProductionInsights, state: ProcessingState): void {
  if (value === null || value === undefined) return;
  if (!Array.isArray(value)) {
    markMalformed(state);
    return;
  }

  const processCount = Math.min(
    value.length,
    STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxIssues
  );
  if (processCount < value.length) state.limitedAreas.add("issues");

  for (let index = 0; index < processCount; index += 1) {
    const issue = value[index];
    if (!isRecord(issue)) {
      markMalformed(state);
      continue;
    }
    insights.issues.totalCount += 1;
    const resolved = issue.resolved === true;
    if (resolved) insights.issues.resolvedCount += 1;

    const severity = ISSUE_SEVERITIES.has(issue.severity as StudioProductionIssueSeverity)
      ? (issue.severity as StudioProductionIssueSeverity)
      : null;
    if (!severity) {
      insights.issues.unclassifiedCount += 1;
      continue;
    }

    const summary = insights.issues.bySeverity[severity];
    summary.totalCount += 1;
    if (resolved) {
      summary.resolvedCount += 1;
      continue;
    }
    if (issue.actionable === false) {
      summary.suppressedCount += 1;
      insights.issues.suppressedCount += 1;
      continue;
    }
    summary.actionableCount += 1;
    insights.issues.actionableCount += 1;
    if (severity === "error") insights.issues.blockingCount += 1;
  }
}

function emptyIssueSummary(): StudioProductionIssueSeveritySummary {
  return { totalCount: 0, actionableCount: 0, resolvedCount: 0, suppressedCount: 0 };
}

function createEmptyInsights(): StudioProductionInsights {
  return {
    basis: "local-document-structure",
    pages: { totalCount: 0, withFramesCount: 0, emptyCount: 0 },
    frames: { totalCount: 0, averagePerPage: 0 },
    text: {
      dialogue: { textCount: 0, characterCount: 0 },
      narration: { textCount: 0, characterCount: 0 },
      total: { textCount: 0, characterCount: 0 },
    },
    readingTime: estimateStudioReadingTime(0, 0),
    review: {
      statusCounts: {
        draft: 0,
        "needs-review": 0,
        "changes-requested": 0,
        approved: 0,
        untracked: 0,
      },
      lockedPageCount: 0,
      approvedAndLockedPageCount: 0,
      approvedUnlockedPageCount: 0,
      coverage: {
        trackedPercent: 0,
        lockedPercent: 0,
        approvedPercent: 0,
        changesRequestedPercent: 0,
      },
    },
    assets: {
      totalCount: 0,
      aiGeneratedCount: 0,
      aiEditedCount: 0,
      aiGeneratedAndEditedCount: 0,
      aiAffectedCount: 0,
      aiAffectedPercent: 0,
    },
    issues: {
      totalCount: 0,
      actionableCount: 0,
      blockingCount: 0,
      resolvedCount: 0,
      suppressedCount: 0,
      unclassifiedCount: 0,
      bySeverity: {
        error: emptyIssueSummary(),
        warning: emptyIssueSummary(),
        info: emptyIssueSummary(),
      },
    },
    normalization: {
      malformedEntryCount: 0,
      limitsApplied: false,
      limitedAreas: [],
    },
  };
}

/**
 * Computes bounded episode-production metrics from an explicitly supplied local projection.
 * Malformed entries are ignored and reported; unknown review statuses stay `untracked` rather
 * than being guessed as drafts, and unknown issue severities are not marked actionable.
 */
export function computeStudioProductionInsights(input: unknown): StudioProductionInsights {
  const insights = createEmptyInsights();
  const state: ProcessingState = {
    malformedEntryCount: 0,
    limitedAreas: new Set(),
    remainingFrames: STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxFrames,
    remainingTextSegments: STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxTextSegments,
    remainingTextCodeUnits: STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxTextCodeUnitsTotal,
    remainingAssets: STUDIO_PRODUCTION_INSIGHTS_LIMITS.maxAssets,
  };

  if (isRecord(input)) {
    addPages(input.pages, insights, state);
    addIssues(input.issues, insights, state);
  } else if (input !== null && input !== undefined) {
    markMalformed(state);
  }

  const pageCount = insights.pages.totalCount;
  const trackedPageCount =
    pageCount - insights.review.statusCounts.untracked;
  insights.frames.averagePerPage = average(insights.frames.totalCount, pageCount);
  insights.text.total = {
    textCount: insights.text.dialogue.textCount + insights.text.narration.textCount,
    characterCount:
      insights.text.dialogue.characterCount + insights.text.narration.characterCount,
  };
  insights.readingTime = estimateStudioReadingTime(
    insights.frames.totalCount,
    insights.text.total.characterCount
  );
  insights.review.coverage = {
    trackedPercent: percentage(trackedPageCount, pageCount),
    lockedPercent: percentage(insights.review.lockedPageCount, pageCount),
    approvedPercent: percentage(insights.review.statusCounts.approved, pageCount),
    changesRequestedPercent: percentage(
      insights.review.statusCounts["changes-requested"],
      pageCount
    ),
  };
  insights.assets.aiAffectedPercent = percentage(
    insights.assets.aiAffectedCount,
    insights.assets.totalCount
  );
  insights.normalization = {
    malformedEntryCount: state.malformedEntryCount,
    limitsApplied: state.limitedAreas.size > 0,
    limitedAreas: [...state.limitedAreas],
  };
  return insights;
}
