/**
 * Generated by the all-brush screen-fill quality benchmark.
 *
 * Empty by default: automatic rollout remains on the incumbent until a non-fallback physical-GPU
 * run proves live/commit continuity, committed texture equivalence, and bounded performance for a
 * particular catalogue id. Explicit development/verification backend selection is independent.
 */
export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION = 2 as const;
export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE = Object.freeze({
  schemaVersion: STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION,
  rendererContractVersion: 1,
  generatedAt: null as string | null,
  expiresAt: null as string | null,
  sourceCommit: null as string | null,
  benchmarkDigest: null as string | null,
  measurementRunCount: 0,
  measuredBrushCount: 0,
  hardwareClass: null as "hardware" | null,
  hardwareAdapterFingerprints: Object.freeze([] as string[]),
  approvedBrushIds: Object.freeze([] as string[]),
  rejectedBrushIds: Object.freeze([] as string[]),
});
