import type {
  StudioBrushDynamicsPresetId,
  StudioBrushDynamicsSettings,
} from "./studio-brush-dynamics";

type StudioBrushDynamicsVariant = {
  presetId: StudioBrushDynamicsPresetId;
  overrides: StudioBrushDynamicsSettings;
};

export const STUDIO_BRUSH_DYNAMICS_VARIANTS_WEB: Readonly<Record<string, StudioBrushDynamicsVariant>> = {
  /** Rainbow flow — soft wide stroke; hue cycling handled by product colour if available. */
  "web-rainbow-flow": {
    presetId: "airbrush",
    overrides: {
      seed: 0x2a_10_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.5,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.1,
        minSizeRatio: 0.45,
        minOpacityRatio: 0.45,
        curve: 0.9,
      },
      tip: { shape: "soft", softness: 0.55 },
      grain: {
        space: "stroke-fixed",
        amount: 0.1,
        scale: 8,
        contrast: 0.3,
        seed: 0x2a_10_0011,
      },
      tipLayers: [],
      dualBrush: {
        enabled: true,
        tip: { shape: "soft", softness: 0.7 },
        blendMode: "screen",
        sizeRatio: 1.25,
      },
      width: {
        base: 14,
        mappings: [{ source: "pressure", from: 0.45, to: 1.4, curve: 0.82 }],
        jitter: null,
      },
      opacity: {
        base: 0.75,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.8 }],
        jitter: null,
      },
      flow: {
        base: 0.65,
        mappings: [{ source: "pressure", from: 0.45, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      spacingRatio: 0.1,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.05,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.9, mappings: [], jitter: null },
    },
  },
  /** Hatch colouring pen — long spacing lattice along stroke. */
  "web-hatch-color": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x4a_7c_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.5,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.08 },
      grain: { amount: 0.06, scale: 5, contrast: 0.3, seed: 0x4a_7c_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 4,
        mappings: [{ source: "pressure", from: 0.65, to: 1.35, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.45, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.85, mappings: [], jitter: null },
      spacingRatio: 0.95,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.04,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 45,
        mappings: [],
        jitter: { mode: "add", amount: 4 },
      },
      roundness: { base: 0.35, mappings: [], jitter: null },
    },
  },
  /** Cel flat marker — hard soft-edge-free colour blocks. */
  "web-cel-flat": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xce_1f_0001,
      fallbackPressure: 0.65,
      maxSpeed: 1.3,
      taper: {
        enabled: true,
        startLength: 0.02,
        endLength: 0.06,
        minSizeRatio: 0.7,
        minOpacityRatio: 0.85,
        curve: 0.9,
      },
      tip: { shape: "hard", softness: 0.05 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 22,
        mappings: [{ source: "pressure", from: 0.7, to: 1.25, curve: 0.85 }],
        jitter: null,
      },
      opacity: {
        base: 0.92,
        mappings: [{ source: "pressure", from: 0.75, to: 1, curve: 0.8 }],
        jitter: null,
      },
      flow: { base: 0.95, mappings: [], jitter: null },
      spacingRatio: 0.18,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 0.95, mappings: [], jitter: null },
    },
  },
  /** Magma-class soft blender — soft airbrush with a visible first tap. */
  "web-blend-softener": {
    presetId: "airbrush",
    overrides: {
      seed: 0xb1_ed_0001,
      fallbackPressure: 0.45,
      maxSpeed: 1.4,
      taper: {
        enabled: true,
        startLength: 0.08,
        endLength: 0.18,
        minSizeRatio: 0.6,
        minOpacityRatio: 0.3,
        curve: 0.75,
      },
      tip: { shape: "soft", softness: 0.92 },
      grain: { amount: 0.04, scale: 20, contrast: 0.15, seed: 0xb1_ed_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 28,
        mappings: [{ source: "pressure", from: 0.55, to: 1.3, curve: 0.8 }],
        jitter: null,
      },
      opacity: {
        base: 0.55,
        mappings: [{ source: "pressure", from: 0.4, to: 0.85, curve: 0.78 }],
        jitter: null,
      },
      flow: {
        base: 0.5,
        mappings: [{ source: "pressure", from: 0.4, to: 0.8, curve: 0.8 }],
        jitter: null,
      },
      spacingRatio: 0.1,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.06,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  /** Dot screentone colouring pen. */
  "web-dot-tone": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xd0_70_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.6,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.1 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 3.5,
        mappings: [{ source: "pressure", from: 0.6, to: 1.4, curve: 0.9 }],
        jitter: { mode: "multiply", amount: 0.08 },
      },
      opacity: {
        base: 0.8,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 1.15,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.15,
      scatter: { mappings: [], jitter: { mode: "multiply", amount: 0.12 } },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  /** Kaleidoscope radial fold ink. */
  "web-kaleido-ink": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xca_1e_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.5,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.12 },
      grain: { amount: 0.05, scale: 9, contrast: 0.25, seed: 0xca_1e_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 8,
        mappings: [{ source: "pressure", from: 0.55, to: 1.35, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.88,
        mappings: [{ source: "pressure", from: 0.5, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 0.14,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.08,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.95, mappings: [], jitter: null },
    },
  },
  /** Fur / strand parallel filaments. */
  "web-fur-strand": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xf0_00_0001,
      fallbackPressure: 0.5,
      maxSpeed: 1.7,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.12,
        minSizeRatio: 0.35,
        minOpacityRatio: 0.4,
        curve: 0.9,
      },
      tip: { shape: "hard", softness: 0.18 },
      grain: { amount: 0.12, scale: 6, contrast: 0.35, seed: 0xf0_00_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 3.5,
        mappings: [{ source: "pressure", from: 0.5, to: 1.4, curve: 0.9 }],
        jitter: { mode: "multiply", amount: 0.1 },
      },
      opacity: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.35, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.85, mappings: [], jitter: null },
      spacingRatio: 0.22,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.18,
      scatter: { mappings: [], jitter: { mode: "multiply", amount: 0.1 } },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: { mode: "add", amount: 6 },
      },
      roundness: { base: 0.45, mappings: [], jitter: null },
    },
  },
  /** Double-contour outline pen. */
  "web-contour-double": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xc0_2d_0001,
      fallbackPressure: 0.6,
      maxSpeed: 1.3,
      taper: {
        enabled: true,
        startLength: 0.03,
        endLength: 0.1,
        minSizeRatio: 0.45,
        minOpacityRatio: 0.55,
        curve: 0.95,
      },
      tip: { shape: "hard", softness: 0.08 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 5,
        mappings: [{ source: "pressure", from: 0.6, to: 1.3, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.92,
        mappings: [{ source: "pressure", from: 0.65, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.95, mappings: [], jitter: null },
      spacingRatio: 0.12,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.02,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.85, mappings: [], jitter: null },
    },
  },
  /** Radial burst / speed-line stations. */
  "web-radial-burst": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xb0_57_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.8,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.1 },
      grain: { amount: 0.04, scale: 12, contrast: 0.2, seed: 0xb0_57_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 2.5,
        mappings: [{ source: "pressure", from: 0.55, to: 1.45, curve: 0.9 }],
        jitter: { mode: "multiply", amount: 0.12 },
      },
      opacity: {
        base: 0.85,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 0.85,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.22,
      scatter: { mappings: [], jitter: { mode: "multiply", amount: 0.15 } },
      angle: { base: 0, mappings: [], jitter: { mode: "add", amount: 12 } },
      roundness: { base: 0.35, mappings: [], jitter: null },
    },
  },
  /** Axis mirror freehand ink. */
  "web-mirror-ink": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x31_00_0001,
      fallbackPressure: 0.58,
      maxSpeed: 1.25,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.12,
        minSizeRatio: 0.3,
        minOpacityRatio: 0.5,
        curve: 1,
      },
      tip: { shape: "hard", softness: 0.12 },
      grain: { amount: 0.03, scale: 10, contrast: 0.2, seed: 0x31_00_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 8,
        mappings: [{ source: "pressure", from: 0.35, to: 1.45, curve: 0.92 }],
        jitter: null,
      },
      opacity: {
        base: 0.94,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.92, mappings: [], jitter: null },
      spacingRatio: 0.08,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.95, mappings: [], jitter: null },
    },
  },
  /** Grid-snap freehand assist ink. */
  "web-grid-ink": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x61_1d_0001,
      fallbackPressure: 0.65,
      maxSpeed: 1.4,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.05 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 6,
        mappings: [{ source: "pressure", from: 0.7, to: 1.25, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.95,
        mappings: [{ source: "pressure", from: 0.75, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 1, mappings: [], jitter: null },
      spacingRatio: 0.95,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 0.2, mappings: [], jitter: null },
    },
  },
  "web-spiro-orbit": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x51_00_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.6,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.15 },
      grain: { amount: 0.06, scale: 8, contrast: 0.25, seed: 0x51_00_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 5,
        mappings: [{ source: "pressure", from: 0.55, to: 1.35, curve: 0.9 }],
        jitter: { mode: "multiply", amount: 0.08 },
      },
      opacity: {
        base: 0.85,
        mappings: [{ source: "pressure", from: 0.45, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.88, mappings: [], jitter: null },
      spacingRatio: 0.16,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.12,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: { mode: "add", amount: 8 },
      },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  "web-zigzag-edge": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x21_9a_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.5,
      taper: {
        enabled: true,
        startLength: 0.03,
        endLength: 0.08,
        minSizeRatio: 0.5,
        minOpacityRatio: 0.55,
        curve: 0.95,
      },
      tip: { shape: "hard", softness: 0.1 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 4,
        mappings: [{ source: "pressure", from: 0.6, to: 1.3, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.9,
        mappings: [{ source: "pressure", from: 0.6, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.95, mappings: [], jitter: null },
      spacingRatio: 0.12,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.04,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: { mode: "add", amount: 4 },
      },
      roundness: { base: 0.55, mappings: [], jitter: null },
    },
  },
  "web-neon-tube": {
    presetId: "airbrush",
    overrides: {
      seed: 0x0e_00_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.4,
      taper: {
        enabled: true,
        startLength: 0.05,
        endLength: 0.12,
        minSizeRatio: 0.5,
        minOpacityRatio: 0.35,
        curve: 0.85,
      },
      tip: { shape: "soft", softness: 0.75 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 10,
        mappings: [{ source: "pressure", from: 0.55, to: 1.35, curve: 0.85 }],
        jitter: null,
      },
      opacity: {
        base: 0.55,
        mappings: [{ source: "pressure", from: 0.4, to: 0.85, curve: 0.8 }],
        jitter: null,
      },
      flow: {
        base: 0.45,
        mappings: [{ source: "pressure", from: 0.35, to: 0.75, curve: 0.8 }],
        jitter: null,
      },
      spacingRatio: 0.1,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.04,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  "web-pressure-flat": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xf1_a7_0001,
      fallbackPressure: 0.72,
      maxSpeed: 1.2,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.06 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 7,
        mappings: [],
        jitter: null,
      },
      opacity: {
        base: 0.96,
        mappings: [],
        jitter: null,
      },
      flow: { base: 1, mappings: [], jitter: null },
      spacingRatio: 0.08,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  "web-smudge-trail": {
    presetId: "airbrush",
    overrides: {
      seed: 0x5d_00_0001,
      fallbackPressure: 0.45,
      maxSpeed: 1.5,
      taper: {
        enabled: true,
        startLength: 0.1,
        endLength: 0.2,
        minSizeRatio: 0.55,
        minOpacityRatio: 0.25,
        curve: 0.75,
      },
      tip: { shape: "soft", softness: 0.88 },
      grain: { amount: 0.05, scale: 16, contrast: 0.15, seed: 0x5d_00_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 18,
        mappings: [{ source: "pressure", from: 0.5, to: 1.35, curve: 0.8 }],
        jitter: null,
      },
      opacity: {
        base: 0.5,
        mappings: [{ source: "pressure", from: 0.4, to: 0.8, curve: 0.75 }],
        jitter: null,
      },
      flow: {
        base: 0.45,
        mappings: [{ source: "pressure", from: 0.35, to: 0.7, curve: 0.8 }],
        jitter: null,
      },
      spacingRatio: 0.12,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.08,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  "web-cross-hatch-pen": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xc4_55_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.55,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.08 },
      grain: { amount: 0.05, scale: 7, contrast: 0.3, seed: 0xc4_55_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 2.8,
        mappings: [{ source: "pressure", from: 0.55, to: 1.4, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.78,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 0.9,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.05,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 45,
        mappings: [],
        jitter: { mode: "add", amount: 3 },
      },
      roundness: { base: 0.3, mappings: [], jitter: null },
    },
  },
  /** Lazy-mouse smooth ink — dense spacing, mild taper, very low scatter. */
  "web-lazy-ink": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x1a_2e_0001,
      fallbackPressure: 0.58,
      maxSpeed: 1.2,
      taper: {
        enabled: true,
        startLength: 0.05,
        endLength: 0.16,
        minSizeRatio: 0.25,
        minOpacityRatio: 0.5,
        curve: 1.1,
      },
      tip: { shape: "hard", softness: 0.14 },
      grain: { amount: 0.04, scale: 10, contrast: 0.2, seed: 0x1a_2e_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 8,
        mappings: [{ source: "pressure", from: 0.3, to: 1.5, curve: 0.92 }],
        jitter: { mode: "multiply", amount: 0.03 },
      },
      opacity: {
        base: 0.94,
        mappings: [{ source: "pressure", from: 0.5, to: 1, curve: 0.8 }],
        jitter: null,
      },
      flow: {
        base: 0.88,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.85 }],
        jitter: null,
      },
      spacingRatio: 0.06,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.9, mappings: [], jitter: null },
    },
  },
};
