import type {
  StudioBrushDynamicsPresetId,
  StudioBrushDynamicsSettings,
} from "./studio-brush-dynamics";

type StudioBrushDynamicsVariant = {
  presetId: StudioBrushDynamicsPresetId;
  overrides: StudioBrushDynamicsSettings;
};

export const STUDIO_BRUSH_DYNAMICS_VARIANTS_TOOLBAR: Readonly<Record<string, StudioBrushDynamicsVariant>> = {
  "hard-airbrush": {
    presetId: "ink-particle",
    overrides: {
      seed: 239,
      fallbackPressure: 0.62,
      maxSpeed: 2.1,
      taper: {
        enabled: true,
        startLength: 0.035,
        endLength: 0.07,
        minSizeRatio: 0.52,
        minOpacityRatio: 0.72,
        curve: 0.82,
      },
      tip: { shape: "hard", softness: 0.015 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 28,
        mappings: [{ source: "pressure", from: 0.46, to: 1.38, curve: 0.78 }],
        jitter: null,
      },
      opacity: {
        base: 1,
        mappings: [{ source: "pressure", from: 0.62, to: 1, curve: 0.72 }],
        jitter: null,
      },
      flow: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.64, to: 1, curve: 0.8 }],
        jitter: null,
      },
      spacingRatio: 0.075,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  "erodible-pencil": {
    presetId: "ink-particle",
    overrides: {
      seed: 347,
      fallbackPressure: 0.54,
      maxSpeed: 1.45,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.1,
        minSizeRatio: 0.34,
        minOpacityRatio: 0.48,
        curve: 1.16,
      },
      tip: { shape: "grain", softness: 0.2 },
      grain: {
        space: "stroke-fixed",
        amount: 0.3,
        scale: 2.35,
        contrast: 0.58,
        seed: 0xe20d_1b1e,
      },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 7,
        mappings: [{ source: "pressure", from: 0.32, to: 1.55, curve: 1.12 }],
        jitter: null,
      },
      opacity: {
        base: 0.94,
        mappings: [{ source: "pressure", from: 0.34, to: 1, curve: 1.02 }],
        jitter: null,
      },
      flow: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.42, to: 1, curve: 0.94 }],
        jitter: null,
      },
      spacingRatio: 0.08,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: {
        base: 0.64,
        mappings: [{ source: "tilt-magnitude", from: 1, to: 0.46, amount: 0.72 }],
        jitter: null,
      },
    },
  },
  "paint-tube": {
    presetId: "ink-particle",
    overrides: {
      seed: 353,
      fallbackPressure: 0.68,
      maxSpeed: 1.5,
      taper: {
        enabled: true,
        startLength: 0.025,
        endLength: 0.055,
        minSizeRatio: 0.64,
        minOpacityRatio: 0.88,
        curve: 0.72,
      },
      tip: { shape: "hard", softness: 0.01 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 30,
        mappings: [{ source: "pressure", from: 0.58, to: 1.42, curve: 0.76 }],
        jitter: null,
      },
      opacity: {
        base: 1,
        mappings: [{ source: "pressure", from: 0.82, to: 1, curve: 0.68 }],
        jitter: null,
      },
      flow: { base: 0.98, mappings: [], jitter: null },
      spacingRatio: 0.065,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: {
        base: 0.82,
        mappings: [{ source: "tilt-magnitude", from: 1, to: 0.68, amount: 0.45 }],
        jitter: null,
      },
    },
  },
  "tangent-normal-brush": {
    presetId: "ink-particle",
    overrides: {
      seed: 359,
      fallbackPressure: 0.64,
      maxSpeed: 1.8,
      taper: {
        enabled: true,
        startLength: 0.03,
        endLength: 0.07,
        minSizeRatio: 0.48,
        minOpacityRatio: 0.9,
        curve: 0.9,
      },
      tip: { shape: "hard", softness: 0 },
      grain: { amount: 0 },
      colorDynamics: {
        backgroundColor: null,
        foregroundBackgroundMix: 0,
        foregroundBackgroundJitter: 0,
        hueJitter: 0,
        saturationJitter: 0,
        valueJitter: 0,
      },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 20,
        mappings: [{ source: "pressure", from: 0.46, to: 1.4, curve: 0.82 }],
        jitter: null,
      },
      opacity: { base: 1, mappings: [], jitter: null },
      flow: { base: 1, mappings: [], jitter: null },
      spacingRatio: 0.075,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.9, mappings: [], jitter: null },
    },
  },
  /**
   * Sketchpad-class Tile: discrete hard stamps on a regular pitch so the stroke reads as a
   * lattice of tiles rather than a continuous ribbon (Sketch.io "Tile" affordance).
   */
  "sketchpad-tile": {
    presetId: "ink-particle",
    overrides: {
      seed: 701,
      fallbackPressure: 0.6,
      maxSpeed: 1.6,
      taper: {
        enabled: false,
        startLength: 0,
        endLength: 0,
        minSizeRatio: 1,
        minOpacityRatio: 1,
        curve: 1,
      },
      tip: { shape: "hard", softness: 0.04 },
      grain: {
        space: "stroke-fixed",
        amount: 0.12,
        scale: 3.2,
        contrast: 0.42,
        seed: 0x71_1e_0001,
      },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 18,
        mappings: [{ source: "pressure", from: 0.72, to: 1.18, curve: 0.85 }],
        jitter: null,
      },
      opacity: {
        base: 0.92,
        mappings: [{ source: "pressure", from: 0.7, to: 1, curve: 0.8 }],
        jitter: null,
      },
      flow: { base: 0.95, mappings: [], jitter: null },
      // Pitch ≈ tip diameter → non-overlapping tile stamps along the path.
      spacingRatio: 1.05,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.92, mappings: [], jitter: null },
    },
  },
  /**
   * Sketchpad-class Mirror: smooth continuous pen that pairs with vertical symmetry
   * (`resolveStudioSketchpadBrushSymmetryHint`) for automatic left/right twins.
   */
  "sketchpad-mirror": {
    presetId: "ink-particle",
    overrides: {
      seed: 703,
      fallbackPressure: 0.58,
      maxSpeed: 1.7,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.1,
        minSizeRatio: 0.28,
        minOpacityRatio: 0.55,
        curve: 1.05,
      },
      tip: { shape: "hard", softness: 0.12 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 12,
        mappings: [{ source: "pressure", from: 0.28, to: 1.45, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.94,
        mappings: [{ source: "pressure", from: 0.48, to: 1, curve: 0.82 }],
        jitter: null,
      },
      flow: {
        base: 0.88,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.85 }],
        jitter: null,
      },
      spacingRatio: 0.09,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.88, mappings: [], jitter: null },
    },
  },
  /**
   * Sketchpad-class Soft Marker: wide soft envelope with gentle pressure (consumer sketch pen).
   */
  "sketchpad-soft-marker": {
    presetId: "airbrush",
    overrides: {
      seed: 709,
      fallbackPressure: 0.55,
      maxSpeed: 1.35,
      taper: {
        enabled: true,
        startLength: 0.05,
        endLength: 0.12,
        minSizeRatio: 0.48,
        minOpacityRatio: 0.4,
        curve: 0.88,
      },
      tip: { shape: "soft", softness: 0.72 },
      grain: {
        space: "canvas-fixed",
        amount: 0.06,
        scale: 14,
        contrast: 0.28,
        seed: 0x50_f7_0003,
      },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 22,
        mappings: [{ source: "pressure", from: 0.42, to: 1.28, curve: 0.78 }],
        jitter: { mode: "multiply", amount: 0.04 },
      },
      opacity: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.38, to: 0.92, curve: 0.8 }],
        jitter: null,
      },
      flow: {
        base: 0.55,
        mappings: [{ source: "pressure", from: 0.42, to: 0.88, curve: 0.82 }],
        jitter: null,
      },
      spacingRatio: 0.11,
      spacing: { mappings: [], jitter: { mode: "multiply", amount: 0.04 } },
      scatterRatio: 0.02,
      scatter: { mappings: [], jitter: null },
      angle: { base: 0, mappings: [], jitter: null },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  /**
   * Bomomo-class multi-agent: dense scatter + dual tips so multiple “pens” orbit the stroke.
   * Pair with `planStudioWebMultiAgentSamples` for exact agent geometry in product paths.
   */
  "web-multi-agent": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xb0_00_0001,
      fallbackPressure: 0.52,
      maxSpeed: 1.85,
      taper: {
        enabled: true,
        startLength: 0.02,
        endLength: 0.08,
        minSizeRatio: 0.35,
        minOpacityRatio: 0.4,
        curve: 1.05,
      },
      tip: { shape: "hard", softness: 0.18 },
      grain: {
        space: "stroke-fixed",
        amount: 0.1,
        scale: 4.5,
        contrast: 0.38,
        seed: 0xb0_00_0011,
      },
      tipLayers: [
        { scale: 0.55, opacity: 0.55, offsetX: 0.35, offsetY: -0.2 },
        { scale: 0.48, opacity: 0.45, offsetX: -0.4, offsetY: 0.25 },
      ],
      dualBrush: {
        enabled: true,
        tip: { shape: "hard", softness: 0.2 },
        blendMode: "screen",
        sizeRatio: 0.72,
      },
      width: {
        base: 12,
        mappings: [{ source: "pressure", from: 0.35, to: 1.55, curve: 0.88 }],
        jitter: { mode: "multiply", amount: 0.14 },
      },
      opacity: {
        base: 0.78,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.8 }],
        jitter: { mode: "multiply", amount: 0.08 },
      },
      flow: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.45, to: 1, curve: 0.85 }],
        jitter: null,
      },
      spacingRatio: 0.12,
      spacing: { mappings: [], jitter: { mode: "multiply", amount: 0.08 } },
      scatterRatio: 0.55,
      scatter: {
        mappings: [{ source: "speed", from: 0.7, to: 1.45, curve: 1.1 }],
        jitter: { mode: "multiply", amount: 0.12 },
      },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: { mode: "add", amount: 18 },
      },
      roundness: { base: 0.82, mappings: [], jitter: null },
    },
  },
  /** Comic hand-ink: multi-pass jitter via scatter + grain for sketchy edges. */
  "web-rough-ink": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x20_f0_0001,
      fallbackPressure: 0.62,
      maxSpeed: 1.5,
      taper: {
        enabled: true,
        startLength: 0.03,
        endLength: 0.14,
        minSizeRatio: 0.22,
        minOpacityRatio: 0.5,
        curve: 1.15,
      },
      tip: { shape: "hard", softness: 0.08 },
      grain: {
        space: "stroke-fixed",
        amount: 0.22,
        scale: 2.4,
        contrast: 0.55,
        seed: 0x20_f0_0011,
      },
      tipLayers: [
        { scale: 0.92, opacity: 0.55, offsetX: 0.08, offsetY: 0.06 },
        { scale: 0.88, opacity: 0.4, offsetX: -0.1, offsetY: -0.05 },
      ],
      dualBrush: { enabled: false },
      width: {
        base: 7,
        mappings: [{ source: "pressure", from: 0.25, to: 1.65, curve: 0.95 }],
        jitter: { mode: "multiply", amount: 0.18 },
      },
      opacity: {
        base: 0.92,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.75 }],
        jitter: { mode: "multiply", amount: 0.06 },
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 0.07,
      spacing: { mappings: [], jitter: { mode: "multiply", amount: 0.1 } },
      scatterRatio: 0.12,
      scatter: { mappings: [], jitter: { mode: "multiply", amount: 0.2 } },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: { mode: "add", amount: 8 },
      },
      roundness: {
        base: 0.72,
        mappings: [{ source: "pressure", from: 0.85, to: 1, curve: 1 }],
        jitter: { mode: "multiply", amount: 0.1 },
      },
    },
  },
  /** Gravity drip: elongated beads with vertical scatter bias. */
  "web-gravity-drip": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xd2_10_0001,
      fallbackPressure: 0.6,
      maxSpeed: 1.25,
      taper: {
        enabled: true,
        startLength: 0.02,
        endLength: 0.22,
        minSizeRatio: 0.18,
        minOpacityRatio: 0.35,
        curve: 1.25,
      },
      tip: { shape: "hard", softness: 0.22 },
      grain: {
        space: "canvas-fixed",
        amount: 0.14,
        scale: 5,
        contrast: 0.4,
        seed: 0xd2_10_0011,
      },
      tipLayers: [
        { scale: 0.4, opacity: 0.7, offsetX: 0, offsetY: 0.55 },
        { scale: 0.28, opacity: 0.5, offsetX: 0.05, offsetY: 1.1 },
      ],
      dualBrush: { enabled: false },
      width: {
        base: 14,
        mappings: [{ source: "pressure", from: 0.4, to: 1.4, curve: 0.9 }],
        jitter: { mode: "multiply", amount: 0.1 },
      },
      opacity: {
        base: 0.88,
        mappings: [{ source: "pressure", from: 0.5, to: 1, curve: 0.8 }],
        jitter: null,
      },
      flow: {
        base: 0.82,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.85 }],
        jitter: null,
      },
      spacingRatio: 0.16,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.08,
      scatter: {
        mappings: [{ source: "pressure", from: 0.6, to: 1.5, curve: 1.2 }],
        jitter: { mode: "multiply", amount: 0.15 },
      },
      angle: {
        base: 90,
        mappings: [],
        jitter: { mode: "add", amount: 12 },
      },
      roundness: {
        base: 0.45,
        mappings: [{ source: "pressure", from: 0.7, to: 1.1, curve: 1 }],
        jitter: null,
      },
    },
  },
  /** Soft cloud spray: wide soft tip + heavy scatter for Kleki-class mist. */
  "web-soft-cloud": {
    presetId: "airbrush",
    overrides: {
      seed: 0xc1_0d_0001,
      fallbackPressure: 0.48,
      maxSpeed: 1.55,
      taper: {
        enabled: true,
        startLength: 0.06,
        endLength: 0.16,
        minSizeRatio: 0.55,
        minOpacityRatio: 0.25,
        curve: 0.82,
      },
      tip: { shape: "soft", softness: 0.88 },
      grain: {
        space: "canvas-fixed",
        amount: 0.08,
        scale: 18,
        contrast: 0.22,
        seed: 0xc1_0d_0011,
      },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 26,
        mappings: [{ source: "pressure", from: 0.5, to: 1.35, curve: 0.75 }],
        jitter: { mode: "multiply", amount: 0.12 },
      },
      opacity: {
        base: 0.62,
        mappings: [{ source: "pressure", from: 0.42, to: 0.9, curve: 0.78 }],
        jitter: { mode: "multiply", amount: 0.08 },
      },
      flow: {
        base: 0.55,
        mappings: [{ source: "pressure", from: 0.4, to: 0.85, curve: 0.8 }],
        jitter: null,
      },
      spacingRatio: 0.12,
      spacing: { mappings: [], jitter: { mode: "multiply", amount: 0.06 } },
      scatterRatio: 0.28,
      scatter: {
        mappings: [{ source: "speed", from: 0.75, to: 1.35, curve: 1 }],
        jitter: { mode: "multiply", amount: 0.18 },
      },
      angle: { base: 0, mappings: [], jitter: { mode: "add", amount: 40 } },
      roundness: { base: 1, mappings: [], jitter: null },
    },
  },
  /** Flat chisel calligraphy — direction-driven angle, low roundness. */
  "web-calligraphy-ribbon": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xca_11_0001,
      fallbackPressure: 0.58,
      maxSpeed: 1.4,
      taper: {
        enabled: true,
        startLength: 0.04,
        endLength: 0.12,
        minSizeRatio: 0.35,
        minOpacityRatio: 0.55,
        curve: 1.05,
      },
      tip: { shape: "hard", softness: 0.1 },
      grain: { amount: 0.05, scale: 6, contrast: 0.25, seed: 0xca_11_0011 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 16,
        mappings: [
          { source: "pressure", from: 0.45, to: 1.45, curve: 0.88 },
          { source: "tilt-magnitude", from: 0.95, to: 1.25 },
        ],
        jitter: null,
      },
      opacity: {
        base: 0.95,
        mappings: [{ source: "pressure", from: 0.6, to: 1, curve: 0.8 }],
        jitter: null,
      },
      flow: { base: 0.9, mappings: [], jitter: null },
      spacingRatio: 0.08,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: {
        base: 0.28,
        mappings: [{ source: "pressure", from: 0.85, to: 1.15, curve: 1 }],
        jitter: null,
      },
    },
  },
  /** Dashed stitch — long spacing so deposits read as dashes. */
  "web-dash-stitch": {
    presetId: "ink-particle",
    overrides: {
      seed: 0xda_50_0001,
      fallbackPressure: 0.6,
      maxSpeed: 1.6,
      taper: { enabled: false, startLength: 0, endLength: 0, minSizeRatio: 1, minOpacityRatio: 1, curve: 1 },
      tip: { shape: "hard", softness: 0.06 },
      grain: { amount: 0 },
      tipLayers: [],
      dualBrush: { enabled: false },
      width: {
        base: 5,
        mappings: [{ source: "pressure", from: 0.7, to: 1.25, curve: 0.9 }],
        jitter: null,
      },
      opacity: {
        base: 0.9,
        mappings: [{ source: "pressure", from: 0.55, to: 1, curve: 0.85 }],
        jitter: null,
      },
      flow: { base: 1, mappings: [], jitter: null },
      spacingRatio: 1.65,
      spacing: { mappings: [], jitter: null },
      scatterRatio: 0.02,
      scatter: { mappings: [], jitter: null },
      angle: {
        base: 0,
        mappings: [{ source: "direction", mode: "add", from: 0, to: 360 }],
        jitter: null,
      },
      roundness: { base: 0.55, mappings: [], jitter: null },
    },
  },
  /** Fun scatter stamps — high scatter, medium spacing. */
  "web-scatter-stamp": {
    presetId: "ink-particle",
    overrides: {
      seed: 0x57_a7_0001,
      fallbackPressure: 0.55,
      maxSpeed: 1.7,
      taper: {
        enabled: true,
        startLength: 0.02,
        endLength: 0.08,
        minSizeRatio: 0.4,
        minOpacityRatio: 0.4,
        curve: 0.95,
      },
      tip: { shape: "hard", softness: 0.15 },
      grain: {
        space: "stroke-fixed",
        amount: 0.12,
        scale: 4,
        contrast: 0.4,
        seed: 0x57_a7_0011,
      },
      tipLayers: [
        { scale: 0.7, opacity: 0.55, offsetX: 0.4, offsetY: -0.3 },
        { scale: 0.55, opacity: 0.45, offsetX: -0.35, offsetY: 0.35 },
      ],
      dualBrush: { enabled: false },
      width: {
        base: 14,
        mappings: [{ source: "pressure", from: 0.4, to: 1.5, curve: 0.85 }],
        jitter: { mode: "multiply", amount: 0.22 },
      },
      opacity: {
        base: 0.85,
        mappings: [{ source: "pressure", from: 0.4, to: 0.95, curve: 0.8 }],
        jitter: { mode: "multiply", amount: 0.1 },
      },
      flow: { base: 0.75, mappings: [], jitter: null },
      spacingRatio: 0.55,
      spacing: { mappings: [], jitter: { mode: "multiply", amount: 0.12 } },
      scatterRatio: 0.75,
      scatter: {
        mappings: [{ source: "speed", from: 0.8, to: 1.4, curve: 1 }],
        jitter: { mode: "multiply", amount: 0.2 },
      },
      angle: {
        base: 0,
        mappings: [],
        jitter: { mode: "add", amount: 180 },
      },
      roundness: { base: 0.85, mappings: [], jitter: { mode: "multiply", amount: 0.12 } },
    },
  },
};
