/** Product capability map for the Storyworld Causality Lab.
 *
 * `engine` means the included deterministic core already supplies a usable result.
 * `adapter` means the feature composes that core with an existing ToonSpectrum subsystem.
 * `experimental` means the contract is defined but must remain opt-in until its benchmark gate passes.
 */

export type StoryworldCapabilityMaturity = "engine" | "adapter" | "experimental";
export type StoryworldCapabilityGroup =
  | "world-model"
  | "character-intelligence"
  | "narrative-contract"
  | "reader-experience"
  | "production-operations"
  | "global-release"
  | "trust-collaboration";

export interface StoryworldCapability {
  readonly id: string;
  readonly group: StoryworldCapabilityGroup;
  readonly name: string;
  readonly oneLine: string;
  readonly maturity: StoryworldCapabilityMaturity;
  readonly engineEntry?: string;
  readonly composesWith?: readonly string[];
  readonly guardrail: string;
  readonly evidence: readonly string[];
}

export const STORYWORLD_CAPABILITY_GROUPS: Readonly<
  Record<StoryworldCapabilityGroup, { readonly label: string; readonly purpose: string }>
> = {
  "world-model": {
    label: "스토리월드 디지털 트윈",
    purpose: "사실·시간·장소·원인과 결과를 작품의 실행 가능한 상태로 바꿉니다.",
  },
  "character-intelligence": {
    label: "인물 지능과 관점",
    purpose: "작가가 아는 사실과 등장인물이 아는 사실을 분리해 행동의 설득력을 지킵니다.",
  },
  "narrative-contract": {
    label: "서사 계약",
    purpose: "복선·회수·모티프·감정 변화·독자 공개 시점을 검증 가능한 약속으로 관리합니다.",
  },
  "reader-experience": {
    label: "독자 경험 오케스트레이션",
    purpose: "기존 스크롤·가독성·품질 분석을 인과관계와 함께 해석합니다.",
  },
  "production-operations": {
    label: "제작 운영체계",
    purpose: "창작 결정이 일정·자산·작업자·렌더링 비용에 미치는 영향을 같은 분기에서 비교합니다.",
  },
  "global-release": {
    label: "글로벌 릴리스",
    purpose: "번역·접근성·플랫폼 변형을 마지막 검수가 아니라 장면 설계 단계에서 시뮬레이션합니다.",
  },
  "trust-collaboration": {
    label: "신뢰·권리·협업",
    purpose: "왜 문제가 생겼고 어떤 변경이 해결했는지를 재현 가능한 영수증으로 남깁니다.",
  },
};

export const STORYWORLD_CAPABILITIES: readonly StoryworldCapability[] = [
  {
    id: "canon-state-machine",
    group: "world-model",
    name: "캐논 상태 머신",
    oneLine: "장면 전후 사실 값을 실행해 모순과 성립하지 않은 전제를 찾습니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "사실을 추측하지 않고 명시적으로 등록된 상태만 계산합니다.",
    evidence: ["worldTimeline", "canon axis score", "proof receipt"],
  },
  {
    id: "plot-physics",
    group: "world-model",
    name: "플롯 물리 엔진",
    oneLine: "사건 의존성을 그래프로 만들고 원인이 빠졌을 때 무너지는 후속 장면을 추적합니다.",
    maturity: "engine",
    engineEntry: "simulateStoryworldCounterfactual",
    guardrail: "분기 결과는 제안일 뿐 원본 장면을 자동 삭제하지 않습니다.",
    evidence: ["dependency cycle", "impactedSceneIds", "added/resolved issues"],
  },
  {
    id: "counterfactual-multiverse",
    group: "world-model",
    name: "반사실 멀티버스",
    oneLine: "장면 삭제·순서 이동·사실 변경을 가상 적용해 품질 축별 차이를 비교합니다.",
    maturity: "engine",
    engineEntry: "simulateStoryworldCounterfactual",
    guardrail: "가상 분기는 별도 객체이며 명시적 승인 전에는 문서 History에 들어가지 않습니다.",
    evidence: ["scoreDelta", "issue diff", "impact cone"],
  },
  {
    id: "pareto-branch-board",
    group: "world-model",
    name: "파레토 분기 보드",
    oneLine: "하나의 숨은 종합 점수 대신 어느 품질도 다른 분기보다 나쁘지 않은 후보를 표시합니다.",
    maturity: "engine",
    engineEntry: "rankStoryworldParetoFrontier",
    guardrail: "창작 선호를 임의 가중치로 덮지 않습니다.",
    evidence: ["frontier", "dominatesIds", "dominatedByIds"],
  },
  {
    id: "timeline-location-proof",
    group: "world-model",
    name: "시간·공간 존재 증명",
    oneLine: "같은 인물이 같은 시간에 다른 장소에 있거나 이유 없는 시간 역행을 탐지합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "회상·몽타주 같은 연출은 명시적 표식으로 예외 처리합니다.",
    evidence: ["time-regression", "impossible-travel"],
  },
  {
    id: "belief-matrix",
    group: "character-intelligence",
    name: "인물별 믿음 행렬",
    oneLine: "각 인물이 장면 시점에 알고 있는 사실과 아직 모르는 비밀을 분리합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "작가 관점의 사실을 등장인물 지식으로 자동 복사하지 않습니다.",
    evidence: ["knowledgeMatrix", "knowledge-leak"],
  },
  {
    id: "knowledge-leak-detector",
    group: "character-intelligence",
    name: "초능력 대사 탐지기",
    oneLine: "보거나 듣거나 추론한 적 없는 정보를 인물이 말하거나 행동에 쓰는 순간을 찾습니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "수정은 앞 장면에 전달 비트를 제안하며 대사를 몰래 재작성하지 않습니다.",
    evidence: ["knowledgeUses", "add-reveal repair intent"],
  },
  {
    id: "secret-boundary",
    group: "character-intelligence",
    name: "비밀 경계 지도",
    oneLine: "인물별 비밀 보유·공유·노출 경계를 한눈에 비교합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "비밀은 권한처럼 다루되 작품 데이터 밖의 실제 개인정보와 결합하지 않습니다.",
    evidence: ["secretFactIds", "readerFactIds"],
  },
  {
    id: "antagonist-response-sandbox",
    group: "character-intelligence",
    name: "상대 행동 샌드박스",
    oneLine: "한 인물의 지식이 바뀌었을 때 목표와 다음 행동 후보가 달라지는 분기를 비교합니다.",
    maturity: "adapter",
    composesWith: ["AI 어시스트", "제안 브랜치", "캐릭터 바이블"],
    guardrail: "모델 출력은 ghost proposal이며 인물 성격·사실 제약을 통과한 항목만 표시합니다.",
    evidence: ["character fact context", "proposal provenance", "partial accept"],
  },
  {
    id: "unreliable-narrator-lens",
    group: "character-intelligence",
    name: "불신 화자 렌즈",
    oneLine: "객관적 세계 상태, 화자의 믿음, 독자에게 보인 정보가 의도적으로 다른 장면을 관리합니다.",
    maturity: "experimental",
    composesWith: ["대사", "캡션", "독자 공개 행렬"],
    guardrail: "모순을 오류로 지우지 않고 ‘의도된 불일치’ 계약이 있을 때만 허용합니다.",
    evidence: ["world fact", "narrator belief", "reader reveal"],
  },
  {
    id: "setup-payoff-ledger",
    group: "narrative-contract",
    name: "체호프 원장",
    oneLine: "설치·회수·기한·중복 회수를 장편 전체에서 추적합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "열린 복선을 결함으로 단정하지 않고 작가가 설정한 기한을 넘겼을 때만 오류화합니다.",
    evidence: ["setupLedger", "orphan-payoff", "unpaid-setup"],
  },
  {
    id: "spoiler-firewall",
    group: "narrative-contract",
    name: "스포일러 방화벽",
    oneLine: "대사뿐 아니라 장면 메타데이터의 독자 공개가 예정 시점을 침범하는지 검사합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "예정 공개 순서가 없는 사실에는 자의적 경고를 만들지 않습니다.",
    evidence: ["premature-reader-reveal", "reader-reveal-missed"],
  },
  {
    id: "motif-dna",
    group: "narrative-contract",
    name: "시각 모티프 DNA",
    oneLine: "색·소품·구도·소리 모티프의 등장 빈도와 너무 긴 공백을 추적합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "빈도는 미학적 정답이 아니라 작품이 직접 선언한 목표만 사용합니다.",
    evidence: ["motifLedger", "motif-gap", "motif-underused"],
  },
  {
    id: "emotional-conservation",
    group: "narrative-contract",
    name: "감정 보존 법칙",
    oneLine: "인물 감정이 큰 폭으로 바뀌는데 독자가 관찰할 연결 비트가 없는 장면을 찾습니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "숫자는 창작 평가가 아니라 장면 간 급격한 변화의 검토 신호로만 사용합니다.",
    evidence: ["emotional-whiplash", "add-transition repair intent"],
  },
  {
    id: "cliffhanger-debt",
    group: "narrative-contract",
    name: "클리프행어 부채",
    oneLine: "회차 말에 만든 질문이 언제, 어느 강도로 답을 받는지 복선 원장과 함께 추적합니다.",
    maturity: "adapter",
    composesWith: ["페이지 시퀀스", "회차 경계", "스크롤 리듬"],
    guardrail: "클리프행어를 강제하지 않고 약속 후 장기간 무응답만 표시합니다.",
    evidence: ["episode boundary", "setup contract", "payoff scene"],
  },
  {
    id: "reader-persona-swarm",
    group: "reader-experience",
    name: "독자 페르소나 군집",
    oneLine: "기존 스크롤 시뮬레이터·가독성 검사 결과를 캐주얼·정독·스키밍 독자별로 인과 분석과 결합합니다.",
    maturity: "adapter",
    composesWith: ["webtoon-scroll-pacing-simulator", "social reader ecosystem"],
    guardrail: "실제 독자 행동처럼 오표시하지 않고 휴리스틱·실측·예측을 구분합니다.",
    evidence: ["source label", "persona result", "confidence"],
  },
  {
    id: "attention-budget",
    group: "reader-experience",
    name: "주의력 예산",
    oneLine: "새 사실·새 인물·공간 전환·대사량이 한 화면에 몰릴 때 인지 부하를 표시합니다.",
    maturity: "adapter",
    composesWith: ["패널", "말풍선", "스크롤 리듬", "캐논 상태"],
    guardrail: "장르별 실험을 막는 하드 제한이 아니라 비교 가능한 부하 구성요소를 보여줍니다.",
    evidence: ["new fact count", "visible panel count", "dialogue density"],
  },
  {
    id: "adaptive-recap",
    group: "reader-experience",
    name: "지식 기반 맞춤 회상",
    oneLine: "독자가 이미 본 사실만 사용해 휴재 복귀·시즌 시작용 리캡 후보를 만듭니다.",
    maturity: "adapter",
    composesWith: ["독자 공개 행렬", "AI 어시스트", "페이지 템플릿"],
    guardrail: "미공개 사실과 다음 화 스포일러를 입력 컨텍스트에서 구조적으로 제외합니다.",
    evidence: ["readerFactIds", "source scene links", "generated provenance"],
  },
  {
    id: "community-fork-simulator",
    group: "reader-experience",
    name: "커뮤니티 선택지 포크",
    oneLine: "독자 투표 선택지를 원본 캐논과 분리된 반사실 분기로 실행해 후속 모순을 미리 봅니다.",
    maturity: "adapter",
    composesWith: ["댓글·투표", "버전 브랜치", "반사실 멀티버스"],
    guardrail: "인기 투표가 원본을 덮어쓰지 않으며 채택 시 명시적 브랜치 병합을 거칩니다.",
    evidence: ["branch id", "vote snapshot", "merge receipt"],
  },
  {
    id: "production-digital-twin",
    group: "production-operations",
    name: "제작 디지털 트윈",
    oneLine: "장면의 드로잉·레터링·렌더·검수 시간을 합산하고 가용 시간과 비교합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "시간 값이 없으면 추정해 채우지 않고 미입력으로 남깁니다.",
    evidence: ["production summary", "capacity utilization", "critical scenes"],
  },
  {
    id: "creative-opportunity-cost",
    group: "production-operations",
    name: "창작 기회비용 비교",
    oneLine: "서사 점수가 비슷한 분기끼리 추가 제작 시간과 신규 자산 수를 비교합니다.",
    maturity: "adapter",
    composesWith: ["파레토 분기 보드", "자산 패밀리", "작업 큐"],
    guardrail: "비용이 낮다는 이유만으로 분기를 자동 선택하지 않습니다.",
    evidence: ["quality axes", "total minutes", "unique assets"],
  },
  {
    id: "asset-reuse-orbit",
    group: "production-operations",
    name: "자산 재사용 궤도",
    oneLine: "배경·소품·3D·브러시 리비전이 다음 장면에서 재사용될 가능성과 교체 파급을 계산합니다.",
    maturity: "adapter",
    composesWith: ["asset family", "immutable revision", "3D scene"],
    guardrail: "기존 원고는 mutable default가 아니라 정확한 리비전을 계속 참조합니다.",
    evidence: ["asset revision", "reuse count", "impact scenes"],
  },
  {
    id: "shot-reshoot-cost",
    group: "production-operations",
    name: "가상 재촬영 비용",
    oneLine: "카메라·의상·배경 변경이 이미 완성된 컷과 파생 출력에 미치는 재작업 범위를 계산합니다.",
    maturity: "adapter",
    composesWith: ["3D shot", "panel graph", "export dependency"],
    guardrail: "영향 범위를 먼저 제시하고 변경은 별도 transaction으로 승인합니다.",
    evidence: ["dependency cone", "render minutes", "affected exports"],
  },
  {
    id: "team-load-balancer",
    group: "production-operations",
    name: "창작팀 부하 균형",
    oneLine: "장면별 역할 의존성과 작업량을 계산해 병렬 처리 가능한 작업을 제안합니다.",
    maturity: "adapter",
    composesWith: ["협업 역할", "작업 상태", "제작 디지털 트윈"],
    guardrail: "개인 성과 평가에 사용하지 않고 작업 분할·대기 원인만 보여줍니다.",
    evidence: ["assignee load", "blocked tasks", "parallelizable groups"],
  },
  {
    id: "localization-shape-stress",
    group: "global-release",
    name: "번역 형태 스트레스 테스트",
    oneLine: "언어별 확장 길이가 말풍선·세로쓰기·효과음 형태를 깨뜨리는지 장면별 검사합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "실제 번역 길이 또는 명시적 테스트 문자열만 사용하고 임의 평균치를 사실처럼 쓰지 않습니다.",
    evidence: ["localization-overflow", "locale", "capacity"],
  },
  {
    id: "semantic-lettering",
    group: "global-release",
    name: "의미 보존 레터링",
    oneLine: "대사 의미·강조·말 끊김과 말풍선 형태를 분리해 번역 후에도 연출 의도를 유지합니다.",
    maturity: "adapter",
    composesWith: ["말풍선", "텍스트", "번역 메모리"],
    guardrail: "번역 텍스트와 레이아웃 변경을 서로 다른 History operation으로 기록합니다.",
    evidence: ["semantic spans", "layout revision", "translation revision"],
  },
  {
    id: "accessibility-story-layer",
    group: "global-release",
    name: "접근성 스토리 레이어",
    oneLine: "읽기 순서·비색상 단서·대체 텍스트·소리의 시각화·감소 동작 대체를 장면 데이터로 저장합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "자동 생성된 대체 설명은 검토 전 게시되지 않습니다.",
    evidence: ["accessibility evidence", "gap issue", "review state"],
  },
  {
    id: "platform-morph-preview",
    group: "global-release",
    name: "플랫폼 형태 변환 프리뷰",
    oneLine: "세로 웹툰·페이지 만화·숏폼·모션컷 변형이 공개 순서와 복선을 보존하는지 비교합니다.",
    maturity: "adapter",
    composesWith: ["publish pack", "platform validator", "timeline"],
    guardrail: "변형 출력은 원본 장면 그래프를 참조하며 독자 공개 순서를 재검증합니다.",
    evidence: ["destination spec", "reveal order", "layout diff"],
  },
  {
    id: "rights-consent-ledger",
    group: "trust-collaboration",
    name: "권리·동의 원장",
    oneLine: "자산 리비전별 라이선스·초상 동의·만료·철회 상태를 장면 영향과 연결합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "권리 상태가 불명확하면 승인으로 추정하지 않습니다.",
    evidence: ["rights-risk", "asset revision", "affected scene"],
  },
  {
    id: "creative-proof-receipt",
    group: "trust-collaboration",
    name: "창작 근거 영수증",
    oneLine: "입력 해시·문제 해시·축별 점수·버전을 결정적으로 묶어 리뷰와 회귀 비교에 사용합니다.",
    maturity: "engine",
    engineEntry: "fingerprintStoryworldValue",
    guardrail: "간단한 해시는 무결성 지문이며 전자서명이나 법적 증명으로 오표시하지 않습니다.",
    evidence: ["projectFingerprint", "issueFingerprint", "schema version"],
  },
  {
    id: "explainable-repair-intents",
    group: "trust-collaboration",
    name: "설명 가능한 수선 제안",
    oneLine: "문제를 고치는 최소 변경을 실행 코드가 아닌 검토 가능한 중립 intent로 반환합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "제안은 자동 적용되지 않으며 원본·이유·위험도를 함께 표시합니다.",
    evidence: ["issueId", "rationale", "risk", "intent"],
  },
  {
    id: "canon-branch-merge",
    group: "trust-collaboration",
    name: "캐논 분기 병합",
    oneLine: "두 작가 브랜치의 픽셀 충돌뿐 아니라 사실·지식·공개 시점 충돌을 의미 단위로 보여줍니다.",
    maturity: "adapter",
    composesWith: ["CRDT", "version history", "storyworld receipt"],
    guardrail: "의미 충돌은 last-write-wins로 자동 해소하지 않습니다.",
    evidence: ["base receipt", "branch receipts", "semantic conflicts"],
  },
  {
    id: "review-proof-obligations",
    group: "trust-collaboration",
    name: "검토 증명 의무",
    oneLine: "중요한 전제·권리·접근성·게시 규칙마다 누가 어떤 근거로 승인했는지 연결합니다.",
    maturity: "adapter",
    composesWith: ["comments", "roles", "publish gate"],
    guardrail: "승인자가 없는 항목을 자동 승인하지 않고 게시 차단 또는 명시적 예외 영수증을 요구합니다.",
    evidence: ["obligation id", "reviewer", "evidence link", "exception receipt"],
  },
  {
    id: "privacy-safe-writers-room",
    group: "trust-collaboration",
    name: "프라이버시 안전 작가실",
    oneLine: "AI·외부 도구로 보내는 컨텍스트에서 미선택 장면·비밀·개인 메모를 구조적으로 제외합니다.",
    maturity: "adapter",
    composesWith: ["provider routing", "permissions", "knowledge matrix"],
    guardrail: "전송 범위·비용·보존 정책을 실행 전에 표시하고 취소 시 문서를 불변으로 유지합니다.",
    evidence: ["context manifest", "provider", "retention policy", "receipt"],
  },
  {
    id: "premise-inversion-lab",
    group: "world-model",
    name: "전제 뒤집기 연구실",
    oneLine: "작품의 핵심 사실 하나를 반대로 바꿨을 때 살아남는 장면과 새로 필요한 증거를 보여줍니다.",
    maturity: "engine",
    engineEntry: "simulateStoryworldCounterfactual",
    guardrail: "결과를 ‘더 좋은 이야기’로 단정하지 않고 영향 범위와 품질 축 차이만 제시합니다.",
    evidence: ["set-fact mutation", "impact cone", "axis delta"],
  },
  {
    id: "dream-flashback-topology",
    group: "narrative-contract",
    name: "꿈·회상 위상 지도",
    oneLine: "현재·회상·꿈·가상 장면의 사실 효력과 독자 공개 효력을 서로 다른 층으로 관리합니다.",
    maturity: "experimental",
    composesWith: ["timeline", "caption style", "canon state"],
    guardrail: "꿈속 효과를 현실 캐논 상태에 자동 반영하지 않습니다.",
    evidence: ["reality layer", "fact scope", "transition marker"],
  },
  {
    id: "sound-meaning-continuity",
    group: "reader-experience",
    name: "소리 의미 연속성",
    oneLine: "효과음·무음·진동·음성 연출이 시각 대체와 함께 같은 서사 의미를 전달하는지 검사합니다.",
    maturity: "adapter",
    composesWith: ["SFX lexicon", "audio timeline", "accessibility layer"],
    guardrail: "청각 연출만으로 필수 사실을 전달하지 않도록 대체 단서를 요구합니다.",
    evidence: ["audio cue", "visual cue", "fact reveal"],
  },
  {
    id: "release-risk-radar",
    group: "global-release",
    name: "릴리스 위험 레이더",
    oneLine: "권리·접근성·번역·플랫폼 규격·미회수 약속을 게시 전 하나의 근거 묶음으로 집계합니다.",
    maturity: "adapter",
    composesWith: ["publish preflight", "quality inspector", "storyworld receipt"],
    guardrail: "정책 날짜와 출처를 고정하고 최신 규칙 확인에 실패하면 통과로 간주하지 않습니다.",
    evidence: ["policy source", "checkedAt", "blocking issues", "exception receipt"],
  },
  {
    id: "prop-lifecycle-ledger",
    group: "world-model",
    name: "소품 생애 원장",
    oneLine: "열쇠·상처·무기·편지처럼 이동하고 손상되는 소품의 소유자와 상태를 장면별로 실행합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "화면 인식으로 상태를 추측하지 않고 등록된 사실과 장면 효과만 사용합니다.",
    evidence: ["subject fact", "worldTimeline", "precondition"],
  },
  {
    id: "wardrobe-continuity",
    group: "world-model",
    name: "의상·상처 연속성",
    oneLine: "의상 리비전, 오염, 파손, 헤어와 상처 상태가 컷 사이에서 갑자기 되돌아가는지 검사합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "의도적 변신·시간 점프는 명시한 전환 장면으로 예외 처리합니다.",
    evidence: ["character appearance facts", "timeIndex", "contradicted-precondition"],
  },
  {
    id: "environment-memory",
    group: "world-model",
    name: "배경의 기억",
    oneLine: "날씨·조명·파손·문 개폐·군중 상태가 인물이 떠난 뒤에도 세계에 남도록 추적합니다.",
    maturity: "engine",
    engineEntry: "analyzeStoryworldProject",
    guardrail: "장면을 바꾸면 배경이 초기화된다고 가정하지 않습니다.",
    evidence: ["location facts", "persistent world state", "scene effects"],
  },
  {
    id: "inference-distance-map",
    group: "character-intelligence",
    name: "추론 거리 지도",
    oneLine: "인물이 직접 들은 사실과 여러 단서를 조합해 추론한 사실을 구분하고 추론 단계를 시각화합니다.",
    maturity: "experimental",
    composesWith: ["belief matrix", "dialogue", "AI verifier"],
    guardrail: "추론 가능성을 사실 습득으로 자동 확정하지 않고 작가 승인과 근거 연결을 요구합니다.",
    evidence: ["premise facts", "inference rule", "confidence", "approval"],
  },
  {
    id: "reader-memory-decay",
    group: "reader-experience",
    name: "독자 기억 감쇠 시뮬레이터",
    oneLine: "회차 간 공백과 정보 밀도를 반영해 어떤 사실을 독자가 잊었을 가능성이 큰지 리캡 후보로 표시합니다.",
    maturity: "experimental",
    composesWith: ["reader reveal", "release calendar", "adaptive recap"],
    guardrail: "개별 독자의 실제 기억으로 오표시하지 않고 선택 가능한 휴리스틱 프로필로만 제공합니다.",
    evidence: ["reveal order", "elapsed release time", "information density", "profile"],
  },
  {
    id: "revelation-choreographer",
    group: "narrative-contract",
    name: "폭로 안무가",
    oneLine: "같은 사실을 표정·소품·대사·효과음 중 어디에서 먼저 보일지 채널별 공개 순서로 설계합니다.",
    maturity: "adapter",
    composesWith: ["layer graph", "dialogue", "SFX", "reader reveal"],
    guardrail: "장면의 공개 계약을 어긴 채널만 경고하고 표현 수단을 하나로 강제하지 않습니다.",
    evidence: ["channel reveal", "fact id", "reader order", "panel link"],
  },
  {
    id: "causal-canvas-overlay",
    group: "reader-experience",
    name: "캔버스 인과 오버레이",
    oneLine: "캔버스의 소품·말풍선·컷을 선택하면 그 요소가 성립시키거나 소비하는 사실과 후속 장면을 표시합니다.",
    maturity: "adapter",
    composesWith: ["canvas selection", "panel graph", "impact cone"],
    guardrail: "오버레이는 편집 대상과 분리된 검토 레이어이며 출력 파일에는 포함되지 않습니다.",
    evidence: ["element id", "fact links", "dependent scenes"],
  },
  {
    id: "narrative-regression-suite",
    group: "trust-collaboration",
    name: "서사 회귀 테스트",
    oneLine: "중요 장면의 전제·공개·권리·접근성 기대값을 테스트로 저장해 리라이트가 깨뜨린 계약을 즉시 찾습니다.",
    maturity: "engine",
    engineEntry: "fingerprintStoryworldValue",
    guardrail: "텍스트 표현 자체를 고정하지 않고 의미 계약과 결과 지문만 비교합니다.",
    evidence: ["proof receipt", "expected issue set", "axis threshold", "fixture"],
  },
  {
    id: "canon-lock-token",
    group: "trust-collaboration",
    name: "캐논 잠금 토큰",
    oneLine: "시즌 결말·정체·권리 고지 같은 핵심 사실을 변경할 때 지정 리뷰어의 의미 단위 승인을 요구합니다.",
    maturity: "adapter",
    composesWith: ["roles", "semantic diff", "version history"],
    guardrail: "일상 편집을 잠그지 않고 작가가 지정한 사실과 범위에만 적용합니다.",
    evidence: ["fact id", "lock scope", "reviewer", "approval receipt"],
  },
  {
    id: "branch-budget-pruner",
    group: "production-operations",
    name: "분기 예산 가지치기",
    oneLine: "수십 개 가상 전개 중 품질·제작비·권리 위험에서 명백히 지배되는 분기만 접어 탐색 공간을 줄입니다.",
    maturity: "adapter",
    composesWith: ["Pareto frontier", "production twin", "rights ledger"],
    guardrail: "숨겨진 미학 점수로 삭제하지 않고 접힌 후보와 지배 근거를 언제든 다시 볼 수 있게 합니다.",
    evidence: ["dominatedByIds", "cost axes", "restore branch"],
  },
  {
    id: "emotional-color-script",
    group: "narrative-contract",
    name: "감정·색채 스크립트 동기화",
    oneLine: "인물 감정 곡선과 팔레트·명암·카메라 거리 변화를 겹쳐 의도하지 않은 연출 역행을 찾습니다.",
    maturity: "adapter",
    composesWith: ["emotional beats", "palette", "camera", "lighting"],
    guardrail: "색을 감정의 보편적 정답으로 해석하지 않고 작품이 선언한 색채 문법만 검사합니다.",
    evidence: ["emotion curve", "palette key", "shot distance", "declared grammar"],
  },
  {
    id: "live-table-read",
    group: "character-intelligence",
    name: "라이브 테이블 리드",
    oneLine: "인물별 지식 상태를 잠근 채 대사를 순서대로 읽어 말할 수 없는 정보와 감정 전환을 실시간 표시합니다.",
    maturity: "adapter",
    composesWith: ["voice preview", "dialogue timeline", "belief matrix"],
    guardrail: "음성 합성은 선택한 대사만 처리하며 배우·사용자 음성 복제에는 명시적 동의를 요구합니다.",
    evidence: ["line id", "speaker knowledge", "emotion transition", "voice consent"],
  },
] as const;

export function storyworldCapabilitiesByGroup(
  group: StoryworldCapabilityGroup,
): readonly StoryworldCapability[] {
  return STORYWORLD_CAPABILITIES.filter((capability) => capability.group === group);
}

export function storyworldCapabilityCounts(): Readonly<Record<StoryworldCapabilityMaturity, number>> {
  return STORYWORLD_CAPABILITIES.reduce<Record<StoryworldCapabilityMaturity, number>>(
    (counts, capability) => {
      counts[capability.maturity] += 1;
      return counts;
    },
    { engine: 0, adapter: 0, experimental: 0 },
  );
}
