/** Link-only sources are deliberately NOT represented as working integrations. */
export const RESOURCE_SOURCES = [
  { name: "The Met", category: "창작 자료", status: "검색 어댑터 구현", url: "https://metmuseum.github.io/", note: "키 없는 검색. v1.1 페이지 조회, 공개 이용 여부 확인, 미리보기와 출처 저장. 배포 후 실제 연결 확인이 필요합니다." },
  { name: "카카오 책 검색", category: "작품 탐색", status: "서버 인증키 필요", url: "https://developers.kakao.com/docs/ko/daum-search/dev-guide", note: "도서 메타데이터 어댑터 구현. 카카오웹툰 전용 API가 아닙니다. KAKAO_REST_API_KEY가 없으면 검색 연결 대기로 표시합니다." },
  { name: "기업마당", category: "창작 기회", status: "서버 인증키 필요", url: "https://www.bizinfo.go.kr/apiDetail.do?id=bizinfoApi", note: "지원사업 어댑터 구현. BIZINFO_API_KEY 필요. 최근 최대 100건 검색이며 전체 공모전 목록이 아닙니다." },
  { name: "만화규장각 KMAS", category: "작품 탐색", status: "기존 기능 재사용", url: "https://www.kmas.or.kr/guide/openapi", note: "기존 작품 검색과 카탈로그를 사용합니다. 새로운 카탈로그를 중복 생성하지 않습니다." },
  { name: "문화포털 전통문양", category: "창작 자료", status: "공식 링크만 제공", url: "https://www.culture.go.kr/tradition/", note: "전통문양과 원본 이용 절차를 확인하세요. 자동 원본 다운로드·대량 에셋 수집은 구현하지 않았습니다." },
  { name: "공유마당", category: "창작 자료", status: "공식 링크만 제공", url: "https://gongu.copyright.or.kr/", note: "저작물별 이용조건과 원문 제공 범위를 확인하세요. 번역문·삽화의 권리를 원작과 동일하게 간주하지 않습니다." },
  { name: "Openverse", category: "창작 자료", status: "권리 검수 절차 필요", url: "https://openverse.org/", note: "검색 결과의 라이선스는 원제공처에서 다시 확인해야 합니다. 현재 자동 수집·미리보기 연동은 하지 않습니다." },
  { name: "한국콘텐츠진흥원", category: "창작 기회", status: "공식 링크만 제공", url: "https://www.kocca.kr/", note: "지원사업·공지를 원문에서 확인하세요. RSS 수집과 마감 알림 자동 전송은 아직 연결하지 않았습니다." },
  { name: "K-Startup", category: "창작 기회", status: "공식 링크만 제공", url: "https://www.k-startup.go.kr/", note: "사업자·예비창업자 조건을 확인하세요. 개인 작가 공모전과 사업 지원을 동일하게 취급하지 않습니다." },
  { name: "국립중앙도서관", category: "작품 탐색", status: "공식 링크만 제공", url: "https://www.nl.go.kr/", note: "ISBN 서지정보 보강 후보입니다. 인증과 판본 매칭 검증 전에는 작품 관계를 자동 추정하지 않습니다." },
  { name: "도서관 정보나루", category: "통계", status: "공식 링크만 제공", url: "https://www.data4library.kr/", note: "대출 기반 지표는 플랫폼 조회수·매출과 다릅니다. 통계 수집은 아직 연결하지 않았습니다." },
  { name: "KOSIS", category: "통계", status: "공식 링크만 제공", url: "https://kosis.kr/", note: "조사연도, 발표일, 단위와 표본을 함께 확인하세요. 실시간 작품 인기 순위로 표시하지 않습니다." },
  { name: "Google Books", category: "작품 탐색", status: "공식 링크만 제공", url: "https://developers.google.com/books/docs/v1/using", note: "해외 도서 보강 후보입니다. 키·쿼터·미리보기 정책 확인 후 별도 어댑터가 필요합니다." },
  { name: "Open Library", category: "작품 탐색", status: "공식 링크만 제공", url: "https://openlibrary.org/developers/api", note: "저용량 검색과 대량 카탈로그의 이용 방식을 구분해야 합니다. 상시 미러링을 추가하지 않았습니다." },
  { name: "AniList", category: "작품 탐색", status: "상업 이용 검토 필요", url: "https://docs.anilist.co/guide/terms-of-use", note: "상업 이용, 경쟁 서비스와 대량 수집 제한을 확인해야 합니다. 검토 없이 연동하지 않습니다." },
  { name: "TMDB", category: "작품 탐색", status: "상업 이용 검토 필요", url: "https://developer.themoviedb.org/docs/faq", note: "상업 라이선스와 원작 관계 검증이 선행되어야 합니다. 웹툰과 영상의 관계를 추측해 연결하지 않습니다." },
  { name: "YouTube Data API", category: "학습", status: "공식 링크만 제공", url: "https://developers.google.com/youtube/v3", note: "공식 영상 큐레이션 후보입니다. 영상 파일 수집·재편집·재배포는 하지 않습니다." },
  { name: "AI Hub", category: "데이터셋", status: "별도 신청·용도 검토", url: "https://www.aihub.or.kr/", note: "데이터셋은 완성 이미지를 반환하는 생성 API가 아닙니다. 학습 목적과 에셋 재배포 권한을 별도로 검토해야 합니다." },
  { name: "Jikan·비공식 웹툰 API", category: "작품 탐색", status: "핵심 연동에서 제외", url: "https://jikan.moe/", note: "비공식 수집원의 안정성과 권리 범위를 확인하기 전에는 상용 서비스의 핵심 데이터로 사용하지 않습니다." },
  { name: "알라딘 OpenAPI", category: "작품 탐색", status: "신규 연동 제외", url: "https://www.aladin.co.kr/home/welcome.aspx", note: "공식 사이트의 서비스 종료 공지를 확인하세요. 이번 변경에서는 새 의존성을 추가하지 않았습니다." },
  { name: "네이버 책 검색", category: "작품 탐색", status: "신규 연동 제외", url: "https://developers.naver.com/", note: "이관·종료 관련 공식 공지를 확인하세요. 이번 변경에서는 새 의존성을 추가하지 않았습니다." },
];
