/* Extracted render tree from StudioCuttoonEditor.
 * Session props are an `any` bag matching the original editor closure. */
// @ts-nocheck
"use no memo";
// React Compiler 옵트아웃: 가변 호스트 백(h) 을 렌더마다 재대입해 공유하는 추출 패턴이라,
// 컴파일러가 h 참조 동일성만 보고 JSX/계산을 캐시하면 첫 렌더에서 UI 가 영구 동결된다
// (탭 전환 등 커밋된 상태 변경이 화면에 반영되지 않음).
import { StudioLazyPanelStack } from "../StudioLazyPanelStack";
import type { StudioCuttoonEditorViewSession } from "./StudioCuttoonEditorViewSession";

export function StudioCuttoonEditorPanels(s: StudioCuttoonEditorViewSession) {
  const {
    activeCommentAnchor,
    activePage,
    admittedBg3dOpen,
    admittedCharacterShaperOpen,
    admittedMannequinPoserOpen,
    admittedPoserVrmOpen,
    aiProvenance,
    aiProvenanceOpen,
    aiSettings,
    assetsLoaded,
    assetsLoading,
    autoActionBusy,
    autoActionError,
    autoActionPlan,
    autoActionProgress,
    autoActionScope,
    autoActionSelectedPageIds,
    autoActionSet,
    autoActionStatus,
    autoActionsOpen,
    bg3dBatchRecoveryScope,
    bg3dInitialDataUrl,
    bg3dInitialElementId,
    bg3dInitialScene,
    bg3dSeedPrimitiveKind,
    bg3dSeedTemplateId,
    bg3dTargetBundleId,
    characterBible,
    characterBibleOpen,
    checkpointError,
    checkpointPanelOpen,
    checkpoints,
    clearStudioObjectInsertSeeds,
    collaborationDocumentLocked,
    colorWheelCenter,
    colorWheelOpen,
    commentsOpen,
    commentsPanelMounted,
    composeWorkAssetPreviewPage,
    continuityIssues,
    continuityOpen,
    continuityScenes,
    currentPageId,
    currentPublishPackageCreditsText,
    draftCollaboration,
    effectivePublishPackageSettings,
    elementById,
    fxPanelOpen,
    isMobile,
    isStudioCommentAnchorValid,
    loadedWork,
    loggedIn,
    macroSession,
    masterEditMode,
    pageDnd,
    pageReviewOpen,
    pages,
    pagesHi,
    pagesHistory,
    poserInitialDataUrl,
    poserInitialElementId,
    poserSeedPropId,
    productionInsightsOpen,
    productionInsightsResult,
    publicationAnalytics,
    publicationOperationsOpen,
    publishAiDisclosure,
    publishAiUsage,
    publishCompliance,
    publishComplianceResult,
    publishPackageExportBusy,
    publishPackageExportProgress,
    publishPackageExportStatus,
    publishPackageOpen,
    publishPackagePlan,
    publishPreflightOpen,
    publishPreflightResult,
    publishProfile,
    quickActionsAnchor,
    quickActionsDisabledActions,
    quickActionsOpen,
    quickActionsPreferences,
    recentColors,
    referenceBoard,
    referencePanelOpen,
    releaseSchedule,
    scenarioApplyTarget,
    scenarioBusy,
    scenarioError,
    scenarioImageReferenceAssetOptions,
    scenarioImageReferenceDocument,
    scenarioImageReferenceResolution,
    scenarioOpen,
    scenarioProgress,
    scenarioRegeneratingIndex,
    scenarioResult,
    scenarioSceneCountHint,
    scenarioStageLabel,
    scenarioStoryText,
    scrollPreviewOpen,
    serverCurrentRevision,
    serverRevisionError,
    serverRevisionLoading,
    serverRevisions,
    setAiProvenanceOpen,
    setAutoActionsOpen,
    setBg3dInitialDataUrl,
    setBg3dInitialElementId,
    setBg3dInitialScene,
    setBg3dOpen,
    setCharacterBibleOpen,
    setCheckpointPanelOpen,
    setColor,
    setColorWheelOpen,
    setCommentsOpen,
    setContinuityOpen,
    setFxPanelOpen,
    setFollowingStudioSessionId,
    setLoadedWork,
    setCharacterShaperOpen,
    setMannequinPoserOpen,
    setPageReviewOpen,
    setPoserInitialDataUrl,
    setPoserInitialElementId,
    setPoserVrmOpen,
    setProductionInsightsOpen,
    setPublicationOperationsOpen,
    setPublishPackageOpen,
    setPublishPreflightOpen,
    setQuickActionsOpen,
    setQuickActionsPreferences,
    setReferencePanelOpen,
    setScenarioImageReferenceDocument,
    setScenarioOpen,
    setScenarioSceneCountHint,
    setScenarioStoryText,
    setScrollPreviewOpen,
    setSelectedId,
    setSharedDocumentNotice,
    setSharedDocumentScope,
    setStoryboardGridOpen,
    setStudioCommentFocusRequest,
    setStudioCommentPinsHidden,
    setTeamPanelOpen,
    setTimelapseOpen,
    setTool,
    setWriterRoomAiDirection,
    setWriterRoomAiReview,
    setWriterRoomOpen,
    sharedDocument,
    startStudioCommentPlacementSession,
    storyboardGridOpen,
    studioAuthUserId,
    studioCommentActor,
    studioCommentAnchorOptions,
    studioCommentFocusRequest,
    studioCommentInteractionNotice,
    studioCommentPinsHidden,
    studioCommentSharedReplyController,
    studioCommentSyncError,
    studioCommentViewDocument,
    studioLazyPanelStackHandlers,
    studioLegacyCommentThreadIdSet,
    studioRevisionProjectGenerationRef,
    studioTeamCommentCapabilities,
    studioTeamCommentsSyncing,
    studioTeamCommentsWorkId,
    studioTeamUnreadCommentIdSet,
    teamPanelOpen,
    followingStudioSessionId,
    textAiConfigured,
    timelapseOpen,
    title,
    validateRecoveryAccess,
    workId,
    writerRoom,
    writerRoomAiBusy,
    writerRoomAiDirection,
    writerRoomAiError,
    writerRoomAiReview,
    writerRoomCanvasPlan,
    writerRoomOpen,
  } = s;
  return (
        <StudioLazyPanelStack
          activeCommentAnchor={activeCommentAnchor}
          activePage={activePage}
          aiProvenance={aiProvenance}
          aiProvenanceOpen={aiProvenanceOpen}
          aiSettings={aiSettings}
          autoActionBusy={autoActionBusy}
          autoActionError={autoActionError}
          autoActionPlan={autoActionPlan}
          autoActionProgress={autoActionProgress}
          autoActionScope={autoActionScope}
          autoActionSelectedPageIds={autoActionSelectedPageIds}
          autoActionSet={autoActionSet}
          autoActionsOpen={autoActionsOpen}
          autoActionStatus={autoActionStatus}
          bg3dInitialDataUrl={bg3dInitialDataUrl}
          bg3dInitialScene={bg3dInitialScene}
          bg3dOperation={bg3dInitialElementId ? "update" : "insert"}
          bg3dTargetBundleId={bg3dTargetBundleId}
          bg3dBatchRecoveryScope={bg3dBatchRecoveryScope}
          validateRecoveryAccess={validateRecoveryAccess}
          bg3dOpen={admittedBg3dOpen}
          bg3dSeedTemplateId={bg3dSeedTemplateId}
          bg3dSeedPrimitiveKind={bg3dSeedPrimitiveKind}
          onSeedObjectInsertConsumed={clearStudioObjectInsertSeeds}
          characterBible={characterBible}
          characterBibleOpen={characterBibleOpen}
          checkpointError={checkpointError}
          checkpointPanelOpen={checkpointPanelOpen}
          checkpoints={checkpoints}
          collaborationDocumentLocked={collaborationDocumentLocked}
          colorWheelCenter={colorWheelCenter}
          colorWheelOpen={colorWheelOpen}
          commentsOpen={commentsOpen}
          commentsPanelMounted={commentsPanelMounted}
          studioCommentFocusRequest={studioCommentFocusRequest}
          studioCommentSharedReply={studioCommentSharedReplyController}
          studioCommentSyncError={studioCommentInteractionNotice ?? studioCommentSyncError}
          studioCommentPinsHidden={studioCommentPinsHidden}
          studioLegacyCommentThreadIdSet={studioLegacyCommentThreadIdSet}
          studioTeamCommentCapabilities={studioTeamCommentCapabilities}
          studioTeamCommentsSyncing={studioTeamCommentsSyncing}
          studioTeamCommentsWorkId={studioTeamCommentsWorkId}
          studioTeamUnreadCommentIdSet={studioTeamUnreadCommentIdSet}
          composeWorkAssetPreviewPage={composeWorkAssetPreviewPage}
          continuityIssues={continuityIssues}
          continuityOpen={continuityOpen}
          continuityScenes={continuityScenes}
          currentPageId={currentPageId}
          currentPublishPackageCreditsText={currentPublishPackageCreditsText}
          draftCollaboration={draftCollaboration}
          effectivePublishPackageSettings={effectivePublishPackageSettings}
          elementById={elementById}
          fxPanelOpen={fxPanelOpen}
          isMobile={isMobile}
          loadedWork={loadedWork}
          loggedIn={loggedIn}
          macroSession={macroSession}
          masterEditMode={masterEditMode}
          pageDnd={pageDnd}
          pageReviewOpen={pageReviewOpen}
          pages={pages}
          pagesHi={pagesHi}
          pagesHistory={pagesHistory}
          mannequinPoserOpen={admittedMannequinPoserOpen}
          poserInitialDataUrl={poserInitialDataUrl}
          poserInitialElementId={poserInitialElementId}
          poserSeedPropId={poserSeedPropId}
          poserVrmOpen={admittedPoserVrmOpen}
          characterShaperOpen={admittedCharacterShaperOpen}
          productionInsightsOpen={productionInsightsOpen}
          productionInsightsResult={productionInsightsResult}
          publicationAnalytics={publicationAnalytics}
          publicationOperationsOpen={publicationOperationsOpen}
          publishAiDisclosure={publishAiDisclosure}
          publishAiUsage={publishAiUsage}
          publishCompliance={publishCompliance}
          publishComplianceResult={publishComplianceResult}
          publishPackageExportBusy={publishPackageExportBusy}
          publishPackageExportProgress={publishPackageExportProgress}
          publishPackageExportStatus={publishPackageExportStatus}
          publishPackageOpen={publishPackageOpen}
          publishPackagePlan={publishPackagePlan}
          publishPreflightOpen={publishPreflightOpen}
          publishPreflightResult={publishPreflightResult}
          publishProfile={publishProfile}
          quickActionsAnchor={quickActionsAnchor}
          quickActionsDisabledActions={quickActionsDisabledActions}
          quickActionsOpen={quickActionsOpen}
          quickActionsPreferences={quickActionsPreferences}
          recentColors={recentColors}
          referencePanelOpen={referencePanelOpen}
          referenceBoard={referenceBoard}
          releaseSchedule={releaseSchedule}
          scenarioApplyTarget={scenarioApplyTarget}
          scenarioBusy={scenarioBusy}
          scenarioError={scenarioError}
          scenarioImageReferenceAssetOptions={scenarioImageReferenceAssetOptions}
          scenarioImageReferenceDocument={scenarioImageReferenceDocument}
          scenarioImageReferenceMissingCount={
            assetsLoaded ? scenarioImageReferenceResolution.missing.length : 0
          }
          scenarioImageReferencesLoading={assetsLoading || (scenarioOpen && !assetsLoaded)}
          scenarioOpen={scenarioOpen}
          scenarioProgress={scenarioProgress}
          scenarioRegeneratingIndex={scenarioRegeneratingIndex}
          scenarioResult={scenarioResult}
          scenarioSceneCountHint={scenarioSceneCountHint}
          scenarioStageLabel={scenarioStageLabel}
          scenarioStoryText={scenarioStoryText}
          scrollPreviewOpen={scrollPreviewOpen}
          serverCurrentRevision={serverCurrentRevision}
          serverRevisionError={serverRevisionError}
          serverRevisionLoading={serverRevisionLoading}
          serverRevisions={serverRevisions}
          setAiProvenanceOpen={setAiProvenanceOpen}
          setAutoActionsOpen={setAutoActionsOpen}
          setBg3dInitialDataUrl={setBg3dInitialDataUrl}
          setBg3dInitialElementId={setBg3dInitialElementId}
          setBg3dInitialScene={setBg3dInitialScene}
          setBg3dOpen={setBg3dOpen}
          setCharacterBibleOpen={setCharacterBibleOpen}
          setCheckpointPanelOpen={setCheckpointPanelOpen}
          setColor={setColor}
          setColorWheelOpen={setColorWheelOpen}
          onArmCommentPinPlacement={startStudioCommentPlacementSession}
          setCommentsOpen={setCommentsOpen}
          isStudioCommentAnchorValid={isStudioCommentAnchorValid}
          setStudioCommentFocusRequest={setStudioCommentFocusRequest}
          setStudioCommentPinsHidden={setStudioCommentPinsHidden}
          setContinuityOpen={setContinuityOpen}
          setFxPanelOpen={setFxPanelOpen}
          setFollowingStudioSessionId={setFollowingStudioSessionId}
          setLoadedWork={setLoadedWork}
          setPageReviewOpen={setPageReviewOpen}
          setPoserInitialDataUrl={setPoserInitialDataUrl}
          setMannequinPoserOpen={setMannequinPoserOpen}
          setPoserInitialElementId={setPoserInitialElementId}
          setPoserVrmOpen={setPoserVrmOpen}
          setCharacterShaperOpen={setCharacterShaperOpen}
          setProductionInsightsOpen={setProductionInsightsOpen}
          setPublicationOperationsOpen={setPublicationOperationsOpen}
          setPublishPackageOpen={setPublishPackageOpen}
          setPublishPreflightOpen={setPublishPreflightOpen}
          setQuickActionsOpen={setQuickActionsOpen}
          setQuickActionsPreferences={setQuickActionsPreferences}
          setReferencePanelOpen={setReferencePanelOpen}
          setScenarioOpen={setScenarioOpen}
          setScenarioImageReferenceDocument={setScenarioImageReferenceDocument}
          setScenarioSceneCountHint={setScenarioSceneCountHint}
          setScenarioStoryText={setScenarioStoryText}
          setScrollPreviewOpen={setScrollPreviewOpen}
          setSelectedId={setSelectedId}
          setSharedDocumentNotice={setSharedDocumentNotice}
          setSharedDocumentScope={setSharedDocumentScope}
          setStoryboardGridOpen={setStoryboardGridOpen}
          setTeamPanelOpen={setTeamPanelOpen}
          setTimelapseOpen={setTimelapseOpen}
          setTool={setTool}
          setWriterRoomAiDirection={setWriterRoomAiDirection}
          setWriterRoomAiReview={setWriterRoomAiReview}
          setWriterRoomOpen={setWriterRoomOpen}
          sharedDocument={sharedDocument}
          storyboardGridOpen={storyboardGridOpen}
          studioAuthUserId={studioAuthUserId}
          studioCommentActor={studioCommentActor}
          studioCommentAnchorOptions={studioCommentAnchorOptions}
          studioComments={studioCommentViewDocument}
          studioRevisionProjectGenerationRef={studioRevisionProjectGenerationRef}
          teamPanelOpen={teamPanelOpen}
          followingStudioSessionId={followingStudioSessionId}
          textAiConfigured={textAiConfigured}
          timelapseOpen={timelapseOpen}
          title={title}
          workId={workId}
          writerRoom={writerRoom}
          writerRoomAiBusy={writerRoomAiBusy}
          writerRoomAiDirection={writerRoomAiDirection}
          writerRoomAiError={writerRoomAiError}
          writerRoomAiReview={writerRoomAiReview}
          writerRoomCanvasPlan={writerRoomCanvasPlan}
          writerRoomOpen={writerRoomOpen}
          stableHandlers={studioLazyPanelStackHandlers}
        />
  );
}
