/* Extracted render tree from StudioCuttoonEditor.
 * Session props are an `any` bag matching the original editor closure. */
// @ts-nocheck
"use no memo";
// React Compiler 옵트아웃: 가변 호스트 백(h) 을 렌더마다 재대입해 공유하는 추출 패턴이라,
// 컴파일러가 h 참조 동일성만 보고 JSX/계산을 캐시하면 첫 렌더에서 UI 가 영구 동결된다
// (탭 전환 등 커밋된 상태 변경이 화면에 반영되지 않음).
import { SlidersHorizontal } from "lucide-react";
import { Suspense } from "react";
import { resolveStudioPaperGrainVisibleV1 } from "../brush/studio-paper-grain-visibility-v1";
import { hasActiveImageFilters } from "../render/studio-konva-filter-fields";
import { StudioEdgeRailButton } from "../studio-chrome-ui";
import { LazyStudioInspectorAside } from "../studio-inspector-aside-loader";
import { StudioInspectorAsideFallback } from "../studio-mobile-dock-presets";
import { STUDIO_MOBILE_EDITING_DOCK_UI } from "../studio-mobile-dock-presets-config";
import { StudioMobileEditingDock } from "../studio-mobile-editing-dock-loader";
import { studioPathBooleanUnavailableReason } from "../studio-path-boolean";
import { canRedoPixelSelectionHistory, canUndoPixelSelectionHistory } from "../studio-pixel-selection-session-history";
import { StudioPanelResizeHandle } from "../StudioPanelResizeHandle";
import type { El } from "../studio-element-model";
import type { StudioCuttoonEditorViewSession } from "./StudioCuttoonEditorViewSession";

export function StudioCuttoonEditorInspectorColumn(s: StudioCuttoonEditorViewSession) {
  const {
    activeCatalogBrush,
    activePage,
    activeSavedBrushId,
    activeSurfaceReviewLocked,
    advancedFillActive,
    advancedFillBusy,
    advancedFillPreview,
    advancedFillReferenceLayerCount,
    advancedFillSettings,
    advancedFillStatus,
    advancedFillUnsupportedReason,
    advancedFillVisibleRasterCount,
    advancedRulers,
    aiColorizeBusy,
    aiColorizeError,
    aiColorizePrompt,
    aiSettings,
    applyExtendedBlendMergeDown,
    applyPaperVectorRefinement,
    applyPathBooleanCombine,
    applyPixelSelectionHistoryCommand,
    autoColorCanvasSeedHit,
    autoColorCanvasSeedHits,
    autoColorPlanImageSizeRef,
    autoColorScribbleCanvasArmed,
    bgGrad,
    brush,
    brushBaselineController,
    brushCatalogSession,
    brushDynamics,
    brushManagerSheetRef,
    brushOpacity,
    bubbleAnchorPickActive,
    bubbleShapeArmed,
    bubbleShapeEditActive,
    bubbleShapeHandles,
    bubbleShapeSelectedPointIndex,
    cancelPaperVectorRefinement,
    canvasFlipH,
    canvasH,
    canvasRotation,
    changeStudioSymmetryType,
    collaborationDocumentLocked,
    color,
    colorBlindPreview,
    colorRangeFuzziness,
    colorRangePickActive,
    colorRangePreviewEnabled,
    colorRangeSamples,
    colorVisionSheetRef,
    commentPlacementActive,
    commitPixelSelectionState,
    commitQuickMask,
    commitSavedBrushProjection,
    cropAspect,
    cropBusy,
    cropRect,
    currentBrushSnapshot,
    currentPageId,
    currentTemplate,
    description,
    dodgeBurnActive,
    dodgeBurnBusy,
    dodgeBurnExposure,
    dodgeBurnHardness,
    dodgeBurnMode,
    dodgeBurnRadius,
    dodgeBurnRange,
    dodgeBurnSponge,
    drawMode,
    drawShape,
    drawSheetRef,
    drawingPaletteCancelEpoch,
    drawingPaletteLayout,
    effScale,
    effectFavoriteState,
    elementById,
    elements,
    enterQuickMask,
    eraseToIntersection,
    exitQuickMask,
    extendedBlendMode,
    extendedBlendOpacity,
    eyedropperActive,
    filterClipboard,
    filterMaskBusy,
    filterMaskHardness,
    filterMaskPaintActive,
    filterMaskPaintMode,
    filterMaskRadius,
    filterMaskStrength,
    gridSize,
    groups,
    healCloneAligned,
    healCloneBusy,
    healCloneHardness,
    healCloneOpacity,
    healCloneRadius,
    healCloneSourceAnchor,
    healCloneTool,
    history,
    historyBrushActive,
    historyBrushBusy,
    historyBrushHardness,
    historyBrushOpacity,
    historyBrushRadius,
    historyBrushSourceSrc,
    historyPanelOpen,
    inspectorLayout,
    invertQuickMask,
    isMobile,
    isometricAngleDeg,
    isometricCellSize,
    isometricGridActive,
    isometricOriginX,
    isometricOriginY,
    layerMaskBusy,
    layerMaskHardness,
    layerMaskPaintActive,
    layerMaskPaintMode,
    layerMaskRadius,
    layerMaskStrength,
    layerMergeBusy,
    layerNavigatorItems,
    layerSoloState,
    liquifyActive,
    liquifyBusy,
    liquifyMode,
    liquifyRadius,
    liquifyStrength,
    liveDraftShapeKind,
    localHiddenElementIds,
    magicResizeStrategy,
    marqueeIds,
    masterEditMode,
    menuFilterDisabled,
    mobileBrushDockButtonRef,
    mobileInspectorSnap,
    mobileKeyboardInset,
    mobileQuickActionsButton,
    mobileSelectionLocked,
    mobileSheet,
    nodeEditHandles,
    nodeEditTool,
    nodeSmoothStrength,
    pageGrade,
    pageGradeActive,
    pageGradePanelOpen,
    panelGutter,
    panelSplitActive,
    panelSplitHint,
    panelSplitRatio,
    paperGrainKind,
    paperVectorRefinementBusy,
    paperVectorRefinementUnavailableReason,
    pathBooleanBusy,
    perspectiveEyeLevelY,
    perspectiveLockHorizon,
    perspectiveRulerActive,
    pixelBrushRadius,
    pixelBusy,
    pixelCombine,
    pixelForceCircle,
    pixelMagneticLasso,
    pixelSel,
    pixelSelectionHistory,
    pixelTool,
    polyLassoSession,
    postCorrection,
    preserveCorners,
    pressureCurve,
    pressureMinSize,
    productBrushRepository,
    propsSheetRef,
    puppetWarpActive,
    puppetWarpBusy,
    puppetWarpPins,
    quickActionsOpen,
    quickMaskActive,
    quickMaskBrushMode,
    quickMaskHardness,
    quickMaskOpacity,
    quickMaskRadius,
    quickMaskTintColor,
    quickMaskTintOpacity,
    quickShapeActive,
    recentColors,
    refreshQuickMaskTint,
    resetPixelSelectionHistoryState,
    rightResize,
    runColorRangeApply,
    savedBrushes,
    saving,
    scrollViewportStore,
    selected,
    selectedBg3dEditSource,
    selectedBubbleTailGeometry,
    selectedContentMutationLocked,
    selectedId,
    selectedProjectedImageSource,
    selectedWorkAssetDestructiveEditReason,
    setAdvancedFillPreview,
    setAdvancedFillStatus,
    setAiColorizePrompt,
    setAlignmentGuidesVisible,
    setAutoColorCanvasSeedHit,
    setAutoColorCanvasSeedHits,
    setAutoColorScribbleCanvasArmed,
    setBg3dInitialDataUrl,
    setBg3dInitialElementId,
    setBg3dInitialScene,
    setBg3dOpen,
    setBrushDynamics,
    setBrushOpacity,
    setBubbleShapeEditActive,
    setColor,
    setColorBlindPreview,
    setColorRangeFuzziness,
    setColorRangePickActive,
    setColorRangePreviewEnabled,
    setColorRangeSamples,
    setCropAspect,
    setCropRect,
    setDodgeBurnExposure,
    setDodgeBurnHardness,
    setDodgeBurnMode,
    setDodgeBurnRadius,
    setDodgeBurnRange,
    setDodgeBurnSponge,
    setDrawMode,
    setDrawShape,
    setEraseToIntersection,
    setExtendedBlendMode,
    setExtendedBlendOpacity,
    setEyedropperActive,
    setFilterClipboard,
    setFilterMaskHardness,
    setFilterMaskPaintActive,
    setFilterMaskPaintMode,
    setFilterMaskRadius,
    setFilterMaskStrength,
    setGridSize,
    setHealCloneAligned,
    setHealCloneHardness,
    setHealCloneOpacity,
    setHealCloneRadius,
    setHealCloneTool,
    setHistoryBrushActive,
    setHistoryBrushHardness,
    setHistoryBrushOpacity,
    setHistoryBrushRadius,
    setHistoryBrushSourceIndex,
    setHistoryBrushSourceSrc,
    setHistoryPanelOpen,
    setLayerMaskHardness,
    setLayerMaskPaintActive,
    setLayerMaskPaintMode,
    setLayerMaskRadius,
    setLayerMaskStrength,
    setLiquifyMode,
    setLiquifyRadius,
    setLiquifyStrength,
    setMagicResizeStrategy,
    setMarqueeIds,
    setMenu,
    setMobileInspectorSnap,
    setMobileSheet,
    setNodeEditTool,
    setNodeSmoothStrength,
    setPageGradePanelOpen,
    setPanelSplitActive,
    setPanelSplitHint,
    setPanelSplitRatio,
    setPerspectiveRulerActive,
    setPixelBrushRadius,
    setPixelCombine,
    setPixelForceCircle,
    setPixelMagneticLasso,
    setPixelTool,
    setPoserInitialDataUrl,
    setPoserInitialElementId,
    setPoserVrmOpen,
    setPostCorrection,
    setPreserveCorners,
    setPressureCurve,
    setPressureMinSize,
    setPuppetWarpActive,
    setPuppetWarpPins,
    setQuickMaskBrushMode,
    setQuickMaskHardness,
    setQuickMaskOpacity,
    setQuickMaskRadius,
    setQuickMaskTintColor,
    setQuickMaskTintOpacity,
    setQuickShapeActive,
    setQuickStartOpen,
    setRightPanelOpenWithOverride,
    setSelectedId,
    setShapeFill,
    setSharedDocumentNotice,
    setShowGrid,
    setShowWebtoonGuides,
    setSmudgeRadius,
    setSmudgeStrength,
    setSnapEnabledVisible,
    setStabilizer,
    setStabilizerMode,
    setStampTuning,
    setStrokeWidth,
    setSymmetryCenterX,
    setSymmetryCenterY,
    setSymmetryRadialCount,
    setTiltEnabled,
    setTipAngle,
    setTipRoundness,
    setTool,
    setUseVelocityPressure,
    setUserGuides,
    setVelocitySensitivity,
    setWandTolerance,
    setWetMixHardness,
    setWetMixPickup,
    setWetMixRadius,
    setWetMixStrength,
    setWetMixWetness,
    setZoom,
    shapeFill,
    showAlignmentGuides,
    showGrid,
    showMobileHint,
    showWebtoonGuides,
    smudgeActive,
    smudgeBusy,
    smudgeRadius,
    smudgeStrength,
    snapEnabled,
    stabilizer,
    stabilizerMode,
    stampTuning,
    strokeWidth,
    studioBrushCatalogHandlers,
    studioFilterPreparationBusy,
    studioFilterTargetLabel,
    studioFilterUnavailableReason,
    studioHistorySidecarRedoAvailable,
    studioHistorySidecarUndoAvailable,
    studioInspectorAsideHandlers,
    studioLayerLiftDisabledReason,
    studioMobileEditingDockHandlers,
    studioOptionsBarsDrawModel,
    studioOptionsBarsHandlers,
    studioOptionsBarsSelectionModel,
    symmetryCenterX,
    symmetryCenterY,
    symmetryRadialCount,
    symmetryType,
    tagsText,
    tiltEnabled,
    timelinePlaying,
    tipAngle,
    tipRoundness,
    title,
    titleInputRef,
    pendingSaveIntent,
    onContinuePendingSave,
    onClearWorkMetadataError,
    tool,
    useVelocityPressure,
    userGuides,
    vanishingPoints,
    velocitySensitivity,
    wandTolerance,
    webtoonGuides,
    webtoonTheme,
    wetMixActive,
    wetMixBusy,
    wetMixHardness,
    wetMixPickup,
    wetMixRadius,
    wetMixStrength,
    wetMixWetness,
    workspaceState,
    zoom,
    bg,
    hi,
    presentationPanelsHidden,
    proDrawPrefs,
    visibleRightPanelOpen,
  } = s;
  return (
    <>
        {/* 캔버스 ↔ 작업 패널 너비 스플리터(데스크톱) */}
        {visibleRightPanelOpen && (
          <StudioPanelResizeHandle handleProps={rightResize.handleProps} dragging={rightResize.dragging} label="작업 패널 너비 조절" />
        )}

        {/* 사이드: 작업 패널(대상·레이어·문서) + 게시 — 접히면 아이콘 엣지 레일 */}
        {!visibleRightPanelOpen && !presentationPanelsHidden && (
          <StudioEdgeRailButton
            side="right"
            // 이 레일이 되돌리는 패널은 스스로를 "작업 패널"이라고 부른다
            // (`StudioInspectorNavigator` COPY.panelTitle, `StudioInspectorAsideShell`
            // 의 "작업 패널 접기"). 레일의 접근 이름은 `${label} 펼치기` 로 만들어지므로
            // 라벨을 줄여 쓰면 접기/펼치기 짝이 서로 다른 이름을 갖게 된다.
            label="작업 패널"
            icon={SlidersHorizontal}
            onClick={() => setRightPanelOpenWithOverride(true)}
            title="작업 패널 펼치기"
          />
        )}
        {!isMobile || mobileSheet === "props" ? (
          <Suspense
            fallback={(
              <StudioInspectorAsideFallback
                isMobile={isMobile}
                keyboardInset={mobileKeyboardInset}
                propsSheetRef={propsSheetRef}
                snap={mobileInspectorSnap}
                visible={visibleRightPanelOpen}
                width={rightResize.width}
              />
            )}
          >
          <LazyStudioInspectorAside
          activeSavedBrushId={activeSavedBrushId}
          advancedRulers={advancedRulers}
          activeSurfaceReviewLocked={activeSurfaceReviewLocked}
          advancedFillActive={advancedFillActive}
          advancedFillBusy={advancedFillBusy}
          advancedFillPreview={advancedFillPreview}
          advancedFillReferenceLayerCount={advancedFillReferenceLayerCount}
          advancedFillSettings={advancedFillSettings}
          advancedFillStatus={advancedFillStatus}
          advancedFillUnsupportedReason={advancedFillUnsupportedReason}
          advancedFillVisibleRasterCount={advancedFillVisibleRasterCount}
          aiColorizeBusy={aiColorizeBusy}
          aiColorizeError={aiColorizeError}
          aiColorizePrompt={aiColorizePrompt}
          aiSettings={aiSettings}
          bg={bg}
          bgGrad={bgGrad}
          brush={brush}
          brushDynamics={brushDynamics}
          brushOpacity={brushOpacity}
          bubbleAnchorPickActive={bubbleAnchorPickActive}
          bubbleShapeArmed={bubbleShapeArmed}
          bubbleShapeEditActive={bubbleShapeEditActive}
          bubbleShapeHandles={bubbleShapeHandles}
          bubbleShapeSelectedPointIndex={bubbleShapeSelectedPointIndex}
          canvasFlipH={canvasFlipH}
          canvasH={canvasH}
          canvasRotation={canvasRotation}
          collaborationDocumentLocked={collaborationDocumentLocked}
          paperGrainKind={paperGrainKind}
          paperGrainVisible={resolveStudioPaperGrainVisibleV1(activePage)}
          color={color}
          colorRangeFuzziness={colorRangeFuzziness}
          colorRangePickActive={colorRangePickActive}
          colorRangePreviewEnabled={colorRangePreviewEnabled}
          colorRangeSamples={colorRangeSamples}
          quickMaskActive={quickMaskActive}
          quickMaskBrushMode={quickMaskBrushMode}
          quickMaskHardness={quickMaskHardness}
          quickMaskOpacity={quickMaskOpacity}
          quickMaskRadius={quickMaskRadius}
          quickMaskTintColor={quickMaskTintColor}
          quickMaskTintOpacity={quickMaskTintOpacity}
          enterQuickMask={enterQuickMask}
          commitQuickMask={commitQuickMask}
          exitQuickMask={exitQuickMask}
          invertQuickMask={invertQuickMask}
          onQuickMaskTintColorChange={(c) => {
            setQuickMaskTintColor(c);
            refreshQuickMaskTint(c, quickMaskTintOpacity);
          }}
          onQuickMaskTintOpacityChange={(v) => {
            setQuickMaskTintOpacity(v);
            refreshQuickMaskTint(quickMaskTintColor, v);
          }}
          setQuickMaskBrushMode={setQuickMaskBrushMode}
          setQuickMaskRadius={setQuickMaskRadius}
          setQuickMaskHardness={setQuickMaskHardness}
          setQuickMaskOpacity={setQuickMaskOpacity}
          cropAspect={cropAspect}
          cropBusy={cropBusy}
          cropRect={cropRect}
          currentBrushSnapshot={currentBrushSnapshot}
          currentPageId={currentPageId}
          currentTemplate={currentTemplate}
          description={description}
          drawMode={drawMode}
          drawShape={drawShape}
          drawingPaletteCancelEpoch={drawingPaletteCancelEpoch}
          drawingPaletteLayout={drawingPaletteLayout}
          effectFavoriteState={effectFavoriteState}
          effScale={effScale}
          elementById={elementById}
          elements={elements}
          eyedropperActive={eyedropperActive}
          filterClipboard={filterClipboard}
          gridSize={gridSize}
          groups={groups}
          healCloneAligned={healCloneAligned}
          healCloneBusy={healCloneBusy}
          healCloneHardness={healCloneHardness}
          healCloneOpacity={healCloneOpacity}
          healCloneRadius={healCloneRadius}
          healCloneSourceAnchor={healCloneSourceAnchor}
          healCloneTool={healCloneTool}
          historyBrushActive={historyBrushActive}
          historyBrushBusy={historyBrushBusy}
          historyBrushHardness={historyBrushHardness}
          historyBrushOpacity={historyBrushOpacity}
          historyBrushRadius={historyBrushRadius}
          historyBrushSourceSrc={historyBrushSourceSrc}
          historyPanelOpen={historyPanelOpen}
          inspectorLayout={inspectorLayout}
          isMobile={isMobile}
          isometricAngleDeg={isometricAngleDeg}
          isometricCellSize={isometricCellSize}
          isometricGridActive={isometricGridActive}
          isometricOriginX={isometricOriginX}
          isometricOriginY={isometricOriginY}
          filterMaskBusy={filterMaskBusy}
          filterMaskHardness={filterMaskHardness}
          filterMaskPaintActive={filterMaskPaintActive}
          filterMaskPaintMode={filterMaskPaintMode}
          filterMaskRadius={filterMaskRadius}
          filterMaskStrength={filterMaskStrength}
          selectedImageHasActiveFilters={
            selected?.type === "image" ? hasActiveImageFilters(selected) : false
          }
          layerMaskBusy={layerMaskBusy}
          layerMaskHardness={layerMaskHardness}
          layerMaskPaintActive={layerMaskPaintActive}
          layerMaskPaintMode={layerMaskPaintMode}
          layerMaskRadius={layerMaskRadius}
          layerMaskStrength={layerMaskStrength}
          layerNavigatorItems={layerNavigatorItems}
          localHiddenElementIds={localHiddenElementIds}
          soloLayerId={layerSoloState.soloId}
          liquifyActive={liquifyActive}
          liquifyBusy={liquifyBusy}
          liquifyMode={liquifyMode}
          liquifyRadius={liquifyRadius}
          liquifyStrength={liquifyStrength}
          liveDraftShapeKind={liveDraftShapeKind}
          magicResizeStrategy={magicResizeStrategy}
          marqueeIds={marqueeIds}
          masterEditMode={masterEditMode}
          mobileKeyboardInset={mobileKeyboardInset}
          mobileInspectorSnap={mobileInspectorSnap}
          mobileSheet={mobileSheet}
          nodeEditHandles={nodeEditHandles}
          nodeEditTool={nodeEditTool}
          nodeSmoothStrength={nodeSmoothStrength}
          pageGrade={pageGrade}
          pageGradeActive={pageGradeActive}
          pageGradePanelOpen={pageGradePanelOpen}
          panelGutter={panelGutter}
          panelSplitActive={panelSplitActive}
          panelSplitHint={panelSplitHint}
          panelSplitRatio={panelSplitRatio}
          perspectiveRulerActive={perspectiveRulerActive}
          perspectiveEyeLevelY={perspectiveEyeLevelY}
          perspectiveLockHorizon={perspectiveLockHorizon}
          pixelBrushRadius={pixelBrushRadius}
          pixelBusy={pixelBusy}
          pixelCombine={pixelCombine}
          pixelMagneticLasso={pixelMagneticLasso}
          onTogglePixelMagneticLasso={() => setPixelMagneticLasso((v) => !v)}
          pixelForceCircle={pixelForceCircle}
          pixelSel={pixelSel}
          pixelSelectionCanRedo={canRedoPixelSelectionHistory(
            pixelSelectionHistory,
            selected?.type === "image" ? selected.id : null
          )}
          pixelSelectionCanUndo={canUndoPixelSelectionHistory(
            pixelSelectionHistory,
            selected?.type === "image" ? selected.id : null
          )}
          pixelTool={pixelTool}
          polyLassoSession={polyLassoSession}
          postCorrection={postCorrection}
          preserveCorners={preserveCorners}
          pressureCurve={pressureCurve}
          propsSheetRef={propsSheetRef}
          puppetWarpActive={puppetWarpActive}
          puppetWarpBusy={puppetWarpBusy}
          puppetWarpPins={puppetWarpPins}
          quickShapeActive={quickShapeActive}
          recentColors={recentColors}
          rightResize={rightResize}
          savedBrushes={savedBrushes}
          openBrushLibraryRepository={productBrushRepository}
          saving={saving}
          studioFilterPreparationBusy={studioFilterPreparationBusy}
          studioLayerLiftDisabledReason={studioLayerLiftDisabledReason}
          scrollViewportStore={scrollViewportStore}
          selected={selected}
          selectedBg3dEditSource={selectedBg3dEditSource}
          selectedBubbleTailGeometry={selectedBubbleTailGeometry}
          selectedContentMutationLocked={selectedContentMutationLocked}
          selectedId={selectedId}
          selectedRasterSource={selectedProjectedImageSource}
          selectedWorkAssetDestructiveEditReason={selectedWorkAssetDestructiveEditReason}
          setSelectedId={setSelectedId}
          autoColorScribbleCanvasArmed={autoColorScribbleCanvasArmed}
          setAutoColorScribbleCanvasArmed={setAutoColorScribbleCanvasArmed}
          autoColorCanvasSeedHit={autoColorCanvasSeedHit}
          setAutoColorCanvasSeedHit={setAutoColorCanvasSeedHit}
          autoColorCanvasSeedHits={autoColorCanvasSeedHits}
          setAutoColorCanvasSeedHits={setAutoColorCanvasSeedHits}
          onAutoColorPlanImageSize={(size: { width: number; height: number } | null) => {
            autoColorPlanImageSizeRef.current = size;
          }}
          setAdvancedFillPreview={setAdvancedFillPreview}
          setAdvancedFillStatus={setAdvancedFillStatus}
          setAiColorizePrompt={setAiColorizePrompt}
          setBg3dInitialDataUrl={setBg3dInitialDataUrl}
          setBg3dInitialElementId={setBg3dInitialElementId}
          setBg3dInitialScene={setBg3dInitialScene}
          setBg3dOpen={setBg3dOpen}
          setBrushDynamics={setBrushDynamics}
          setBrushOpacity={setBrushOpacity}
          setBubbleShapeEditActive={setBubbleShapeEditActive}
          setColor={setColor}
          setCropAspect={setCropAspect}
          setCropRect={setCropRect}
          setDrawShape={setDrawShape}
          setEyedropperActive={setEyedropperActive}
          setFilterClipboard={setFilterClipboard}
          setGridSize={setGridSize}
          setHealCloneAligned={setHealCloneAligned}
          setHealCloneHardness={setHealCloneHardness}
          setHealCloneOpacity={setHealCloneOpacity}
          setHealCloneRadius={setHealCloneRadius}
          setHealCloneTool={setHealCloneTool}
          setHistoryBrushActive={setHistoryBrushActive}
          setHistoryBrushHardness={setHistoryBrushHardness}
          setHistoryBrushOpacity={setHistoryBrushOpacity}
          setHistoryBrushRadius={setHistoryBrushRadius}
          setHistoryBrushSourceIndex={setHistoryBrushSourceIndex}
          setHistoryBrushSourceSrc={setHistoryBrushSourceSrc}
          setHistoryPanelOpen={setHistoryPanelOpen}
          setFilterMaskHardness={setFilterMaskHardness}
          setFilterMaskPaintActive={setFilterMaskPaintActive}
          setFilterMaskPaintMode={setFilterMaskPaintMode}
          setFilterMaskRadius={setFilterMaskRadius}
          setFilterMaskStrength={setFilterMaskStrength}
          setLayerMaskHardness={setLayerMaskHardness}
          setLayerMaskPaintActive={setLayerMaskPaintActive}
          setLayerMaskPaintMode={setLayerMaskPaintMode}
          setLayerMaskRadius={setLayerMaskRadius}
          setLayerMaskStrength={setLayerMaskStrength}
          setLiquifyRadius={setLiquifyRadius}
          setLiquifyMode={setLiquifyMode}
          setLiquifyStrength={setLiquifyStrength}
          setMagicResizeStrategy={setMagicResizeStrategy}
          setMenu={setMenu}
          setMobileInspectorSnap={setMobileInspectorSnap}
          setMobileSheet={setMobileSheet}
          setNodeEditTool={setNodeEditTool}
          setNodeSmoothStrength={setNodeSmoothStrength}
          setPageGradePanelOpen={setPageGradePanelOpen}
          setPanelSplitActive={setPanelSplitActive}
          setPanelSplitHint={setPanelSplitHint}
          setPanelSplitRatio={setPanelSplitRatio}
          setPerspectiveRulerActive={setPerspectiveRulerActive}
          setPixelBrushRadius={setPixelBrushRadius}
          setPixelCombine={setPixelCombine}
          setPixelForceCircle={setPixelForceCircle}
          commitPixelSelectionState={commitPixelSelectionState}
          resetPixelSelectionState={(selection) => resetPixelSelectionHistoryState(
            selected?.type === "image" ? selected.id : null,
            selection
          )}
          undoPixelSelectionState={() => {
            applyPixelSelectionHistoryCommand("undo");
          }}
          redoPixelSelectionState={() => {
            applyPixelSelectionHistoryCommand("redo");
          }}
          runColorRangeApply={runColorRangeApply}
          setColorRangeFuzziness={setColorRangeFuzziness}
          setColorRangePickActive={setColorRangePickActive}
          setColorRangePreviewEnabled={setColorRangePreviewEnabled}
          setColorRangeSamples={setColorRangeSamples}
          setPixelTool={setPixelTool}
          setPoserInitialDataUrl={setPoserInitialDataUrl}
          setPoserInitialElementId={setPoserInitialElementId}
          setPoserVrmOpen={setPoserVrmOpen}
          setPostCorrection={setPostCorrection}
          setPreserveCorners={setPreserveCorners}
          setPressureCurve={setPressureCurve}
          pressureMinSize={pressureMinSize}
          setPressureMinSize={setPressureMinSize}
          setPuppetWarpActive={setPuppetWarpActive}
          setPuppetWarpPins={setPuppetWarpPins}
          setQuickShapeActive={setQuickShapeActive}
          setRightPanelOpen={setRightPanelOpenWithOverride}
          setSavedBrushes={commitSavedBrushProjection}
          setShapeFill={setShapeFill}
          setSharedDocumentNotice={setSharedDocumentNotice}
          setShowGrid={setShowGrid}
          setShowAlignmentGuides={setAlignmentGuidesVisible}
          setShowWebtoonGuides={setShowWebtoonGuides}
          setSmudgeRadius={setSmudgeRadius}
          setSmudgeStrength={setSmudgeStrength}
          setDodgeBurnExposure={setDodgeBurnExposure}
          setDodgeBurnHardness={setDodgeBurnHardness}
          setDodgeBurnMode={setDodgeBurnMode}
          setDodgeBurnRadius={setDodgeBurnRadius}
          setDodgeBurnRange={setDodgeBurnRange}
          setDodgeBurnSponge={setDodgeBurnSponge}
          setWetMixHardness={setWetMixHardness}
          setWetMixPickup={setWetMixPickup}
          setWetMixRadius={setWetMixRadius}
          setWetMixStrength={setWetMixStrength}
          setWetMixWetness={setWetMixWetness}
          setSnapEnabled={setSnapEnabledVisible}
          setStabilizer={setStabilizer}
          setStabilizerMode={setStabilizerMode}
          setStampTuning={setStampTuning}
          setStrokeWidth={setStrokeWidth}
          setSymmetryCenterX={setSymmetryCenterX}
          setSymmetryCenterY={setSymmetryCenterY}
          setSymmetryRadialCount={setSymmetryRadialCount}
          setSymmetryType={changeStudioSymmetryType}
          setTiltEnabled={setTiltEnabled}
          setTipAngle={setTipAngle}
          setTipRoundness={setTipRoundness}
          setTool={setTool}
          setUserGuides={setUserGuides}
          setUseVelocityPressure={setUseVelocityPressure}
          setVelocitySensitivity={setVelocitySensitivity}
          setWandTolerance={setWandTolerance}
          shapeFill={shapeFill}
          showGrid={showGrid}
          showWebtoonGuides={showWebtoonGuides}
          smudgeActive={smudgeActive}
          smudgeBusy={smudgeBusy}
          smudgeRadius={smudgeRadius}
          smudgeStrength={smudgeStrength}
          extendedBlendBusy={layerMergeBusy}
          extendedBlendMode={extendedBlendMode}
          extendedBlendOpacity={extendedBlendOpacity}
          extendedBlendUnavailableReason={(() => {
            if (selected?.type !== "image") return "이미지 요소를 선택하세요.";
            const index = elements.findIndex((element) => element.id === selected.id);
            const below = index > 0 ? elements[index - 1] : undefined;
            if (below?.type !== "image") return "바로 아래에 이미지 레이어가 있어야 합니다.";
            return null;
          })()}
          applyExtendedBlendMergeDown={applyExtendedBlendMergeDown}
          setExtendedBlendMode={setExtendedBlendMode}
          setExtendedBlendOpacity={setExtendedBlendOpacity}
          pathBooleanBusy={pathBooleanBusy}
          pathBooleanUnavailableReason={studioPathBooleanUnavailableReason(
            marqueeIds.map((id) => elementById.get(id)).filter((el): el is El => Boolean(el))
          )}
          applyPathBooleanCombine={(op) => void applyPathBooleanCombine(op)}
          paperVectorRefinementBusy={paperVectorRefinementBusy}
          paperVectorRefinementUnavailableReason={
            paperVectorRefinementUnavailableReason
          }
          applyPaperVectorRefinement={(operation) => {
            void applyPaperVectorRefinement(operation);
          }}
          cancelPaperVectorRefinement={cancelPaperVectorRefinement}
          dodgeBurnActive={dodgeBurnActive}
          dodgeBurnBusy={dodgeBurnBusy}
          dodgeBurnExposure={dodgeBurnExposure}
          dodgeBurnHardness={dodgeBurnHardness}
          dodgeBurnMode={dodgeBurnMode}
          dodgeBurnRadius={dodgeBurnRadius}
          dodgeBurnRange={dodgeBurnRange}
          dodgeBurnSponge={dodgeBurnSponge}
          wetMixActive={wetMixActive}
          wetMixBusy={wetMixBusy}
          wetMixHardness={wetMixHardness}
          wetMixPickup={wetMixPickup}
          wetMixRadius={wetMixRadius}
          wetMixStrength={wetMixStrength}
          wetMixWetness={wetMixWetness}
          snapEnabled={snapEnabled}
          showAlignmentGuides={showAlignmentGuides}
          stabilizer={stabilizer}
          stabilizerMode={stabilizerMode}
          stampTuning={stampTuning}
          strokeWidth={strokeWidth}
          symmetryCenterX={symmetryCenterX}
          symmetryCenterY={symmetryCenterY}
          symmetryRadialCount={symmetryRadialCount}
          symmetryType={symmetryType}
          tagsText={tagsText}
          timelinePlaying={timelinePlaying}
          tiltEnabled={tiltEnabled}
          tipAngle={tipAngle}
          tipRoundness={tipRoundness}
          title={title}
          titleInputRef={titleInputRef}
          pendingSaveIntent={pendingSaveIntent}
          onContinuePendingSave={onContinuePendingSave}
          onClearWorkMetadataError={onClearWorkMetadataError}
          tool={tool}
          userGuides={userGuides}
          useVelocityPressure={useVelocityPressure}
          vanishingPoints={vanishingPoints}
          velocitySensitivity={velocitySensitivity}
          visibleRightPanelOpen={visibleRightPanelOpen}
          wandTolerance={wandTolerance}
          webtoonGuides={webtoonGuides}
          webtoonTheme={webtoonTheme}
            stableHandlers={studioInspectorAsideHandlers}
          />
          </Suspense>
        ) : null}

        {isMobile ? (
          <Suspense fallback={null}>
            <StudioMobileEditingDock
          activeCatalogBrushId={activeCatalogBrush.id}
          activeCatalogBrushName={activeCatalogBrush.name}
          activeSavedBrushId={activeSavedBrushId}
          activeSurfaceReviewLocked={activeSurfaceReviewLocked}
          advancedFillActive={advancedFillActive}
          advancedFillUnsupportedReason={advancedFillUnsupportedReason}
          brush={brush}
          brushCatalogHandlers={studioBrushCatalogHandlers}
          brushCatalogOpen={brushCatalogSession?.placement === "mobile-sheet"}
          brushDefaultRestore={brushBaselineController.restoreState}
          brushDynamics={brushDynamics}
          brushManagerSheetRef={brushManagerSheetRef}
          brushOpacity={brushOpacity}
          collaborationDocumentLocked={collaborationDocumentLocked}
          commentPinArmed={commentPlacementActive}
          color={color}
          colorBlindPreview={colorBlindPreview}
          colorVisionSheetRef={colorVisionSheetRef}
          currentBrushSnapshot={currentBrushSnapshot}
          drawMode={drawMode}
          drawShape={drawShape}
          drawSheetRef={drawSheetRef}
          eraseToIntersection={eraseToIntersection}
          filterMutationLocked={menuFilterDisabled}
          filterPreparationBusy={studioFilterPreparationBusy}
          filterTargetLabel={studioFilterTargetLabel}
          filterUnavailableReason={studioFilterUnavailableReason}
          hi={hi}
          history={history}
          sidecarUndoAvailable={studioHistorySidecarUndoAvailable}
          sidecarRedoAvailable={studioHistorySidecarRedoAvailable}
          isMobile={isMobile}
          livingInk={{
            ...studioOptionsBarsDrawModel.livingInk,
            onPhysicalModeEnabledChange:
              studioOptionsBarsHandlers.setLivingInkPhysicalModeEnabled,
            onModeChange: studioOptionsBarsHandlers.setLivingInkMode,
            onScopeChange: studioOptionsBarsHandlers.setLivingInkScope,
            onFix: studioOptionsBarsHandlers.applyLivingInkFix,
            onClear: studioOptionsBarsHandlers.applyLivingInkClear,
            onMaterialChange: studioOptionsBarsHandlers.patchLivingInkMaterial,
          }}
          marqueeIds={marqueeIds}
          mobileBrushDockButtonRef={mobileBrushDockButtonRef}
          mobileKeyboardInset={mobileKeyboardInset}
          mobileQuickActionsButton={mobileQuickActionsButton}
          mobileSheet={mobileSheet}
          postCorrection={postCorrection}
          preserveCorners={preserveCorners}
          pressureCurve={pressureCurve}
          proDrawPrefs={proDrawPrefs}
          quickActionsOpen={quickActionsOpen}
          savedBrushes={savedBrushes}
          openBrushLibraryRepository={productBrushRepository}
          selected={selected}
          selectionLocked={mobileSelectionLocked}
          selectionTextEditLabel={studioOptionsBarsSelectionModel.textEditLabel}
          setBrushDynamics={setBrushDynamics}
          setBrushOpacity={setBrushOpacity}
          setColor={setColor}
          setColorBlindPreview={setColorBlindPreview}
          setDrawMode={setDrawMode}
          setDrawShape={setDrawShape}
          setEraseToIntersection={setEraseToIntersection}
          setMarqueeIds={setMarqueeIds}
          setMenu={setMenu}
          setMobileSheet={setMobileSheet}
          setPostCorrection={setPostCorrection}
          setPreserveCorners={setPreserveCorners}
          setPressureCurve={setPressureCurve}
          pressureMinSize={pressureMinSize}
          setPressureMinSize={setPressureMinSize}
          setQuickStartOpen={setQuickStartOpen}
          setSavedBrushes={commitSavedBrushProjection}
          setSelectedId={setSelectedId}
          setShapeFill={setShapeFill}
          setStampTuning={setStampTuning}
          setStabilizer={setStabilizer}
          setStabilizerMode={setStabilizerMode}
          setStrokeWidth={setStrokeWidth}
          setTiltEnabled={setTiltEnabled}
          setTipAngle={setTipAngle}
          setTipRoundness={setTipRoundness}
          setTool={setTool}
          setUseVelocityPressure={setUseVelocityPressure}
          setVelocitySensitivity={setVelocitySensitivity}
          setZoom={setZoom}
          shapeFill={shapeFill}
          showMobileHint={showMobileHint}
          stabilizer={stabilizer}
          stabilizerMode={stabilizerMode}
          stampTuning={stampTuning}
          strokeWidth={strokeWidth}
          tiltEnabled={tiltEnabled}
          tipAngle={tipAngle}
          tipRoundness={tipRoundness}
          tool={tool}
          ui={STUDIO_MOBILE_EDITING_DOCK_UI}
          useVelocityPressure={useVelocityPressure}
          velocitySensitivity={velocitySensitivity}
          workspaceState={workspaceState}
          zoom={zoom}
              stableHandlers={studioMobileEditingDockHandlers}
            />
          </Suspense>
        ) : null}
    </>
  );
}
