export const STUDIO_COMPANION_REFERENCE_RASTER_WORKER_MAX_DATA_URL_CHARS = 32 * 1024 * 1024;
export const STUDIO_COMPANION_REFERENCE_RASTER_WORKER_MAX_INPUT_BYTES = 64 * 1024 * 1024;
export const STUDIO_COMPANION_REFERENCE_RASTER_WORKER_MAX_OUTPUT_BYTES = 32 * 1024 * 1024;
export const STUDIO_COMPANION_REFERENCE_RASTER_WORKER_MAX_WIDTH = 1_280;
export const STUDIO_COMPANION_REFERENCE_RASTER_WORKER_MAX_HEIGHT = 720;
